// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsequenceClass } from "./ConsequenceClass";
import type { CustomSection } from "./CustomSection";
import type { DeflectionClass } from "./DeflectionClass";
import type { ForcePoint } from "./ForcePoint";
import type { LateralBracing } from "./LateralBracing";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { Staafeinden } from "./Staafeinden";
import type { Staafstand } from "./Staafstand";

/**
 * Invoer van één staaltoetsing.
 *
 * `deny_unknown_fields`: een onbekend veld is een **fout**, geen ruis. Zeven
 * velden hieronder hebben `#[serde(default)]`, en een tikfout in zo'n
 * veldnaam zou anders stilzwijgend op 0 uitkomen. Bij `q_equiv_n_per_mm` en
 * `z_a_mm` valt de kiptoets daarmee *gunstiger* uit dan hij hoort te zijn —
 * onveilig aan de verkeerde kant, en onzichtbaar in het resultaat.
 */
export type BeamCheckInput = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, beam_id: number, profile_name: string, steel_grade: string, length_m: number, forces_envelope: Array<ForcePoint>, lateral_bracing: LateralBracing, 
/**
 * Kniklengte om de sterke y-as, in m — knik IN het vlak van het model.
 *
 * `0` of weglaten = niet opgegeven: de kern houdt dan de staaflengte aan
 * en zegt dat in de afleiding ("staaflengte (terugval)"). Tot september
 * 2026 vulde de frontend die terugval zelf in, en kon de toets niet zien
 * dat het een terugval was. Een negatieve of niet-eindige waarde wordt
 * genegeerd mét een kanttekening; een kniklengte van nul zou χ = 1 geven.
 *
 * In het vlakke model van deze app is y altijd de sterke as in het vlak:
 * de oplosser rekent met I_y, en een staaf kent geen doorsnederotatie.
 */
buckling_length_y_m: number, 
/**
 * Kniklengte om de zwakke z-as, in m — knik UIT het vlak van het model.
 *
 * `0` of weglaten = niet opgegeven. De kern leidt L_cr,z dan af uit
 * [`Self::lateral_bracing`], maar ALLEEN op plaatsen waar een kipsteun aan
 * de boven- én aan de onderflens zit: alleen daar wordt de doorsnede als
 * geheel zijdelings gehouden. Zonder zo'n paar geldt de staaflengte. Zie
 * `nen_en_1993_1_1_stability::kniklengte` voor de regel en de normgrond;
 * de gebruikte waarde en haar herkomst staan in de toets.
 */
buckling_length_z_m: number, deflection_limit_class: DeflectionClass, 
/**
 * Noemer n in de eis L/n; alleen gelezen bij klasse `Custom`.
 *
 * `i32` en niet `u32`: een negatieve noemer is een invoerfout die de kern
 * per staaf met reden weigert ([`crate::deflection::keur_noemers`]). Met
 * `u32` liep zo'n getal al vast bij het inlezen, en dan viel de hele
 * aanroep met alle staven weg in plaats van alleen deze staaf.
 */
deflection_limit_numerator: number, deflection_actual_max_mm: number, 
/**
 * Is deze staaf een uitkraging?
 *
 * Tot september 2026 werd dit veld door de kern NERGENS gelezen: alleen
 * [`DeflectionClass::Cantilever`] deed iets, en dan nog uitsluitend via de
 * w_fin-noemer 150 op de staaflengte. Nu bepaalt het samen met de klasse
 * de referentielengte ℓ_rep = 2·L voor de w_add-grens
 * ("ℓ_rep is de lengte van een overspanning of tweemaal de lengte van een
 * uitkraging", NEN-EN 1990:2002/NB:2019 A1.4.3(3)). Eén van beide volstaat;
 * de frontend zet ze allebei.
 *
 * Let op de asymmetrie met w_fin: die kant verdubbelt ℓ_rep NIET maar
 * gebruikt noemer 150 op de staaflengte, wat op ℓ_rep/300 neerkomt.
 * Strenger dan de ℓ_rep/250 uit A1.4.3(4), dus veilig — maar het is een
 * andere manier om hetzelfde uit te drukken, en dat staat als notitie in
 * het rapport.
 */
is_cantilever: boolean, 
/**
 * Gevolgklasse van het project — in deze kern ALLEEN ter vermelding.
 * NEN-EN 1990:2002/NB:2019 verwerkt K_FI in de partiële belastingsfactoren
 * zelf (tabel NB.4 voor CC2, NB.5 voor CC1 en CC3); de krachten in
 * `forces_envelope` dragen die factoren al. De kern vermenigvuldigt dus
 * niets met K_FI, want dan telde de klasse dubbel.
 */
consequence_class: ConsequenceClass, 
/**
 * Zeeg (pre-camber) in mm, POSITIEF = OMHOOG: een zeeg die tegen een
 * doorhangende ligger in werkt is een positief getal. De zakking zelf
 * ([`Self::deflection_actual_max_mm`]) is negatief omlaag, dus de
 * eindzakking is w_fin = w_z + w_zeeg; zie
 * [`crate::deflection::w_fin_mm`] voor de grond in NEN-EN 1990 figuur A1.1.
 */
pre_camber_mm: number, 
/**
 * Doorbuiging onder de permanente BGT-combinatie (mm), voor w_add.
 */
deflection_permanent_mm: number, 
/**
 * Noemer n in de grenswaarde L/n voor de **bijkomende** zakking w_add.
 *
 * `0` of afwezig = de waarde die bij [`Self::deflection_limit_class`]
 * hoort volgens NEN-EN 1990:2002/NB:2019 A1.4.3(3); zie
 * [`crate::deflection::w_add_grens`]. Een waarde > 0 overschrijft die
 * klassewaarde en wordt op de **staaflengte** toegepast (dus zonder de
 * verdubbeling ℓ_rep = 2·L bij een uitkraging) — precies zoals een
 * externe referentie-uitwerking met een vaste noemer rekent. Het rapport
 * vermeldt dan dat de noemer is opgegeven en niet uit de norm volgt.
 *
 * `f64` en niet `u32`, omdat de NB-waarde 3/1000 een noemer van 333⅓
 * oplevert; met een geheel getal was die niet exact op te geven.
 */
deflection_add_limit_numerator: number, 
/**
 * Vrije toelichtingen bij de doorbuigingstoets, die letterlijk in de
 * `notes` van de w_fin-regel van het rapport belanden.
 *
 * Waarom dit bestaat: [`Self::deflection_actual_max_mm`] is een kaal
 * getal. Waar het vandaan komt — vanaf welke referentielijn het is
 * gemeten, over welke lengte, en of de aanroeper daarbij iets heeft moeten
 * aannemen — weet alleen de bouwer die de invoer samenstelt. Zonder dit
 * kanaal zou zo'n aanname onzichtbaar zijn in het rapport.
 */
deflection_notes: Array<string>, 
/**
 * Equivalente gelijkmatig verdeelde belasting in het kipveld (N/mm),
 * voor B* volgens NB.NB.4.3(3). 0 = alleen eindmomenten.
 */
q_equiv_n_per_mm: number, 
/**
 * Afstand zwaartepunt → aangrijpingspunt van de belasting (mm).
 * Positief = boven het zwaartepunt (destabiliserend, bijvoorbeeld een
 * belasting op de bovenflens: z_a ≈ h/2).
 */
z_a_mm: number, 
/**
 * Inline opgegeven doorsnede (D4.3). Is dit veld gevuld, dan wordt de
 * profielendatabase **niet** geraadpleegd en rekent de toetsing op deze
 * doorsnede. `None` (of ontbrekend in de JSON) = het bestaande pad via
 * [`BeamCheckInput::profile_name`], bit-identiek aan voorheen.
 *
 * `#[ts(optional)]`: in TypeScript is het veld weglaatbaar, zodat de
 * bestaande bouwers in de frontend ongewijzigd blijven compileren.
 */
custom_section?: CustomSection, 
/**
 * Hoe de staaf in het model staat — alleen voor de benaming van de
 * flenzen in de afleiding van de kiptoets.
 *
 * De krachtenomhullende hoort in de referentierichting van de staaf te
 * staan: liggend van links naar rechts, staand van voet naar kop. "Boven-
 * flens" en "onderflens" zijn dan bij een liggende staaf letterlijk; bij
 * een staande staaf is de bovenflens de LINKERflens en de onderflens de
 * RECHTERflens, en dat zet de kern er dan bij. `None` of weglaten =
 * [`Staafstand::Liggend`], het gedrag van vóór dit veld.
 */
staafstand?: Staafstand, 
/**
 * Kanttekeningen bij de staafstand die de BOUWER van de invoer opstelt. De
 * kern zet ze letterlijk bij de kiptoets, achter de flenzen in
 * wereldtermen, en rekent er nergens mee.
 *
 * WAAROM. Aan welke fysieke zijde "bovenflens" ligt, springt bij een naar
 * links hellende staaf op 75° van het bovenvlak naar het ondervlak (zie
 * `design-mockup/src/lib/referentierichting.ts`, DE SPRONG BIJ 75°). Of een
 * staaf dicht bij die sprong ligt, weet alleen wie de meetkunde kent; de
 * kern krijgt alleen de omhullende. Zonder dit kanaal zou de waarschuwing
 * niet in de afleiding en niet in het rapport komen. `None` of een lege
 * lijst = geen kanttekening.
 */
staafstand_notities?: Array<string>, 
/**
 * Wat er aan de twee staafeinden zit — zie [`Staafeinden`]. `None` of
 * weglaten = beide een gaffel, het gedrag van vóór dit veld.
 */
staafeinden?: Staafeinden, 
/**
 * Toelichtingen bij de STAAF ALS GEHEEL, die de bouwer van de invoer
 * opstelt en die de kern letterlijk bij de kniktoets (6.3.1), de kiptoets
 * (6.3.2) en de eindzakking zet. Rekenen nergens mee.
 *
 * WAAROM. Een staaf die door tussenknopen in delen is geknipt, wordt door
 * de invoerbouwer als één doorgaande lijn getoetst; welke delen dat zijn,
 * hoe lang de lijn is en welke tussenknopen niet als steun tellen, weet
 * alleen de bouwer. Zonder dit kanaal zou de lezer van het rapport een
 * staaf van 12 m zien waar het model er twee van 6 m toont, zonder uitleg.
 */
staaf_notities?: Array<string>, 
/**
 * Profiel aan het EIND van de staaf (x = L) van een VERLOPENDE staaf;
 * [`Self::profile_name`] is dan het profiel aan het begin (x = 0). De
 * maten h, b, t_w en t_f verlopen lineair tussen de twee, en de doorsnede
 * telt over de hele staaf als GELAST I-profiel zonder afrondingsstraal
 * (ontwerpbesluit van 15 september 2026, §2): knikkromme en kipkromme voor
 * gelaste profielen, tabel 6.2 en 6.5.
 *
 * De KERN bepaalt per krachtpunt de plaatselijke doorsnede en toetst
 * elke doorsnedetoets op elk punt; de stabiliteitstoetsen rekenen met de
 * kleinste doorsnede in het betreffende veld. Zie `crate::verlopend`.
 *
 * Beide uiteinden moeten I/H-profielen zijn: uit de catalogus, of als
 * GELASTE dubbelsymmetrische I uit drie platen ([`Self::custom_section`]
 * voor het begin, [`Self::custom_section_end`] voor het eind). Dat laatste
 * is geen uitbreiding om de uitbreiding: het SPLITSEN van een verlopende
 * staaf laat op de splitsplaats precies zo'n doorsnede achter, en zonder
 * dit pad zou een gesplitste staaf niet meer te toetsen zijn. Een koker,
 * buis, hoeklijn, U-profiel, een I-profiel met toelopende flenzen of een
 * eigen doorsnede van een andere vorm wordt geweigerd met reden. `None`,
 * leeg of gelijk aan `profile_name` = prismatisch: dan verandert er
 * niets aan de bestaande toetsing, tot op het laatste getal.
 */
profile_end?: string, 
/**
 * De doorsnede aan het EIND van een verlopende staaf, wanneer dat eind
 * geen catalogusprofiel is maar een gelaste dubbelsymmetrische I uit drie
 * platen. Alleen gelezen wanneer [`Self::profile_end`] gevuld is; de naam
 * erin is de naam die in het rapport komt.
 *
 * Waarom een apart veld en niet gewoon een naam: een gelaste doorsnede
 * staat in geen enkele catalogus, dus er is geen naam waaraan haar maten
 * te ontlenen zijn. Zou de kern ze uit de naam moeten raden, dan zou zij
 * rekenen met iets wat niemand heeft opgegeven.
 */
custom_section_end?: CustomSection, };
