// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResistanceCalc } from "./ResistanceCalc";
import type { StabilityCalc } from "./StabilityCalc";

export type CheckKind = { "type": "Resistance", "data": ResistanceCalc } | { "type": "Stability", "data": StabilityCalc };
