// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén lamel (rechthoekige plaat) van een inline opgegeven doorsnede.
 *
 * Zelfde afspraken als [`section_properties::composite::Lamella`]: `b_mm` is
 * de lengte in de lengterichting van de plaat, `t_mm` de dikte daar loodrecht
 * op, `(y_mm, z_mm)` het zwaartepunt van de plaat en `alpha_rad` de hoek van
 * de lengterichting met de y-as (0 = liggend, π/2 = staand).
 */
export type CustomLamella = { b_mm: number, t_mm: number, y_mm: number, z_mm: number, alpha_rad: number, };
