// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomPunt } from "./CustomPunt";

/**
 * Een **expliciet gedeclareerde** gesloten cel, voor de Bredt-torsie.
 *
 * Zonder deze declaratie rekent de kern `I_t` met de open formule ⅓·Σb·t³;
 * dat onderschat de torsiestijfheid van een koker met ordes van grootte, en
 * daarom komt er dan een melding in het resultaat.
 */
export type CustomGeslotenCel = { 
/**
 * Hoekpunten van de wandmiddellijn, in volgorde; de cel sluit vanzelf.
 */
midlijn: Array<CustomPunt>, 
/**
 * Wanddikte van de zijde van punt `i` naar punt `i+1`.
 */
dikte_mm: Array<number>, 
/**
 * Indices van de lamellen die de celwanden vormen.
 */
lamellen: Array<number>, };
