// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomDoorsnedevorm } from "./CustomDoorsnedevorm";
import type { CustomGeslotenCel } from "./CustomGeslotenCel";
import type { CustomLamella } from "./CustomLamella";
import type { SectionProperties } from "./SectionProperties";

/**
 * Een inline opgegeven doorsnede.
 *
 * Twee manieren om hem te beschrijven, en precies één daarvan geldt:
 * * **lamellen** — de doorsnede wordt door `section-properties` doorgerekend
 *   en door tabel 5.2 per plaatdeel geklasseerd. Alles (dubbelsymmetrie,
 *   h_w/t_w, gesloten cellen) volgt uit de geometrie.
 * * **eigenschappen** — een kant-en-klare set doorsnede-eigenschappen, met
 *   `vorm` erbij zodat de classificatie weet welk blad van tabel 5.2 geldt.
 *   Hiermee laat een catalogusprofiel zich één-op-één inline meegeven.
 */
export type CustomSection = { 
/**
 * Naam zoals hij in het rapport verschijnt.
 */
naam: string, lamellen: Array<CustomLamella>, gesloten_cellen: Array<CustomGeslotenCel>, 
/**
 * Doorsnede-eigenschappen; alleen gebruikt als `lamellen` leeg is.
 */
eigenschappen: SectionProperties | null, 
/**
 * Vormaanduiding; alleen gebruikt als `lamellen` leeg is.
 */
vorm: CustomDoorsnedevorm, };
