// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vormaanduiding voor een doorsnede die **niet** uit lamellen is opgebouwd.
 *
 * Alleen nodig als [`CustomSection::lamellen`] leeg is: dan is er geen
 * geometrie om tabel 5.2 op los te laten en om de dubbelsymmetrie aan te
 * controleren. Staan er wél lamellen, dan wordt alles uit de geometrie
 * afgeleid en telt dit veld niet mee.
 */
export type CustomDoorsnedevorm = "Onbekend" | "GelasteIDubbelsymmetrisch" | "GelasteIMonosymmetrisch" | "Koker" | "RondeBuis";
