// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Doorbuigingsklasse van een staaf.
 *
 * De klasse bepaalt twee dingen: de noemer voor de eindzakking `w_fin`
 * ([`crate::deflection::default_numerator`]) en de noemer plus de
 * referentielengte ℓ_rep voor de bijkomende zakking `w_add`
 * ([`crate::deflection::w_add_grens`]).
 *
 * De indeling volgt de vier gedachtestreepjes van NEN-EN 1990:2002/NB:2019
 * A1.4.3(3), die de grenswaarden voor w2 + w3 (= de bijkomende doorbuiging)
 * geven. Per variant staat hieronder welk gedachtestreepje erbij hoort; de
 * bijbehorende getallen en belastingscombinaties staan in
 * [`crate::deflection`], want daar worden ze gebruikt.
 *
 * Wat hier bewust GEEN variant is: het vierde gedachtestreepje
 * (vloerafscheidingen ter plaatse van een hoogteverschil, ℓ_rep/150). Dat is
 * geen vloer- of dakligger maar de bovenrand/bovenregel van een balustrade, en
 * de NB geeft daar geen w_max-eis bij; een w_fin-noemer zou dus verzonnen
 * moeten worden. Wie L/150 nodig heeft — bijvoorbeeld om een externe
 * referentie-uitwerking na te bootsen — geeft dat op via
 * [`BeamCheckInput::deflection_add_limit_numerator`], of via `Custom`.
 */
export type DeflectionClass = "Floor" | "FloorBrittlePartitions" | "Roof" | "Cantilever" | "Custom";
