// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InternalForces } from "./InternalForces";

/**
 * Snapshot of force state at a single check location — used in derivation reports.
 */
export type ForceStateSnapshot = { combination_id: number, position_mm: number, forces: InternalForces, };
