// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kipsteunen, als fracties van de staaflengte.
 *
 * `Default` is afgeleid, maar de velden hebben **geen** `#[serde(default)]`:
 * een leeg object `{}` in de JSON levert daarom een fout ("missing field")
 * in plaats van stilzwijgend "geen kipsteunen". Dat is gewild — geen
 * kipsteunen moet je opschrijven als twee lege arrays, niet per ongeluk
 * krijgen. `deny_unknown_fields` maakt bovendien een tikfout in een
 * veldnaam zichtbaar in plaats van dat hij ongemerkt wegvalt.
 */
export type LateralBracing = { top_flange_positions: Array<number>, bottom_flange_positions: Array<number>, };
