// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partiële factoren voor één uitdrukking (STR/GEO of EQU).
 */
export type LoadFactors = { name: string, 
/**
 * γ_G,sup — ongunstig werkende blijvende belasting.
 */
gamma_g_sup: number, 
/**
 * γ_G,inf — gunstig werkende blijvende belasting.
 */
gamma_g_inf: number, 
/**
 * γ_Q — belangrijkste én andere veranderlijke belastingen.
 */
gamma_q: number, };
