// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Toetsdoorsnede } from "./Toetsdoorsnede";

/**
 * Het maatgevende punt over alle doorsnedetoetsen en alle rekenpunten.
 */
export type MaatgevendPunt = { toets_id: string, uc: number, doorsnede: Toetsdoorsnede, };
