// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De doorsnedesoorten in de catalogus.
 *
 * `Angle` is de hoeklijn (EN 10056-1), gelijk- of ongelijkbenig. Hij staat
 * hier apart en niet onder `ISection` omdat er niets van de I-regels op hem
 * van toepassing is: NEN-EN 1993-1-1 tabel 5.2 heeft er een eigen blad voor
 * (blad 3 van 3), par. 1.7(2) legt de assen anders, en de y-y- en z-z-as zijn
 * geen hoofdassen. Wie hem als I-profiel zou meenemen, rekent stilzwijgend
 * met de verkeerde regels.
 */
export type ProfileKind = "ISection" | "Channel" | "Rhs" | "Shs" | "Chs" | "Angle";
