// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ψ-factoren voor één rij van tabel NB.2–A1.1.
 */
export type PsiFactors = { category: string, description: string, psi0: number, psi1: number, psi2: number, };
