// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De taal waarin het rapport zijn datum noemt — de vier talen van de app.
 *
 * Weglaten = Nederlands: de rest van de PDF-tekst is Nederlands, en zo bleef
 * een aanroep van vóór dit veld hetzelfde rapport opleveren. Een onbekende
 * code wordt bij het lezen GEWEIGERD (serde), niet stil vervangen.
 */
export type RapportTaal = "nl" | "en" | "de" | "fr";
