// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Een plaat die de app NIET naar de kern stuurde, met de reden — de spiegel
 * van `PlaatSkip` in `design-mockup/src/lib/plaatCheckBuilder.ts`.
 *
 * Het live rapport toont deze platen in het overzicht; zonder dit type zou de
 * PDF er stil over zijn, en een plaat die ontbreekt zonder woord leest als een
 * plaat die voldoet.
 */
export type RapportPlaatOvergeslagen = { plate_id: number, reden: string, };
