// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeamCheckResult } from "./BeamCheckResult";
import type { BetonStaafZones } from "../concrete/BetonStaafZones";
import type { BetonStijfheidSpoor } from "../concrete/BetonStijfheidSpoor";
import type { CltBeamCheckResult } from "../timber/CltBeamCheckResult";
import type { ConcreteBeamCheckResult } from "../concrete/ConcreteBeamCheckResult";
import type { DekkingslijnAntwoord } from "../concrete/DekkingslijnAntwoord";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { PlateCheckInput } from "../plaat/PlateCheckInput";
import type { PlateCheckResult } from "../plaat/PlateCheckResult";
import type { RapportPlaatOvergeslagen } from "./RapportPlaatOvergeslagen";
import type { RapportTaal } from "./RapportTaal";
import type { SpanningBeamCheckResult } from "../spanning/SpanningBeamCheckResult";
import type { TimberBeamCheckResult } from "../timber/TimberBeamCheckResult";

export type ReportInput = { 
/**
 * De nationale bijlage van het project (normnaad). Zij bepaalt welke
 * UITGAVEN het rapport noemt: de normenregel op omslag en paginakop, het
 * infoblok en de normkolom per staaf komen uit haar rij in
 * `nationale_bijlage::Aanduidingen`.
 *
 * Tot september 2026 kende de PDF dit veld niet en stonden de aanduidingen
 * vast op de Nederlandse rij, terwijl het live rapport en de kernen de
 * bijlage van het project al lazen. Een bijlage die deze uitgave niet kent,
 * wordt bij het lezen GEWEIGERD met reden.
 *
 * `#[serde(default)]`: er is één gevulde rij, dus weglaten kan niets anders
 * betekenen (zie `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`);
 * in TypeScript daarom optioneel.
 */
bijlage?: NationaleBijlage, project_name: string, project_number: string, engineer: string, company: string, 
/**
 * De projectdatum zoals ingevuld, normaal `JJJJ-MM-DD`. Het rapport zet
 * hem op titelblad én paginakop voluit in [`Self::taal`] — zie
 * [`datum::datum_voluit`].
 */
date: string, 
/**
 * De taal waarin het rapport de datum noemt (issue #20): de taal van de
 * app, zodat het papier dezelfde notatie draagt als het live rapport.
 *
 * `#[serde(default)]` = Nederlands, de taal van de overige PDF-tekst; een
 * aanroep zonder dit veld blijft geldig. In TypeScript daarom optioneel.
 */
taal?: RapportTaal, steel_check_results: Array<BeamCheckResult>, 
/**
 * Houttoetsingen (EN 1995-1-1). `#[serde(default)]` zodat bestaande
 * aanroepen zonder dit veld geldig blijven; in TypeScript daarom
 * optioneel.
 */
timber_check_results?: Array<TimberBeamCheckResult>, 
/**
 * Kruislaaghout (EN 1995-1-1, een toets per lamel plus de rolschuif uit
 * bijlage B). Draagt dezelfde velden als een houtresultaat en volgt
 * daarom hetzelfde renderpad; alleen de laagtabel en de laagtekening uit
 * het live rapport blijven hier weg.
 *
 * `#[serde(default)]` om dezelfde reden als bij hout: een bestaande
 * aanroep zonder dit veld blijft geldig.
 */
clt_check_results?: Array<CltBeamCheckResult>, 
/**
 * Betontoetsingen (EN 1992-1-1): buiging met normaalkracht op de
 * doorsnede. `#[serde(default)]` om dezelfde reden als bij hout —
 * bestaande aanroepen zonder dit veld blijven geldig.
 *
 * LET OP bij het lezen van deze resultaten: de betonkern toetst
 * uitsluitend de doorsnede op M en N. Dwarskracht, wringing, pons,
 * scheurwijdte, doorbuiging, tweede-orde-effecten en de
 * detailleringsregels zitten er NIET in; zie het beperkingenblok van de
 * betonsectie in het live rapport.
 *
 * De tweede orde is daarmee niet per se afwezig uit de BEREKENING: het
 * analysetype "2e orde + fysisch" bepaalt de krachtsverdeling met de
 * algemene methode van 5.8.6, via `concrete_check::segments` en de lus in
 * de frontend. Dat spoor reist mee in [`Self::concrete_stiffness_trace`],
 * en daaruit bouwt [`crate::betonhoofdstuk`] het hoofdstuk "Beton —
 * fysisch niet-lineaire tweede orde" mét de vier figuren.
 */
concrete_check_results?: Array<ConcreteBeamCheckResult>, 
/**
 * De vrije spanningstoets: een doorsnede en een OPGEGEVEN toelaatbare
 * spanning, getoetst op de vergelijkspanning van von Mises. Hoort bij géén
 * norm, en het rapport zegt dat ook zo — zie [`ReportMember::norm`].
 *
 * Zonder dit veld levert een model met uitsluitend vrije materialen een
 * rapport zonder één getoetste staaf, terwijl de gebruiker wél heeft
 * getoetst. Daarom reist het mee.
 *
 * `#[serde(default)]` om dezelfde reden als bij de andere kernen.
 */
stress_check_results?: Array<SpanningBeamCheckResult>, 
/**
 * Het segmentspoor van de fysisch niet-lineaire tweede orde: per
 * belastingcombinatie de segmenttabel van de laatste ronde, het
 * convergentieverloop, de doorsnede en de korf per staaf, en de
 * verplichte kruipvermelding zoals de kern die teruggeeft.
 *
 * `#[serde(default)]` om dezelfde reden als bij hout en beton: een
 * bestaande aanroep zonder dit veld blijft geldig, en in TypeScript is
 * het daarom optioneel.
 *
 * Ontbreekt het spoor, dan blijft het betonhoofdstuk weg wanneer er ook
 * geen betontoetsingen zijn; zijn die er wél, dan staat het hoofdstuk er
 * met de eerlijke melding dat er niet fysisch gerekend is. Dat verschil is
 * hetzelfde onderscheid dat `design-mockup/src/lib/sectieRelevantie.ts`
 * maakt: "kan dit model dit ooit vullen" laat een hoofdstuk weg, "is het
 * nu leeg" is een rekenstand en laat het staan.
 */
concrete_stiffness_trace?: BetonStijfheidSpoor, 
/**
 * De dekkingslijnen die de rekenkern heeft geleverd — figuur 9.2 van
 * art. 9.2.1.3 als gegevens, per staaf.
 *
 * Dit is een APARTE vraag aan de kern (`concrete_dekkingslijn`) en geen
 * bijproduct van de toetsing: de dekkingslijn vraagt om een z, een c_d en
 * eventueel een A_sl die de doorsnedetoets niet nodig heeft. Zij komt er
 * dus alleen in als iemand haar heeft opgevraagd, en het hoofdstuk blijft
 * anders weg — zie [`crate::betondekking::van_toepassing`].
 *
 * `#[serde(default)]` om dezelfde reden als bij de andere kernen: een
 * bestaande aanroep zonder dit veld blijft geldig.
 */
concrete_dekkingslijnen?: Array<DekkingslijnAntwoord>, 
/**
 * De wapeningszones per betonstaaf, zoals de toetsing ze gekregen heeft.
 *
 * Zonder dit veld toont het rapport bij een staaf met ingekorte wapening
 * alleen de BASISkorf, terwijl er per snede met `cage_at_mm` is gerekend —
 * en dan is een unity check niet na te rekenen. Zie [`crate::betonzones`].
 *
 * `#[serde(default)]`: een aanroeper die geen zones kent, stuurt niets mee
 * en het blok blijft weg.
 */
concrete_reinforcement_zones?: Array<BetonStaafZones>, 
/**
 * De scheefstand die deze berekening in is gegaan, als tekstblok met alle
 * tussenwaarden en normartikelen.
 *
 * WOORDELIJK uit `design-mockup/src/lib/scheefstandNorm.ts`
 * (`scheefstandToelichting`), en dat is de hele reden dat dit een String
 * is en geen verzameling getallen: die functie kent de drie normen
 * (EN 1993-1-1 (5.5), EN 1992-1-1 (5.1) en EN 1995-1-1 (5.1)), de stand
 * "ongunstigste", de vraag of h en m handmatig zijn opgegeven of uit de
 * meetkunde volgen, en de waarschuwingen die daarbij horen. Dat hier
 * naspelen zou een tweede lezing van dezelfde norm opleveren, en de twee
 * zouden uiteen gaan lopen zonder dat iemand het ziet.
 *
 * Leeg of afwezig = de aanroeper heeft de scheefstand niet meegestuurd;
 * het rapport zwijgt er dan over in plaats van een vaste 1/200 te
 * suggereren.
 */
scheefstand_toelichting?: string, 
/**
 * Het analysetype en de kritieke lastfactor α_cr per UGT-combinatie, als
 * tekstblok — woordelijk uit `solver/alphaCr.ts` (`analyseToelichting`).
 *
 * Waarom dit in het rapport hoort (basisaudit nr 27): het staalrapport
 * noemde nergens of de krachten eerste of tweede orde waren, terwijl
 * NEN-EN 1993-1-1 5.2.1(3) eerste orde alleen bij α_cr ≥ 10 toestaat en
 * 5.2.2(7)b de terugval van de kniklengte op de systeemlengte aan een
 * tweede-orde-berekening met imperfecties bindt. Een regel die met "!"
 * begint is een waarschuwing of fout en wordt rood gezet.
 *
 * Leeg of afwezig = niet meegestuurd; het rapport zwijgt dan.
 */
analyse_toelichting?: string, 
/**
 * De windbelasting zoals de windgenerator haar in het model zette, als
 * tekstblok — woordelijk uit `lib/wind/windGenerator.ts`
 * (`vrijstaandDakUitgangspunten`): een kopregel met de normgrondslag
 * (NEN-EN 1991-1-4 §7.3) en per gegenereerd belastinggeval de omschrijving
 * van zijn lasten (tabel, α, φ en de gebruikte coëfficiënt).
 *
 * Waarom (issue #16): het live rapport noemde per windlast waar het getal
 * vandaan kwam, het papier niet. Een windlast zonder tabel en cel is niet
 * na te rekenen, en de PDF is het stuk dat wordt ingediend.
 *
 * Een String en geen getallen om dezelfde reden als de scheefstand: de
 * generator kent de tabelopzoeking en de interpolatie; die hier naspelen
 * zou een tweede lezing van dezelfde norm opleveren.
 *
 * Leeg of afwezig = geen gegenereerde windlast met omschrijving; het
 * rapport zwijgt dan.
 */
wind_toelichting?: string, 
/**
 * De plaattoets (wandschijven, belast in het vlak) per plaat, zoals
 * `plaat_check::check_all_plates` hem leverde — getoetst of geweigerd met
 * reden. Hieruit komt het hoofdstuk [`crate::plaathoofdstuk`].
 *
 * Waarom (issue #25): het live rapport had een sectie "Toetsing platen",
 * het papier niet. Een wand die op het scherm "niet getoetst: trek
 * loodrecht op de vezel" draagt, hoort dat ook op het ingediende stuk te
 * doen.
 *
 * `#[serde(default)]` om dezelfde reden als bij de andere kernen: een
 * aanroep zonder platen blijft geldig, en het hoofdstuk blijft dan weg.
 */
plate_results?: Array<PlateCheckResult>, 
/**
 * Oorspronkelijke plaatinvoer van dezelfde toetsronde, met alle
 * combinaties en elementspanningen. Zonder invoer blijven bestaande
 * resultaataanroepen geldig; het hoofdstuk meldt dan de ontbrekende invoer.
 */
plate_inputs?: Array<PlateCheckInput>, 
/**
 * De platen die de app NIET naar de kern stuurde, met de reden (geen
 * materiaal, geen rekenresultaat, …). Het live rapport noemt ze in het
 * overzicht; zonder dit veld zou de PDF er stil over zijn.
 */
plate_skipped?: Array<RapportPlaatOvergeslagen>, };
