// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "./CheckStatus";
import type { Deelstap } from "./Deelstap";
import type { ForceStateSnapshot } from "./ForceStateSnapshot";
import type { NamedValue } from "./NamedValue";
import type { UnityCheck } from "./UnityCheck";

export type ResistanceCalc = { id: string, title: string, article: string, force_state: ForceStateSnapshot, formula_latex: string, variables: Array<NamedValue>, 
/**
 * De afleiding die aan deze toets voorafgaat, in de volgorde waarin het
 * rapport haar toont. Leeg voor toetsen die geen voorafgaande keten
 * hebben — dan verandert er niets aan de weergave. De betontoetsen vullen
 * hem; de staal- en houttoetsen zijn één formule en laten hem leeg.
 */
deelstappen: Array<Deelstap>, value: number, unit: string, uc: UnityCheck | null, status: CheckStatus, notes: Array<string>, };
