// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wat er aan één staafeind zit, voor zover de stabiliteitstoetsen ervan
 * afhangen.
 *
 * De kiptoets (NB.NB.4.3) en de terugval van de kniklengte nemen een
 * staafeind als GAFFEL: torsie verhinderd, zijdelings gesteund. Dat is de
 * aanname van de hele keten, en zij is verdedigbaar bij een oplegging of een
 * aansluiting op een andere staaf. Twee soorten staafeinden zijn het NIET, en
 * tot september 2026 werden ze wél zo behandeld (basisaudit, kipgedrag):
 *
 *  * een **vrij** eind — geen oplegging en geen aansluitende staaf: een
 *    uitkraging of een vrijstaande kolom. Een IPE 300 van 3 m als uitkraging
 *    kreeg L_st = 3000 mm (UC_kip 0,406) waar tabel NB.NB.1 geval 5 de
 *    vervangende ligger van 2·L = 6000 mm voorschrijft (UC_kip 0,720);
 *  * een **doorlopend** eind — de staaf loopt zonder oplegging in het
 *    verlengde door in een staaf met een ándere doorsnede of een ander
 *    materiaal. Delen met dezelfde doorsnede voegt de invoerbouwer al samen
 *    tot één staaf; bij een wisselende doorsnede kan dat niet, en dan kan de
 *    kern de kipvelden en de kniklengte niet per deel bepalen. Hij weigert
 *    dan met reden in plaats van het eind stil als gaffel te nemen.
 */
export type Staafeind = "Gaffel" | "Vrij" | "Doorlopend";
