// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hoe een staaf in het vlak van het model staat. Rekent nergens mee: het
 * bepaalt alleen hoe een afleiding de zijden van de doorsnede benoemt.
 *
 * WAAROM. De krachten komen in de referentierichting van de staaf binnen
 * (zie [`InternalForces`]). Bij een liggende staaf zijn "boven" en "onder"
 * daarmee wereldtermen. Bij een staande staaf zijn ze dat niet: gerekend van
 * voet naar kop ligt de lokale onderzijde — waar een positief moment trek
 * geeft, waar de onderwapening en de onderflens zitten — aan de RECHTERzijde
 * van de staaf zoals hij in het model staat, en de bovenzijde links. Een
 * afleiding die dan "onderwapening" of "BOVENflens gedrukt" schrijft, hoort
 * erbij te zeggen welke kant dat is.
 *
 * De grens van 75° is die van `isOverwegendVerticaal` in de frontend, die op
 * zijn beurt dezelfde is als die van het staaftype; er is geen derde regel.
 *
 * Ontbreekt het veld in een invoer, dan geldt [`Staafstand::Liggend`]: dat is
 * het gedrag van vóór dit type, en de benaming boven/onder is dan letterlijk.
 */
export type Staafstand = "Liggend" | "Staand";
