// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerloopMaten } from "./VerloopMaten";

/**
 * De doorsnede waarmee één stabiliteitstoets is gerekend, en waarom die.
 */
export type StabiliteitsDoorsnede = { toets_id: string, 
/**
 * Het veld waarvoor deze doorsnede geldt (bij kip: het kipveld), als
 * tekst voor het rapport; leeg als het de hele staaf is.
 */
veld: string, x_mm: number, maten: VerloopMaten, area_mm2: number, w_y_mm3: number, reden: string, };
