// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "./CheckStatus";
import type { Deelstap } from "./Deelstap";
import type { ForceStateSnapshot } from "./ForceStateSnapshot";
import type { NamedValue } from "./NamedValue";
import type { UnityCheck } from "./UnityCheck";

/**
 * Mirror of ResistanceCalc but for stability checks.
 */
export type StabilityCalc = { id: string, title: string, article: string, force_state: ForceStateSnapshot, formula_latex: string, variables: Array<NamedValue>, intermediate_values: Array<NamedValue>, 
/**
 * De afleiding die aan deze toets voorafgaat, in de volgorde waarin het
 * rapport haar toont. Leeg voor toetsen die geen voorafgaande keten
 * hebben; dan verandert er niets aan de weergave.
 *
 * Waar deze lijst gevuld is, herhaalt `intermediate_values` haar
 * uitkomsten: die blijft bestaan omdat toetsen en afnemers erop zoeken,
 * maar het rapport hoort dan de deelstappen te tonen en de losse
 * tussenwaardenregel weg te laten.
 */
deelstappen: Array<Deelstap>, value: number, unit: string, uc: UnityCheck | null, status: CheckStatus, notes: Array<string>, };
