// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SteelGrade = { name: string, fy_mpa: number, fu_mpa: number, gamma_m0: number, gamma_m1: number, gamma_m2: number, };
