// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BucklingCurves } from "./BucklingCurves";
import type { ProfileGeometry } from "./ProfileGeometry";
import type { ProfileKind } from "./ProfileKind";
import type { SectionProperties } from "./SectionProperties";

export type SteelProfile = { name: string, kind: ProfileKind, geometry: ProfileGeometry, properties: SectionProperties, buckling_curves: BucklingCurves, };
