// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrossSectionClass } from "./CrossSectionClass";
import type { ToetsUc } from "./ToetsUc";
import type { VerloopMaten } from "./VerloopMaten";

/**
 * Eén toetsdoorsnede: waar hij ligt, welke maten daar gelden en wat elke
 * doorsnedetoets daar geeft (de hoogste unity check over de combinaties op
 * dat rekenpunt).
 */
export type Toetsdoorsnede = { 
/**
 * Positie langs de staaf (mm vanaf x = 0), het REKENPUNT dat het dichtst
 * bij de gevraagde plaats ligt — niet per se precies k·L/5.
 */
x_mm: number, 
/**
 * Relatieve positie t = x/L.
 */
t: number, maten: VerloopMaten, 
/**
 * Doorsnede-oppervlak op deze plek (mm²).
 */
area_mm2: number, 
/**
 * Weerstandsmoment om y op deze plek (mm³): W_pl,y bij staal, W_el,y bij hout.
 */
w_y_mm3: number, 
/**
 * Doorsnedeklasse op deze plek (staal): de ongunstigste over de
 * combinaties op dit rekenpunt. `None` bij hout.
 */
klasse?: CrossSectionClass, toetsen: Array<ToetsUc>, };
