// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De unity check van één doorsnedetoets op één toetsdoorsnede. `uc` is
 * `None` als de toets daar niet is gerekend (geweigerd, of niet van
 * toepassing op die plek) — dat is geen 0,00.
 */
export type ToetsUc = { 
/**
 * Het toets-id zoals het in `checks` staat ("6.2.5_bending_y", "6.1.6_bending").
 */
id: string, uc?: number, };
