// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De hoofdmaten van één doorsnede langs een verlopende staaf, in mm.
 * `tw_mm` en `tf_mm` alleen bij een gelast I-profiel (staal).
 */
export type VerloopMaten = { h_mm: number, b_mm: number, tw_mm?: number, tf_mm?: number, };
