import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { ChevronDown, ChevronUp, Plus, Trash2, X } from 'lucide-react';
import type { WorkCalendar, Holiday, WorkTimeBands } from '@/types/calendar';
import { accentChipClass, CalendarGeneratorFields } from './CalendarGeneratorFields';
import { WorkTimeEditor } from './WorkTimeEditor';
import { DateTextInput } from '@/components/common/DateTextInput';
import { useAppStore } from '@/state/appStore';
import { isHourCalendar, deriveHoursPerDay, workDaysFromBands } from '@/services/subdayIo';
import { generateId } from '@/utils/id';
import { loadWorkTimePresets, saveWorkTimePresets } from '@/utils/settingsStore';
import {
  CALENDAR_PRESETS, SHIFT_PRESET_LABEL, shiftPresetPatch, patchFromPreset, presetFromCalendar,
  seedScalarWorkTime, presetDescription, isAutoGeneratedDescription,
  type WorkTimePreset, type ShiftPresetKey,
} from '@/utils/shiftPresets';
import {
  materializeHolidays, computeGenerateSpan, DEFAULT_GEN_PARAMS, type HolidayGenParams,
} from '@/engine/calendar/generateCalendarHolidays';
import { orderedWeekDays } from '@/utils/weekDays';
import {
  calendarScalarBreakIssue, legacySimpleBreakDurationMinutes, scalarBreakIssue, simpleBreakPatch,
} from '@/utils/effectiveWorkTime';
import { holidayIssue } from '@/utils/holidayRange';

function minutesToTime(value: number): string {
  const totalMinutes = Math.round(value);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}`;
}

function timeToMinutes(value: string): number | undefined {
  const match = /^(\d{2}):(\d{2})$/.exec(value);
  if (!match) return undefined;
  const hours = Number(match[1]);
  const minutes = Number(match[2]);
  return hours >= 0 && hours <= 24 && minutes >= 0 && minutes < 60 && (hours < 24 || minutes === 0)
    ? hours * 60 + minutes
    : undefined;
}

const TIME_STEP_MINUTES = 15;

/** Rode rand voor een ongeldige feestdagdatum; `DateTextInput` legt `style` op de omrande groep. */
const INVALID_DATE_STYLE = { borderColor: 'var(--error)' } as const;

type ScalarTimeField = 'workStart' | 'workEnd' | 'breakStart' | 'breakDuration';
type ScalarTimeIssue = 'invalidWorkStart' | 'invalidWorkEnd' | 'invalidWorkTimeOrder' | 'invalidStart' | 'invalidDuration' | 'outsideWorkingDay' | 'consumesWorkingDay';

function StepButtons({ onStep, increaseLabel, decreaseLabel, dataAttribute }: {
  onStep: (delta: number) => void;
  increaseLabel: string;
  decreaseLabel: string;
  dataAttribute: string;
}) {
  return <span className="flex w-5 shrink-0 flex-col gap-0.5">
    <button type="button" className="flex flex-1 items-center justify-center rounded border border-[var(--theme-control-border)] text-text-secondary hover:bg-surface-hover focus:outline-none focus:ring-2 focus:ring-accent" aria-label={increaseLabel} title={increaseLabel} onClick={() => onStep(TIME_STEP_MINUTES)} data-ops-scalar-time-step={`${dataAttribute}-up`}>
      <ChevronUp size={11} aria-hidden="true" />
    </button>
    <button type="button" className="flex flex-1 items-center justify-center rounded border border-[var(--theme-control-border)] text-text-secondary hover:bg-surface-hover focus:outline-none focus:ring-2 focus:ring-accent" aria-label={decreaseLabel} title={decreaseLabel} onClick={() => onStep(-TIME_STEP_MINUTES)} data-ops-scalar-time-step={`${dataAttribute}-down`}>
      <ChevronDown size={11} aria-hidden="true" />
    </button>
  </span>;
}

/**
 * Een bewust gewoon tekstveld voor de drie scalar-tijden. Native time/number-invoer verschilt per
 * browser (klokje, AM/PM en spinners); dit veld houdt OPS overal bij 24-uurs HH:MM. De aanroeper
 * bewaart tusseninvoer lokaal en schrijft uitsluitend gevalideerde minuten naar het kalenderdraft.
 */
function ScalarTimeInput({
  id,
  value,
  onTextChange,
  onCommit,
  onStep,
  increaseLabel,
  decreaseLabel,
  className,
  dataAttribute,
}: {
  id: string;
  value: string;
  onTextChange: (value: string) => void;
  onCommit: () => void;
  onStep: (delta: number) => void;
  increaseLabel: string;
  decreaseLabel: string;
  className: string;
  dataAttribute: string;
}) {
  return (
    <div className="flex min-w-0 items-stretch gap-1">
      <input
        id={id}
        type="text"
        inputMode="numeric"
        placeholder="HH:MM"
        value={value}
        onChange={event => onTextChange(event.target.value)}
        onBlur={onCommit}
        onKeyDown={event => {
          if (event.key === 'Enter') {
            event.preventDefault();
            onCommit();
          } else if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
            event.preventDefault();
            onStep(event.key === 'ArrowUp' ? TIME_STEP_MINUTES : -TIME_STEP_MINUTES);
          }
        }}
        className={className + ' min-w-0 flex-1'}
        data-ops-scalar-time={dataAttribute}
        data-ops-work-start={dataAttribute === 'work-start' ? true : undefined}
        data-ops-work-end={dataAttribute === 'work-end' ? true : undefined}
        data-ops-simple-break-start={dataAttribute === 'break-start' ? true : undefined}
      />
      <StepButtons onStep={onStep} increaseLabel={increaseLabel} decreaseLabel={decreaseLabel} dataAttribute={dataAttribute} />
    </div>
  );
}

function minutesFromText(value: string): number | undefined {
  return /^\d+$/.test(value) && Number(value) <= 24 * 60 ? Number(value) : undefined;
}

/**
 * Presentational kalenderformulier (naam, werkdagen, uren, feestdagen) — kent geen store.
 * Hergebruikt door `CalendarDialog` (projectkalender) én `ResourceCalendarDialog`;
 * de aanroeper beslist wat er met `onChange`-patches gebeurt en wanneer
 * er gecommit wordt (Apply-knop leeft in de aanroeper, niet hier).
 *
 * `projectYearSpan`: optionele projectperiode (in jaren) van de aanroeper.
 * Stuurt de default generatie-spanne én de hergeneratie-hint wanneer de kalender al
 * `generation`-metadata draagt die de projectperiode niet meer dekt.
 */
export function CalendarForm({
  draft,
  onChange,
  onScalarTimeValidityChange,
  projectYearSpan,
}: {
  draft: WorkCalendar;
  onChange: (patch: Partial<WorkCalendar>) => void;
  /** De aanroeper bezit Apply en moet lokaal ongeldige, nog niet-gecommitte HH:MM-invoer blokkeren. */
  onScalarTimeValidityChange?: (invalid: boolean) => void;
  projectYearSpan?: { from: number; to: number };
}) {
  const { t: tMenu, i18n } = useTranslation('menu');
  const { t: tCommon } = useTranslation('common');
  const enableHourPlanning = useAppStore(s => s.ui.enableHourPlanning);
  const weekStartDay = useAppStore(s => s.ui.weekStartDay);

  const [showGenerator, setShowGenerator] = useState(false);
  // Werktijden-UI: eigen presets (app-niveau localStorage), banden-editor achter een knop,
  // en een inline naam-invoer voor "Bewaar als preset…".
  const [ownPresets, setOwnPresets] = useState<WorkTimePreset[]>([]);
  // In uur-modus staat de banden-editor standaard OPEN (elke uur-preset toont meteen bewerkbare
  // tijden); deze vlag laat de gebruiker hem inklappen. Voor een dag-kalender is er nog geen
  // `workTime`, dus opent de knop de editor (seed uit scalar) i.p.v. te collapsen.
  const [bandsCollapsed, setBandsCollapsed] = useState(false);
  const [savingPreset, setSavingPreset] = useState(false);
  const [presetName, setPresetName] = useState('');
  const hourMode = isHourCalendar(draft);
  const scalarBreakError = calendarScalarBreakIssue(draft);
  // Oude scalar-kalenders hebben nog geen velden, maar hun zichtbare waarden moeten het bestaande
  // gedrag verklaren: 07:00–16:00 / 8 uur toont daarom de afgeleide 12:00 / 60 min, terwijl
  // 08:00–16:00 / 8 uur terecht 0 minuten toont.
  const inferredSimpleBreakDuration = legacySimpleBreakDurationMinutes(draft);
  const [workStartText, setWorkStartText] = useState(() => minutesToTime(draft.workStartHour * 60));
  const [workEndText, setWorkEndText] = useState(() => minutesToTime(draft.workEndHour * 60));
  const [simpleBreakStartText, setSimpleBreakStartText] = useState(() =>
    minutesToTime(draft.simpleBreakStartMinute ?? 12 * 60));
  const [simpleBreakDurationText, setSimpleBreakDurationText] = useState(() =>
    String(draft.simpleBreakDurationMinutes ?? inferredSimpleBreakDuration));
  const [scalarTimeIssues, setScalarTimeIssues] = useState<Partial<Record<ScalarTimeField, ScalarTimeIssue>>>({});
  const netHoursFormatter = useMemo(
    () => new Intl.NumberFormat(i18n.language, { minimumFractionDigits: 2, maximumFractionDigits: 2 }),
    [i18n.language],
  );

  useEffect(() => {
    setWorkStartText(minutesToTime(draft.workStartHour * 60));
    setScalarTimeIssues(issues => {
      if (!issues.workStart) return issues;
      const next = { ...issues };
      delete next.workStart;
      return next;
    });
  }, [draft.workStartHour]);

  useEffect(() => {
    setWorkEndText(minutesToTime(draft.workEndHour * 60));
    setScalarTimeIssues(issues => {
      if (!issues.workEnd) return issues;
      const next = { ...issues };
      delete next.workEnd;
      return next;
    });
  }, [draft.workEndHour]);

  useEffect(() => {
    setSimpleBreakStartText(minutesToTime(draft.simpleBreakStartMinute ?? 12 * 60));
    setScalarTimeIssues(issues => {
      if (!issues.breakStart) return issues;
      const next = { ...issues };
      delete next.breakStart;
      return next;
    });
  }, [draft.simpleBreakStartMinute]);

  useEffect(() => {
    setSimpleBreakDurationText(String(draft.simpleBreakDurationMinutes ?? inferredSimpleBreakDuration));
    setScalarTimeIssues(issues => {
      if (!issues.breakDuration) return issues;
      const next = { ...issues };
      delete next.breakDuration;
      return next;
    });
  }, [draft.simpleBreakDurationMinutes, inferredSimpleBreakDuration]);

  useEffect(() => {
    onScalarTimeValidityChange?.(Object.keys(scalarTimeIssues).length > 0);
  }, [onScalarTimeValidityChange, scalarTimeIssues]);

  useEffect(() => { void loadWorkTimePresets().then(setOwnPresets); }, []);

  // Preset toepassen ⇒ workTime + shift + scalar-fallback in één patch (buffer-model). Optionele
  // `description`-override (zie `applyBuiltinPreset` hieronder) — alleen meegegeven wanneer de
  // aanroeper al bepaald heeft dat het veilig is om 'm te overschrijven.
  const applyPreset = (patch: ReturnType<typeof shiftPresetPatch>, description?: string) => {
    onChange({
      workTime: patch.workTime,
      shift: patch.shift,
      workDays: patch.workDays,
      workStartHour: patch.workStartHour,
      workEndHour: patch.workEndHour,
      hoursPerDay: patch.hoursPerDay,
      simpleBreakStartMinute: patch.simpleBreakStartMinute,
      simpleBreakDurationMinutes: patch.simpleBreakDurationMinutes,
      ...(description !== undefined ? { description } : null),
    });
    // Elke uur-preset ⇒ editor meteen open/zichtbaar (uitgeklapt); dag-preset heeft geen editor.
    setBandsCollapsed(false);
  };

  // Eén van de vijf INGEBOUWDE presets (CALENDAR_PRESETS) — in tegenstelling tot een eigen preset
  // (`patchFromPreset`) kennen we hier de preset-`key` en dus een accurate
  // omschrijving. `description` wordt ALLEEN meegepatcht
  // als de HUIDIGE tekst nog aantoonbaar machine-gegenereerd is: een
  // handmatig ingevulde omschrijving ("Vaste onderaannemerskalender, zie contract §4") mag nooit
  // stilzwijgend verdwijnen achter een preset-klik.
  const applyBuiltinPreset = (key: ShiftPresetKey) => {
    applyPreset(
      shiftPresetPatch(key),
      isAutoGeneratedDescription(draft.description) ? presetDescription(key) : undefined,
    );
  };

  const persistOwnPresets = (list: WorkTimePreset[]) => {
    setOwnPresets(list);
    void saveWorkTimePresets(list);
  };
  const confirmSavePreset = () => {
    const name = presetName.trim();
    if (!name) return;
    persistOwnPresets([...ownPresets, presetFromCalendar(generateId('wtp'), name, draft)]);
    setPresetName('');
    setSavingPreset(false);
  };
  const deleteOwnPreset = (id: string) => persistOwnPresets(ownPresets.filter(p => p.id !== id));

  // Banden-editor openen ⇒ ontbreekt workTime, seed dan uit de scalar zodat een dag-kalender via de
  // editor een uur-kalender kan worden. KRITISCH: de band-som moet EXACT `hoursPerDay ×
  // 60` zijn — de default 07:00-16:00/8u is 9 klokuren, 8 netto; `seedScalarWorkTime` materialiseert dat
  // verschil als pauze-gat rond het middaguur, zodat `deriveHoursPerDay` de oorspronkelijke 8 teruggeeft
  // en ongewijzigd openen+toepassen `hoursPerDay` niet corrumpeert.
  const toggleBandEditor = () => {
    if (!draft.workTime) {
      // Dag-kalender ⇒ seed uit de scalar (wordt uur-kalender) en toon de editor uitgeklapt.
      applyBands(seedScalarWorkTime(draft.workDays, draft.workStartHour, draft.workEndHour, draft.hoursPerDay));
      setBandsCollapsed(false);
      return;
    }
    setBandsCollapsed(c => !c); // uur-kalender ⇒ in-/uitklappen.
  };
  const applyBands = (bands: WorkTimeBands) => {
    onChange({
      workTime: bands,
      hoursPerDay: deriveHoursPerDay(bands, draft.hoursPerDay),
      workDays: workDaysFromBands(bands),
      // Handmatige weekbanden zijn absoluut leidend; laat geen oud scalar-pauzepatroon als
      // tweede bron naast deze expliciete keuze bestaan.
      simpleBreakStartMinute: undefined,
      simpleBreakDurationMinutes: undefined,
    });
  };
  const [genParams, setGenParams] = useState<HolidayGenParams>(() =>
    draft.generation
      ? {
          country: draft.generation.ruleSetId,
          region: draft.generation.region,
          bouwvak: draft.generation.breakChoice ?? 'geen',
        }
      : DEFAULT_GEN_PARAMS,
  );

  const defaultSpan = projectYearSpan
    ?? (draft.generation
      ? { from: draft.generation.generatedFromYear, to: draft.generation.generatedToYear }
      : computeGenerateSpan(new Date().toISOString().slice(0, 10), undefined));

  const needsRegen = !!draft.generation && !!projectYearSpan
    && (projectYearSpan.from < draft.generation.generatedFromYear
      || projectYearSpan.to > draft.generation.generatedToYear);

  const applyGenerator = () => {
    const { holidays, generation } = materializeHolidays(genParams, defaultSpan.from, defaultSpan.to);
    onChange({ holidays, generation });
    setShowGenerator(false);
  };

  const regenerate = () => {
    if (!draft.generation || !projectYearSpan) return;
    const params: HolidayGenParams = {
      country: draft.generation.ruleSetId,
      region: draft.generation.region,
      bouwvak: draft.generation.breakChoice ?? 'geen',
    };
    const { holidays, generation } = materializeHolidays(params, projectYearSpan.from, projectYearSpan.to);
    onChange({ holidays, generation });
  };

  const toggleWorkDay = (day: number) => {
    const has = draft.workDays.includes(day);
    const workDays = has
      ? draft.workDays.filter(x => x !== day)
      : [...draft.workDays, day].sort((a, b) => a - b);
    onChange({ workDays });
  };

  // Het eenvoudige patroon is geen tweede engineformule: de netto uren worden alleen als
  // gebruikersfeedback uit hetzelfde effectieve-worktime-model afgeleid. Expliciete weekbanden
  // blijven volledig buiten dit pad en dus absoluut leidend. Een oude scalar heeft een impliciete
  // pauze om haar bestaande netto-uren te verklaren; zodra de gebruiker één van de vier
  // scalarbedieningen wijzigt, wordt die veilig expliciet. Eén definitie met MCP: `simpleBreakPatch`.
  const patchSimpleBreak = (patch: Partial<WorkCalendar>) => {
    onChange(simpleBreakPatch(draft, patch));
  };

  const setScalarTimeIssue = (field: ScalarTimeField, issue?: ScalarTimeIssue) => {
    setScalarTimeIssues(issues => {
      if (issue === undefined && issues[field] === undefined) return issues;
      const next = { ...issues };
      if (issue === undefined) delete next[field];
      else next[field] = issue;
      return next;
    });
  };

  const updateScalarTimeText = (
    field: ScalarTimeField,
    setText: (value: string) => void,
    value: string,
  ) => {
    setText(value);
    // Tusseninvoer blijft in het DOM en raakt het model nooit. Alleen een volledig gevormde
    // HH:MM wist een eerdere tekstfout; inhoudelijke grenzen worden bij blur/Enter beoordeeld.
    if (timeToMinutes(value) !== undefined) setScalarTimeIssue(field);
  };

  const scalarTimesAreValid = (patch: Partial<WorkCalendar>) => {
    const next = { ...draft, ...patch };
    const start = Math.round(next.workStartHour * 60);
    const end = Math.round(next.workEndHour * 60);
    if (start < 0 || start >= 24 * 60 || end <= 0 || end > 24 * 60 || start >= end) return false;
    // Ook een legacy-scalar zonder zichtbare pauzevelden draagt zijn bestaande netto-tijd als
    // impliciete middagpauze. Dezelfde controle beschermt dus een nieuw Start/Einde tegen het
    // ongemerkt buiten de nieuwe werkdag drukken van die pauze.
    const breakStart = next.simpleBreakStartMinute ?? 12 * 60;
    const breakDuration = next.simpleBreakDurationMinutes ?? inferredSimpleBreakDuration;
    return breakStart >= start && breakStart < end
      && scalarBreakIssue(start, end, breakStart, breakDuration) === undefined;
  };

  // Pas bij blur of Enter wordt een complete, inhoudelijk geldige HH:MM-waarde naar het model
  // geschreven. Daarmee blijft ook omgekeerde of buiten-de-dag liggende tusseninvoer veilig lokaal.
  const commitWorkStart = () => {
    const minute = timeToMinutes(workStartText);
    if (minute === undefined) {
      setScalarTimeIssue('workStart', 'invalidWorkStart');
      return;
    }
    if (!scalarTimesAreValid({ workStartHour: minute / 60 })) {
      setScalarTimeIssue('workStart', 'invalidWorkTimeOrder');
      return;
    }
    setScalarTimeIssue('workStart');
    patchSimpleBreak({ workStartHour: minute / 60 });
  };

  const commitWorkEnd = () => {
    const minute = timeToMinutes(workEndText);
    if (minute === undefined) {
      setScalarTimeIssue('workEnd', 'invalidWorkEnd');
      return;
    }
    if (!scalarTimesAreValid({ workEndHour: minute / 60 })) {
      setScalarTimeIssue('workEnd', 'invalidWorkTimeOrder');
      return;
    }
    setScalarTimeIssue('workEnd');
    patchSimpleBreak({ workEndHour: minute / 60 });
  };

  const commitSimpleBreakStart = () => {
    const minute = timeToMinutes(simpleBreakStartText);
    if (minute === undefined || !scalarTimesAreValid({ simpleBreakStartMinute: minute })) {
      setScalarTimeIssue('breakStart', 'invalidStart');
      return;
    }
    setScalarTimeIssue('breakStart');
    patchSimpleBreak({ simpleBreakStartMinute: minute });
  };

  const simpleBreakDurationIssue = (text: string): ScalarTimeIssue | undefined => {
    const duration = minutesFromText(text);
    if (duration === undefined) return 'invalidDuration';
    return scalarBreakIssue(
      draft.workStartHour * 60,
      draft.workEndHour * 60,
      draft.simpleBreakStartMinute ?? 12 * 60,
      duration,
    );
  };

  const updateSimpleBreakDurationText = (value: string) => {
    setSimpleBreakDurationText(value);
    // Een tekstwijziging blijft lokaal, maar Apply moet wel onmiddellijk weten dat bijvoorbeeld
    // een onvolledige, te grote of buiten-de-dag liggende pauze niet geldig is.
    setScalarTimeIssue('breakDuration', simpleBreakDurationIssue(value));
  };

  const commitSimpleBreakDuration = () => {
    const duration = minutesFromText(simpleBreakDurationText);
    if (duration === undefined) {
      setScalarTimeIssue('breakDuration', 'invalidDuration');
      return;
    }
    const issue = simpleBreakDurationIssue(simpleBreakDurationText);
    if (issue) {
      setScalarTimeIssue('breakDuration', issue);
      return;
    }
    setScalarTimeIssue('breakDuration');
    patchSimpleBreak({ simpleBreakStartMinute: draft.simpleBreakStartMinute ?? 12 * 60, simpleBreakDurationMinutes: duration });
  };

  const stepSimpleBreakDuration = (delta: number) => {
    const current = minutesFromText(simpleBreakDurationText);
    if (current === undefined) {
      setScalarTimeIssue('breakDuration', 'invalidDuration');
      return;
    }
    const nextDuration = current + delta;
    if (nextDuration < 0 || nextDuration > 24 * 60) return;
    const issue = scalarBreakIssue(draft.workStartHour * 60, draft.workEndHour * 60, draft.simpleBreakStartMinute ?? 12 * 60, nextDuration);
    if (issue) {
      setScalarTimeIssue('breakDuration', issue);
      return;
    }
    setSimpleBreakDurationText(String(nextDuration));
    setScalarTimeIssue('breakDuration');
    patchSimpleBreak({ simpleBreakStartMinute: draft.simpleBreakStartMinute ?? 12 * 60, simpleBreakDurationMinutes: nextDuration });
  };

  const stepScalarTime = (
    field: ScalarTimeField,
    text: string,
    setText: (value: string) => void,
    delta: number,
  ) => {
    const current = timeToMinutes(text);
    if (current === undefined) {
      setScalarTimeIssue(field, field === 'workStart' ? 'invalidWorkStart' : field === 'workEnd' ? 'invalidWorkEnd' : 'invalidStart');
      return;
    }
    const nextMinute = current + delta;
    // Start en pauze eindigen uiterlijk op 23:45; einde accepteert expliciet 24:00. Er is nooit
    // een wrap naar een volgende/vorige dag, ook niet wanneer de gebruiker een pijl ingedrukt houdt.
    const inRange = field === 'workEnd'
      ? nextMinute > 0 && nextMinute <= 24 * 60
      : nextMinute >= 0 && nextMinute < 24 * 60;
    if (!inRange) return;
    const patch = field === 'workStart'
      ? { workStartHour: nextMinute / 60 }
      : field === 'workEnd'
        ? { workEndHour: nextMinute / 60 }
        : { simpleBreakStartMinute: nextMinute };
    if (!scalarTimesAreValid(patch)) {
      setScalarTimeIssue(field, field === 'breakStart' ? 'invalidStart' : 'invalidWorkTimeOrder');
      return;
    }
    setText(minutesToTime(nextMinute));
    setScalarTimeIssue(field);
    patchSimpleBreak(patch);
  };

  // Presets: "24/7" = workDays [1..7]. Dit is uitsluitend de ene-doorlopende-kalender-preset, geen
  // dag/nacht-PLOEGEN. "Ma-vr" ernaast herstelt symmetrisch de standaard.
  const applyContinuousPreset = () => {
    onChange({
      workDays: [1, 2, 3, 4, 5, 6, 7], workStartHour: 0, workEndHour: 24, hoursPerDay: 24,
      simpleBreakStartMinute: undefined, simpleBreakDurationMinutes: undefined,
    });
  };
  const applyWeekdaysPreset = () => {
    onChange({
      workDays: [1, 2, 3, 4, 5], workStartHour: 7, workEndHour: 16, hoursPerDay: 8,
      simpleBreakStartMinute: undefined, simpleBreakDurationMinutes: undefined,
    });
  };

  const updateHoliday = (index: number, patch: Partial<Holiday>) => {
    const holidays = draft.holidays.map((h, i) => (i === index ? { ...h, ...patch } : h));
    onChange({ holidays });
  };

  const addHoliday = () => {
    const today = new Date().toISOString().slice(0, 10);
    onChange({ holidays: [...draft.holidays, { name: '', startDate: today, endDate: '' }] });
  };

  const removeHoliday = (index: number) => {
    onChange({ holidays: draft.holidays.filter((_, i) => i !== index) });
  };

  const inputCls =
    'px-2 py-1.5 bg-surface border-[1.5px] border-[var(--theme-control-border)] rounded-[8px] text-text-primary focus:outline-none focus:border-accent focus:shadow-[0_0_0_3px_rgba(217,119,6,0.2)] transition-[border-color,box-shadow]';

  return (
    <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4 text-small leading-4">
      {/* Name */}
      <div className="flex flex-col gap-1">
        <label className="text-text-secondary font-medium">
          {tMenu('ribbon.calendarDialog.name')}
        </label>
        <input
          value={draft.name}
          onChange={e => onChange({ name: e.target.value })}
          className={inputCls}
          autoFocus
        />
      </div>

      {/* Work days */}
      <div className="flex flex-col gap-1">
        <div className="flex items-center justify-between">
          <label className="text-text-secondary font-medium">
            {tMenu('ribbon.calendarDialog.workDays')}
          </label>
          {/* Presets: "Continu (24/7)" zet workDays [1..7] + 0-24u ineens;
              "Ma-vr" herstelt symmetrisch de standaard ma-vr/07-16. */}
          <div className="flex gap-1.5">
            <button
              type="button"
              onClick={applyWeekdaysPreset}
              className="btn btn--sm btn--secondary"
            >
              {tCommon('calendar.preset.weekdays')}
            </button>
            <button
              type="button"
              onClick={applyContinuousPreset}
              className="btn btn--sm btn--secondary"
            >
              {tCommon('calendar.preset.continuous')}
            </button>
          </div>
        </div>
        <div className="flex gap-1.5">
          {orderedWeekDays(weekStartDay).map(day => {
            const active = draft.workDays.includes(day);
            return (
              <button
                key={day}
                onClick={() => toggleWorkDay(day)}
                className={accentChipClass(active)}
              >
                {tMenu(`ribbon.calendarDialog.days.${day}`)}
              </button>
            );
          })}
        </div>
      </div>

      {/* Netto-uren zijn in elke kalenderstand uitsluitend een afleiding. De scalarbediening blijft
          verborgen zodra weekbanden autoritatief zijn, maar de readout zelf wisselt nooit van vorm
          of bewerkbaarheid door de Urenplanning-toggle. */}
      <div className="grid grid-cols-3 gap-3">
        {!(enableHourPlanning && hourMode) && (
          <>
          <div className="flex flex-col gap-1">
            <label className="text-text-secondary font-medium" htmlFor="ops-work-start">
              {tMenu('ribbon.calendarDialog.startHour')}
            </label>
            <ScalarTimeInput
              id="ops-work-start"
              value={workStartText}
              onTextChange={value => updateScalarTimeText('workStart', setWorkStartText, value)}
              onCommit={commitWorkStart}
              onStep={delta => stepScalarTime('workStart', workStartText, setWorkStartText, delta)}
              increaseLabel={tCommon('calendar.simpleBreak.increaseTime')}
              decreaseLabel={tCommon('calendar.simpleBreak.decreaseTime')}
              className={inputCls}
              dataAttribute="work-start"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-text-secondary font-medium" htmlFor="ops-work-end">
              {tMenu('ribbon.calendarDialog.endHour')}
            </label>
            <ScalarTimeInput
              id="ops-work-end"
              value={workEndText}
              onTextChange={value => updateScalarTimeText('workEnd', setWorkEndText, value)}
              onCommit={commitWorkEnd}
              onStep={delta => stepScalarTime('workEnd', workEndText, setWorkEndText, delta)}
              increaseLabel={tCommon('calendar.simpleBreak.increaseTime')}
              decreaseLabel={tCommon('calendar.simpleBreak.decreaseTime')}
              className={inputCls}
              dataAttribute="work-end"
            />
          </div>
          </>
        )}
        <div className="flex flex-col gap-1">
          <label className="text-text-secondary font-medium">
            {tMenu('ribbon.calendarDialog.netHoursPerDay')}
          </label>
          <output
            className="py-1.5 font-semibold text-text-primary tabular-nums"
            aria-live="polite"
            data-ops-simple-break-net-hours
          >
            {netHoursFormatter.format(draft.hoursPerDay)} h
          </output>
        </div>
      </div>
      {!(enableHourPlanning && hourMode) && (
        <>
        <div className="grid grid-cols-2 gap-3" data-ops-simple-break>
          <div className="flex flex-col gap-1">
            <label className="text-text-secondary font-medium" htmlFor="ops-simple-break-start">
              {tCommon('calendar.simpleBreak.start')}
            </label>
            <ScalarTimeInput
              id="ops-simple-break-start"
              value={simpleBreakStartText}
              onTextChange={value => updateScalarTimeText('breakStart', setSimpleBreakStartText, value)}
              onCommit={commitSimpleBreakStart}
              onStep={delta => stepScalarTime('breakStart', simpleBreakStartText, setSimpleBreakStartText, delta)}
              increaseLabel={tCommon('calendar.simpleBreak.increaseTime')}
              decreaseLabel={tCommon('calendar.simpleBreak.decreaseTime')}
              className={inputCls}
              dataAttribute="break-start"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-text-secondary font-medium" htmlFor="ops-simple-break-duration">
              {tCommon('calendar.simpleBreak.duration')}
            </label>
            <div className="flex min-w-0 items-stretch gap-1">
              <input id="ops-simple-break-duration" type="text" inputMode="numeric" value={simpleBreakDurationText}
                onChange={event => updateSimpleBreakDurationText(event.target.value)}
                onBlur={commitSimpleBreakDuration}
                onKeyDown={event => {
                  if (event.key === 'Enter') { event.preventDefault(); commitSimpleBreakDuration(); }
                  else if (event.key === 'ArrowUp' || event.key === 'ArrowDown') { event.preventDefault(); stepSimpleBreakDuration(event.key === 'ArrowUp' ? TIME_STEP_MINUTES : -TIME_STEP_MINUTES); }
                }}
                className={inputCls + ' min-w-0 flex-1'} data-ops-simple-break-duration />
              <StepButtons onStep={stepSimpleBreakDuration}
                increaseLabel={tCommon('calendar.simpleBreak.increaseBreakDuration')}
                decreaseLabel={tCommon('calendar.simpleBreak.decreaseBreakDuration')}
                dataAttribute="break-duration" />
            </div>
          </div>
          <p className="col-span-2 !text-body text-text-secondary">
            {tCommon('calendar.simpleBreak.hint')}
          </p>
          {(scalarBreakError || Object.keys(scalarTimeIssues).length > 0) && (
            <p className="col-span-2 !text-body text-red-600" role="alert" data-ops-simple-break-error>
              {scalarTimeIssues.workStart === 'invalidWorkStart'
                ? tCommon('calendar.simpleBreak.invalidWorkStart')
                : scalarTimeIssues.workEnd === 'invalidWorkEnd'
                  ? tCommon('calendar.simpleBreak.invalidWorkEnd')
                  : scalarTimeIssues.workStart === 'invalidWorkTimeOrder' || scalarTimeIssues.workEnd === 'invalidWorkTimeOrder'
                    ? tCommon('calendar.simpleBreak.invalidWorkTimeOrder')
                : scalarTimeIssues.breakStart === 'invalidStart'
                  ? tCommon('calendar.simpleBreak.invalidStart')
                : scalarTimeIssues.breakDuration
                  ? scalarTimeIssues.breakDuration === 'invalidDuration'
                    ? tCommon('calendar.simpleBreak.errors.invalidDuration')
                    : scalarTimeIssues.breakDuration === 'outsideWorkingDay'
                      ? tCommon('calendar.simpleBreak.errors.outsideWorkingDay')
                      : tCommon('calendar.simpleBreak.errors.consumesWorkingDay')
                : scalarBreakError
                  ? tCommon(`calendar.simpleBreak.errors.${scalarBreakError}` as const)
                  : null}
            </p>
          )}
        </div>
        </>
      )}

      {/* Werktijden / ploegen — alleen met Urenplanning aan; anders de scalar-UI. */}
      {enableHourPlanning && (
        <div className="flex flex-col gap-2" data-ops-worktime-section>
          <label className="text-text-secondary font-medium">{tCommon('calendar.worktime.section')}</label>

          {/* Preset-rij: ingebouwde presets + eigen presets (met verwijder-kruisje). */}
          <div className="flex flex-wrap gap-1.5">
            {CALENDAR_PRESETS.map(key => (
              <button key={key} type="button" onClick={() => applyBuiltinPreset(key)}
                className="btn btn--sm btn--secondary" data-ops-preset={key}>
                {tCommon(SHIFT_PRESET_LABEL[key])}
              </button>
            ))}
            {ownPresets.map(p => (
              <span key={p.id} className="inline-flex items-center rounded-[8px] border-[1.5px] border-[var(--theme-control-border)] overflow-hidden"
                data-ops-own-preset={p.id}>
                <button type="button" onClick={() => applyPreset(patchFromPreset(p))}
                  className="px-2.5 py-1.5 text-text-secondary hover:bg-surface-hover">
                  {p.name}
                </button>
                <button type="button" onClick={() => deleteOwnPreset(p.id)}
                  className="px-1.5 py-1.5 text-text-secondary hover:bg-surface-hover hover:text-red-500"
                  title={tCommon('delete')} data-ops-own-preset-del={p.id}>
                  <X size={11} />
                </button>
              </span>
            ))}
          </div>

          <div className="flex flex-wrap gap-2">
            <button type="button" onClick={() => setSavingPreset(v => !v)} className="btn btn--sm btn--secondary"
              title={tCommon('calendar.worktime.saveAsPresetHint')} data-ops-preset-saveas>
              {tCommon('calendar.worktime.saveAsPreset')}
            </button>
            {/* Uur-kalender ⇒ de editor staat standaard open; deze knop klapt hem in/uit. Dag-kalender ⇒
                de knop seedt de banden uit de scalar en toont de editor ("Per weekdag instellen…"). */}
            <button type="button" onClick={toggleBandEditor}
              className="btn btn--sm btn--secondary" data-ops-band-editor-toggle>
              {!draft.workTime
                ? tCommon('calendar.worktime.perWeekday')
                : bandsCollapsed
                  ? tCommon('calendar.worktime.showBands')
                  : tCommon('calendar.worktime.hideBands')}
            </button>
          </div>

          {savingPreset && (
            <div className="flex flex-col gap-1">
              <span className="!text-small text-text-secondary italic" data-ops-preset-saveas-hint>
                {tCommon('calendar.worktime.saveAsPresetHint')}
              </span>
              <div className="flex items-center gap-2">
                <input value={presetName} onChange={e => setPresetName(e.target.value)} autoFocus
                  onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); confirmSavePreset(); } }}
                  placeholder={tCommon('calendar.worktime.presetNamePlaceholder')} className={inputCls + ' flex-1'} />
                <button type="button" onClick={confirmSavePreset} disabled={!presetName.trim()}
                  className="btn btn--sm btn--primary disabled:opacity-40" data-ops-preset-save>{tCommon('save')}</button>
                <button type="button" onClick={() => { setSavingPreset(false); setPresetName(''); }}
                  className="btn btn--sm btn--secondary">{tCommon('cancel')}</button>
              </div>
            </div>
          )}

          {/* Banden-editor: zichtbaar zodra de kalender in uur-modus is (elke uur-preset), tenzij ingeklapt. */}
          {draft.workTime && !bandsCollapsed && (
            <WorkTimeEditor bands={draft.workTime} onChange={applyBands} weekStartDay={weekStartDay} />
          )}
        </div>
      )}

      {/* Feestdagen genereren — regelgebaseerd, óók voor bestaande kalenders. */}
      <div className="flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <button
            onClick={() => setShowGenerator(v => !v)}
            className="btn btn--sm btn--secondary self-start"
          >
            {tCommon('calendar.generate.button')}
          </button>
          {needsRegen && (
            <div className="flex items-center gap-2 !text-body text-text-secondary">
              <span>
                {tCommon('calendar.regen.hint', {
                  from: draft.generation!.generatedFromYear,
                  to: draft.generation!.generatedToYear,
                  year: projectYearSpan!.to,
                })}
              </span>
              <button onClick={regenerate} className="btn btn--sm btn--secondary">
                {tCommon('calendar.regen.button')}
              </button>
            </div>
          )}
        </div>

        {showGenerator && (
          <div className="border border-border rounded-[10px] p-3 flex flex-col gap-3 bg-surface-alt">
            <CalendarGeneratorFields
              value={genParams}
              onChange={patch => setGenParams(p => ({ ...p, ...patch }))}
              fromYear={defaultSpan.from}
              toYear={defaultSpan.to}
              // "Geen feestdagen" hoort er hier óók bij — pariteit met de
              // wizard: leegt de gegenereerde holidays + generation-metadata via
              // materializeHolidays(country:'none'). "Aangepast…" (extraCountryOptions, alleen de
              // wizard) is hier bewust NIET toegevoegd: je bewerkt al een bestaande kalender in de
              // editor zelf, dus een aparte "open de editor"-optie is zinledig in de editor.
            />
            <div className="flex justify-end gap-2">
              <button onClick={() => setShowGenerator(false)} className="btn btn--sm btn--secondary">
                {tCommon('calendar.generate.cancel')}
              </button>
              <button onClick={applyGenerator} className="btn btn--sm btn--primary">
                {tCommon('calendar.generate.apply')}
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Holidays */}
      <div className="flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <label className="text-text-secondary font-medium">
            {tMenu('ribbon.calendarDialog.holidaysSection')}
          </label>
          <button onClick={addHoliday} className="btn btn--sm btn--secondary flex items-center gap-1">
            <Plus size={12} />
            {tMenu('ribbon.calendarDialog.addHoliday')}
          </button>
        </div>

        {draft.holidays.length === 0 ? (
          <span className="text-text-secondary italic">
            {tMenu('ribbon.calendarDialog.noHolidays')}
          </span>
        ) : (
          <div className="flex flex-col gap-2">
            <div className="grid grid-cols-[1fr_auto_auto_auto] gap-2 text-text-secondary font-medium px-1">
              <span>{tMenu('ribbon.calendarDialog.holidayName')}</span>
              <span>{tMenu('ribbon.calendarDialog.from')}</span>
              <span>{tMenu('ribbon.calendarDialog.until')}</span>
              <span />
            </div>
            {draft.holidays.map((h, i) => {
              // Dezelfde regel als MCP (`holidayIssue`): een regel zonder geldige Van of met Tot vóór
              // Van telt in de engine stil als nul dagen. Markeer hem; de aanroeper blokkeert Toepassen.
              const issue = holidayIssue(h);
              const startInvalid = issue === 'invalidStart' || issue === 'endBeforeStart';
              const endInvalid = issue === 'invalidEnd' || issue === 'endBeforeStart';
              return (
                <div key={i} className="flex flex-col gap-1" data-ops-holiday-row={i} data-ops-holiday-invalid={issue}>
                  <div className="grid grid-cols-[1fr_auto_auto_auto] gap-2 items-center">
                    <input
                      value={h.name}
                      onChange={e => updateHoliday(i, { name: e.target.value })}
                      className={inputCls}
                    />
                    <DateTextInput
                      value={h.startDate}
                      onCommit={v => updateHoliday(i, { startDate: v })}
                      className={inputCls}
                      style={startInvalid ? INVALID_DATE_STYLE : undefined}
                      ariaLabel={tMenu('ribbon.calendarDialog.from')}
                    />
                    <DateTextInput
                      value={h.endDate}
                      onCommit={v => updateHoliday(i, { endDate: v })}
                      className={inputCls}
                      style={endInvalid ? INVALID_DATE_STYLE : undefined}
                      ariaLabel={tMenu('ribbon.calendarDialog.until')}
                    />
                    <button
                      onClick={() => removeHoliday(i)}
                      className="p-1.5 hover:bg-surface-hover rounded-[8px] text-text-secondary"
                      title={tCommon('delete')}
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                  {issue && (
                    <p className="!text-body text-red-600" role="alert" data-ops-holiday-error>
                      {tCommon(`calendar.holidayErrors.${issue}` as const)}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
