// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lassoort } from "./Lassoort";
import type { NationaleBijlage } from "../norm/NationaleBijlage";

/**
 * Eén te toetsen naad.
 */
export type LasInput = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, 
/**
 * Vrij te kiezen aanduiding; komt onveranderd in het resultaat terug.
 */
id: string, soort: Lassoort, 
/**
 * Keeldikte `a` van één las (mm).
 */
a_mm: number, 
/**
 * Rekenwaarde van de kracht in de las per eenheidslengte `F_w,Ed`
 * (N/mm) — bij een langslas de schuifstroom `V_z·S/I_y`.
 */
f_w_ed_n_per_mm: number, 
/**
 * Staalsoort van het **zwakste verbonden onderdeel**, zoals "S235".
 * Hieruit volgen `f_u` (EN 1993-1-1 tabel 3.1) en `β_w` (tabel 4.1).
 */
staalsoort: string, };
