// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lassoort } from "./Lassoort";

/**
 * De uitkomst per naad. Alle tussenwaarden staan erbij, zodat het rapport de
 * afleiding kan tonen zonder iets over te hoeven rekenen.
 */
export type LasResultaat = { id: string, soort: Lassoort, a_mm: number, 
/**
 * Meewerkende keeldikte in totaal (mm): `a` of `2a`.
 */
a_totaal_mm: number, staalsoort: string, 
/**
 * Nominale treksterkte van het zwakste verbonden onderdeel (N/mm²).
 */
f_u_mpa: number, 
/**
 * Correlatiefactor volgens tabel 4.1.
 */
beta_w: number, gamma_m2: number, 
/**
 * Rekenwaarde van de schuifsterkte van de las (N/mm²), formule (4.4).
 */
f_vw_d_mpa: number, 
/**
 * Rekenwaarde van de weerstand per eenheidslengte (N/mm), formule (4.3).
 */
f_w_rd_n_per_mm: number, f_w_ed_n_per_mm: number, 
/**
 * Schuifspanning in de keeldoorsnede (N/mm²): `F_w,Ed / a_totaal`.
 */
tau_mpa: number, 
/**
 * `F_w,Ed / F_w,Rd`; 0 wanneer er niet te toetsen valt.
 */
uc: number, 
/**
 * `false` zodra er geen unity check is (stompe las, of ontbrekende invoer).
 */
getoetst: boolean, 
/**
 * Meldingen voor scherm en rapport; leeg als er niets te melden is.
 */
meldingen: Array<string>, };
