// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Soort naad tussen twee delen van een samengestelde doorsnede.
 */
export type Lassoort = "HoeklasEnkel" | "HoeklasDubbel" | "StompVolledig";
