// Lag-notatie + ploeg-preset-checks (gebruikstest-bevindingen F1/F2, 2026-08-15).
//
// F1: het lag-invoerveld (SequenceLagInput/lagFormat.ts) accepteerde geen uren-syntax ("2u")
// en de reguliere `updateSequence`-actie liet `lagMinutes` vallen. Dit bestand bewijst:
//  (1) parseLagInput/formatLagShort — round-trip voor d/ed/%/e%/u/h/eu/eh + afgewezen invoer.
//  (2) updateSequence (de ECHTE Zustand-store-actie, geen rauwe setState) zet/wist lagMinutes
//      net als de andere lag-representaties (precedentie lagPercent → lagMinutes → lagDays,
//      CPMSolver.resolveLagMinutes).
//
// F2: de "3 ploegen"-preset die de gids belooft ontbrak in de kalenderdialoog-rij
// (CALENDAR_PRESETS). Dit bestand bewijst de bandenstructuur (3× 8u, som = 24u, middernacht-
// wrap) en dat de preset nu in CALENDAR_PRESETS staat.
//
// B3 (addendum van het IFC-team, 2026-08-15): `applyPreset`/`applyBuiltinPreset` in CalendarForm.tsx
// patchte workTime/shift/uren maar niet `description`, dus de fabrieksomschrijving ("Standaard
// bouwkalender: ma-vr 07:00-16:00") bleef letterlijk staan op een net-toegepaste 2-ploegen-kalender.
// De React-component zelf is hier niet headless te draaien, maar de PURE beslissingslaag
// (`presetDescription`/`isAutoGeneratedDescription` in shiftPresets.ts) wel — dit bewijst dat de
// gegenereerde tekst altijd de werkelijke uren volgt, dat een preset-wissel blijft meelopen zolang
// de tekst aantoonbaar machine-gegenereerd is, en dat een handmatige omschrijving nooit matcht.
//
// Draait via run.sh (esbuild-bundel, zoals check-calendar-hours.ts). Exit 0 = alles groen.
import { parseLagInput, formatLagShort } from '@/utils/lagFormat';
import { formatExternalLagShort, parseExternalLagInput } from '@/engine/taskGrid/relationFormat';
import {
  CALENDAR_PRESETS, WIZARD_PRESETS, shiftPresetPatch, presetDescription, isAutoGeneratedDescription,
} from '@/utils/shiftPresets';
import { useAppStore } from '@/state/appStore';

const diffs: string[] = [];
let checks = 0;
const eq = (label: string, got: unknown, want: unknown) => {
  checks++;
  if (JSON.stringify(got) !== JSON.stringify(want)) {
    diffs.push(`${label}: verwacht ${JSON.stringify(want)}, kreeg ${JSON.stringify(got)}`);
  }
};

// ═══════════════════════════════════════════════════════════════════════════
// 1) parseLagInput — geldige vormen (dagen, procent, uren, elapsed-varianten).
// ═══════════════════════════════════════════════════════════════════════════
eq('01 "2d" ⇒ lagDays 2', parseLagInput('2d'), { lagDays: 2, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined });
eq('02 "-1d" ⇒ lagDays -1', parseLagInput('-1d'), { lagDays: -1, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined });
eq('03 kaal "2" ⇒ lagDays 2 (werkdagen)', parseLagInput('2'), { lagDays: 2, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined });
eq('04 "3ed" ⇒ lagDays 3, ELAPSEDTIME', parseLagInput('3ed'), { lagDays: 3, lagUnit: 'ELAPSEDTIME', lagPercent: undefined, lagMinutes: undefined });
eq('05 "50%" ⇒ lagPercent 50', parseLagInput('50%'), { lagDays: 0, lagUnit: undefined, lagPercent: 50, lagMinutes: undefined });
eq('06 "-25e%" ⇒ lagPercent -25, ELAPSEDTIME', parseLagInput('-25e%'), { lagDays: 0, lagUnit: 'ELAPSEDTIME', lagPercent: -25, lagMinutes: undefined });
eq('07 "" ⇒ lag 0 (alles undefined/0)', parseLagInput(''), { lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined });

// Uren — de F1-toevoeging. "u" is de weergavevorm (taalonafhankelijk, zoals "d"); "h" is
// ALLEEN-invoer, symmetrisch met parseDuration in durationFormat.ts.
eq('08 "2u" ⇒ lagMinutes 120, lagDays 0', parseLagInput('2u'), { lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: 120 });
eq('09 "2h" ⇒ zelfde als "2u" (taalonafhankelijke invoer)', parseLagInput('2h'), parseLagInput('2u'));
eq('10 "-1u" ⇒ lagMinutes -60 (lead in uren)', parseLagInput('-1u'), { lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: -60 });
eq('11 "3eu" ⇒ lagMinutes 180, ELAPSEDTIME', parseLagInput('3eu'), { lagDays: 0, lagUnit: 'ELAPSEDTIME', lagPercent: undefined, lagMinutes: 180 });
eq('12 "3eh" ⇒ zelfde als "3eu"', parseLagInput('3eh'), parseLagInput('3eu'));
eq('13 "1.5u" ⇒ lagMinutes 90 (decimaal uur toegestaan)', parseLagInput('1.5u'), { lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: 90 });
eq('14 "1,5u" (komma) ⇒ zelfde als "1.5u"', parseLagInput('1,5u'), parseLagInput('1.5u'));
eq('15 "+2U" (hoofdletters) ⇒ zelfde als "2u"', parseLagInput('+2U'), parseLagInput('2u'));
eq('16 " 2 u " (spaties) ⇒ zelfde als "2u"', parseLagInput(' 2 u '), parseLagInput('2u'));

// ── Ongeldige invoer ⇒ null (geen stille 0, geen crash). ──
for (const bad of ['abc', '2x', '2dd', '2u%', '2e', '--2d', '2u u', '%', 'u']) {
  eq(`17.${bad} onparseerbaar ⇒ null`, parseLagInput(bad), null);
}

// ═══════════════════════════════════════════════════════════════════════════
// 2) formatLagShort — precedentie lagPercent → lagMinutes → lagDays, spiegelt CPMSolver.
// ═══════════════════════════════════════════════════════════════════════════
eq('18 lagDays 2 ⇒ "+2d"', formatLagShort({ lagDays: 2, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined }), '+2d');
eq('19 lagDays 0 (niets anders) ⇒ ""', formatLagShort({ lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined }), '');
eq('20 lagPercent 50 ⇒ "+50%" (negeert lagDays)', formatLagShort({ lagDays: 5, lagUnit: undefined, lagPercent: 50, lagMinutes: undefined }), '+50%');
eq('21 lagMinutes 120 ⇒ "+2u" (UREN-vorm, niet een dag-vorm)', formatLagShort({ lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: 120 }), '+2u');
eq('22 lagMinutes 120 + lagDays 3 ⇒ nog steeds "+2u" (minuten winnen)', formatLagShort({ lagDays: 3, lagUnit: undefined, lagPercent: undefined, lagMinutes: 120 }), '+2u');
eq('23 lagMinutes -60 ⇒ "-1u"', formatLagShort({ lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: -60 }), '-1u');
eq('24 lagMinutes 90, ELAPSEDTIME ⇒ "+1.5eu"', formatLagShort({ lagDays: 0, lagUnit: 'ELAPSEDTIME', lagPercent: undefined, lagMinutes: 90 }), '+1.5eu');
eq('25 lagMinutes 0 (expliciet) ⇒ valt terug op lagDays-vorm', formatLagShort({ lagDays: 0, lagUnit: undefined, lagPercent: undefined, lagMinutes: 0 }), '');
eq('26 lagMinutes 0 + lagDays 4 ⇒ "+4d" (0-minuten telt niet als "gezet" voor de weergave)', formatLagShort({ lagDays: 4, lagUnit: undefined, lagPercent: undefined, lagMinutes: 0 }), '+4d');

// De latere relationele clipboardformatter bouwt op deze bestaande centrale korte vorm. Pin daarom
// nu al de directe format→parse-roundtrip, inclusief lead, procent en elapsed-uren.
for (const [label, fields] of [
  ['dag-lag', { lagDays: 2, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined }],
  ['negatieve lead', { lagDays: -1, lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined }],
  ['elapsed procent', { lagDays: 0, lagUnit: 'ELAPSEDTIME' as const, lagPercent: -25, lagMinutes: undefined }],
  ['elapsed uur', { lagDays: 0, lagUnit: 'ELAPSEDTIME' as const, lagPercent: undefined, lagMinutes: 90 }],
] as const) {
  eq(`26 clipboard-roundtrip ${label}`, parseLagInput(formatLagShort(fields)), fields);
}

// ── Round-trip: format(parse(s)) genormaliseerd, en parse(format(seq)) == seq voor elk veld. ──
for (const s of ['2d', '-1d', '3ed', '50%', '-25e%', '2u', '-1u', '3eu', '1.5u']) {
  const parsed = parseLagInput(s)!;
  const formatted = formatLagShort(parsed);
  const reparsed = parseLagInput(formatted)!;
  eq(`27.${s} round-trip parse→format→parse stabiel`, reparsed, parsed);
}

// Externe links hebben bewust een smaller datamodel dan interne Sequences: precies één vaste
// dag- of minutenbron, dus geen elapsed/procent. Hiermee kan de gezamenlijke cel geen waarde tonen
// die ExternalLink, refresh en import/export niet verliesloos kunnen bewaren.
eq('27.ext kaal getal ⇒ uitsluitend lagDays', parseExternalLagInput('2'), { lagDays: 2 });
eq('27.ext d ⇒ uitsluitend lagDays', parseExternalLagInput('-1d'), { lagDays: -1 });
eq('27.ext u ⇒ uitsluitend lagMinutes', parseExternalLagInput('1.5u'), { lagMinutes: 90 });
eq('27.ext h is invoeralias voor u', parseExternalLagInput('1.5h'), { lagMinutes: 90 });
eq('27.ext uurformatter gebruikt canonieke u-vorm', formatExternalLagShort({ lagMinutes: 90 }), '+1.5u');
for (const unsupported of ['50%', '-25e%', '3ed', '2eu', '2eh']) {
  eq(`27.ext ${unsupported} wordt geweigerd`, parseExternalLagInput(unsupported), null);
}

// ═══════════════════════════════════════════════════════════════════════════
// 3) updateSequence — de ECHTE store-actie (geen rauwe setState) zet/wist lagMinutes.
// ═══════════════════════════════════════════════════════════════════════════
const S = () => useAppStore.getState();
const idA = S().addTask({ name: 'A' });
const idB = S().addTask({ name: 'B' });
// `addSequence` kan sinds de verzameltaak-eindpunt-weigering (main, 2026-08) `null` retourneren;
// een blad→blad-relatie mag nooit geweigerd worden, dus pin dat hier vóór de rest erop leunt.
const seqIdOrNull = S().addSequence({ predecessorId: idA, successorId: idB, type: 'FINISH_START', lagDays: 0 });
eq('27a addSequence levert een id voor blad→blad (geen weigering)', seqIdOrNull !== null, true);
const seqId = seqIdOrNull!;

const applied1 = S().updateSequence(seqId, parseLagInput('2u')!);
eq('28 updateSequence("2u") retourneert true', applied1, true);
const seqAfterHours = S().sequences.find(s => s.id === seqId);
eq('29 seq.lagMinutes == 120 ná updateSequence', seqAfterHours?.lagMinutes, 120);
eq('30 seq.lagDays == 0 ná uren-lag (fallback, geen misleidende dag-waarde)', seqAfterHours?.lagDays, 0);
eq('31 seq.lagUnit == undefined (WORKTIME, geen elapsed)', seqAfterHours?.lagUnit, undefined);

// Terugschakelen naar een dag-lag moet de eerder gezette lagMinutes WISSEN — anders overrulet de
// achtergebleven minuut-lag de nieuwe dag-lag (CPMSolver.resolveLagMinutes: percent → minutes →
// days), exact de valkuil die sequenceFields.ts voor de MCP-bridge documenteert.
const applied2 = S().updateSequence(seqId, parseLagInput('3d')!);
eq('32 updateSequence("3d") retourneert true', applied2, true);
const seqAfterDays = S().sequences.find(s => s.id === seqId);
eq('33 seq.lagDays == 3 ná dag-lag', seqAfterDays?.lagDays, 3);
eq('34 seq.lagMinutes == undefined ná dag-lag (gewist, niet achtergebleven)', seqAfterDays?.lagMinutes, undefined);

// En weer terug naar uren, gevolgd door een elapsed-uren-lag.
S().updateSequence(seqId, parseLagInput('4u')!);
eq('35 seq.lagMinutes == 240 ná "4u"', S().sequences.find(s => s.id === seqId)?.lagMinutes, 240);
S().updateSequence(seqId, parseLagInput('2eu')!);
const seqElapsed = S().sequences.find(s => s.id === seqId);
eq('36 seq.lagMinutes == 120 ná "2eu"', seqElapsed?.lagMinutes, 120);
eq('37 seq.lagUnit == ELAPSEDTIME ná "2eu"', seqElapsed?.lagUnit, 'ELAPSEDTIME');

// Een procent-lag moet zowel lagDays als lagMinutes wissen (precedentie: percent wint sowieso,
// maar de velden moeten niet blijven rondslingeren).
S().updateSequence(seqId, parseLagInput('50%')!);
const seqPercent = S().sequences.find(s => s.id === seqId);
eq('38 seq.lagPercent == 50 ná "50%"', seqPercent?.lagPercent, 50);
eq('39 seq.lagMinutes == undefined ná procent-lag', seqPercent?.lagMinutes, undefined);
eq('40 seq.lagDays == 0 ná procent-lag', seqPercent?.lagDays, 0);

// Direct-patch met lagMinutes: undefined moet de minuut-lag ook via een expliciete patch wissen
// (niet alleen via de parser — de actie zelf moet 'lagMinutes' in patch onderscheiden van
// afwezig, zie de `'lagMinutes' in patch`-guard in sequenceSlice.ts).
S().updateSequence(seqId, { lagMinutes: 300, lagDays: 0, lagPercent: undefined, lagUnit: undefined });
eq('41 directe patch lagMinutes:300 wordt gezet', S().sequences.find(s => s.id === seqId)?.lagMinutes, 300);
S().updateSequence(seqId, { lagMinutes: undefined });
eq('42 directe patch lagMinutes:undefined wist het veld', S().sequences.find(s => s.id === seqId)?.lagMinutes, undefined);

// ═══════════════════════════════════════════════════════════════════════════
// 3b) updateSequence zonder werkelijke wijziging is een no-op (audit taakmutaties, bevinding 9).
//     Het lag-veld in het eigenschappenpaneel (SequenceLagInput) commit bij elke blur. Alleen in-
//     en uitklikken maakte het document gewijzigd, zette "Herbereken" aan en gaf een loze undo-stap
//     (de eerste Ctrl+Z deed zichtbaar niets). Raster en MCP zagen "niets gewijzigd" al; nu ook de
//     store-actie — zelfde semantiek als de no-op-guard van `updateTask` (`sameValue`).
// ═══════════════════════════════════════════════════════════════════════════
{
  S().newProject();
  const a = S().addTask({ name: 'Grondwerk' });
  const b = S().addTask({ name: 'Fundering' });
  const id = S().addSequence({ predecessorId: a, successorId: b, type: 'FINISH_START', lagDays: 2 })!;
  S().runCPM();
  useAppStore.setState(s => { s.isDirty = false; });
  const depth = () => S().historyEvents.filter(event => event.state === 'applied').length;
  const before = { depth: depth(), sequences: S().sequences };
  const snap = () => ({ isDirty: S().isDirty, stale: S().scheduleStale, depth: depth() });

  // Precies wat het lag-veld bij een blur zonder typen doet: de getoonde tekst opnieuw parsen.
  const shown = formatLagShort(S().sequences.find(q => q.id === id)!);
  eq('42a het lag-veld toont "+2d"', shown, '+2d');
  eq('42b blur zonder wijziging: updateSequence meldt "in orde"', S().updateSequence(id, parseLagInput(shown)!), true);
  eq('42c … geen dirty, geen stale, geen undo-stap', snap(), { isDirty: false, stale: false, depth: before.depth });
  eq('42d … en de relatie is referentieel ongewijzigd', S().sequences === before.sequences, true);
  eq('42e zelfde type opnieuw kiezen is ook een no-op', (S().updateSequence(id, { type: 'FINISH_START' }), snap()),
    { isDirty: false, stale: false, depth: before.depth });
  eq('42f een expliciete undefined op een afwezig lagveld is geen wijziging', (S().updateSequence(id, {
    lagUnit: undefined, lagPercent: undefined, lagMinutes: undefined,
  }), snap()), { isDirty: false, stale: false, depth: before.depth });

  // Een echte wijziging blijft gewoon één undo-stap.
  eq('42g echte lagwijziging slaagt', S().updateSequence(id, parseLagInput('3d')!), true);
  eq('42h … en is dirty, stale en één undo-stap', snap(), { isDirty: true, stale: true, depth: before.depth + 1 });
  eq('42i … met de nieuwe lag', S().sequences.find(q => q.id === id)?.lagDays, 3);
  eq('42j onbekend relatie-id blijft een stille weigering', S().updateSequence('bestaat-niet', { lagDays: 1 }), false);
}

// ═══════════════════════════════════════════════════════════════════════════
// 4) Ploeg-preset "3 ploegen" (F2) — bandenstructuur, afgeleide uren, middernacht-wrap,
//    en aanwezigheid in zowel CALENDAR_PRESETS (kalenderdialoog) als WIZARD_PRESETS.
// ═══════════════════════════════════════════════════════════════════════════
eq('43 CALENDAR_PRESETS bevat three-shift (F2-fix)', CALENDAR_PRESETS.includes('three-shift'), true);
eq('44 WIZARD_PRESETS bevat three-shift (bestond al)', WIZARD_PRESETS.includes('three-shift'), true);

const three = shiftPresetPatch('three-shift');
eq('45 three-shift.hoursPerDay == 24', three.hoursPerDay, 24);
eq('46 three-shift.workStartHour == 0', three.workStartHour, 0);
eq('47 three-shift.workEndHour == 24', three.workEndHour, 24);
eq('48 three-shift.workDays == ma-vr', three.workDays, [1, 2, 3, 4, 5]);
eq('49 three-shift is geen dag-kalender (workTime gezet)', !!three.workTime, true);

const mondayBands = three.workTime?.byWeekday[1] ?? [];
eq('50 three-shift: 3 banden op maandag', mondayBands.length, 3);
eq('51 three-shift: band 1 = 06:00-14:00', mondayBands[0], { start: 360, end: 840 });
eq('52 three-shift: band 2 = 14:00-22:00', mondayBands[1], { start: 840, end: 1320 });
eq('53 three-shift: band 3 = 22:00-06:00(wrap)', mondayBands[2], { start: 1320, end: 1800 });
// Middernacht-wrap: band 3 eindigt > 1440 (volgende dag), exact zoals Nachtploeg (§3.2 canoniek
// [start,end), wrap ⇒ end ∈ (1440,2880]).
eq('54 three-shift: band 3 wrapt over middernacht (end > 1440)', mondayBands[2].end > 1440, true);
eq('55 three-shift: band 3 eindtijd binnen (1440,2880]', mondayBands[2].end > 1440 && mondayBands[2].end <= 2880, true);
// Aaneengesloten: elke band sluit exact aan op de vorige (geen gat, geen overlap).
eq('56 three-shift: band1.end == band2.start (aaneengesloten)', mondayBands[0].end, mondayBands[1].start);
eq('57 three-shift: band2.end == band3.start (aaneengesloten)', mondayBands[1].end, mondayBands[2].start);
// Som van de banden = 24 klokuur = hoursPerDay × 60.
const totalMin = mondayBands.reduce((sum, b) => sum + (b.end - b.start), 0);
eq('58 three-shift: som van de banden == 1440m (24u)', totalMin, 24 * 60);
// Alle 5 werkdagen krijgen dezelfde banden (makeBands-conventie).
for (const d of [2, 3, 4, 5] as const) {
  eq(`59.${d} three-shift: dag ${d} zelfde banden als maandag`, three.workTime?.byWeekday[d], mondayBands);
}
eq('60 three-shift: za/zo blijven leeg', [three.workTime?.byWeekday[6], three.workTime?.byWeekday[7]], [[], []]);
// shift-classificatie: geen van de vaste ENUM-namen (FIRST/SECOND/THIRD) dekt drie ploegen ⇒
// USERDEFINED, zelfde als 24/7.
eq('61 three-shift.shift == USERDEFINED', three.shift, 'USERDEFINED');

// ═══════════════════════════════════════════════════════════════════════════
// 5) B3 — preset-omschrijving (presetDescription/isAutoGeneratedDescription), addendum 2026-08-15.
//    De React-laag (CalendarForm.applyBuiltinPreset) is hier niet headless te draaien; dit bewijst
//    de PURE beslissingslaag die dat gedrag draagt.
// ═══════════════════════════════════════════════════════════════════════════
// presetDescription volgt de WERKELIJKE uren van elke preset (nooit een stale letterlijke tekst).
eq('62 presetDescription(day) noemt de echte uren (08-16)', presetDescription('day'), 'Dagdienst: ma-vr 08:00-16:00');
eq('63 presetDescription(two-shift) noemt 06:00-22:00', presetDescription('two-shift'), '2 ploegen: ma-vr 06:00-22:00');
eq('64 presetDescription(three-shift) noemt 00:00-24:00, ma-vr', presetDescription('three-shift'), '3 ploegen: ma-vr 00:00-24:00');
eq('65 presetDescription(night) noemt de wrap-uren 22-06', presetDescription('night'), 'Nachtploeg: ma-vr 22:00-06:00');
eq('66 presetDescription(continuous) noemt alle dagen', presetDescription('continuous'), '24/7: alle dagen 00:00-24:00');
// three-shift en continuous dekken allebei de volle dag maar op een ander dagenbereik — de
// omschrijvingen mogen dus NOOIT gelijk zijn (anders zou een preset-wissel tussen die twee stil
// een no-op voor de description lijken).
eq('67 three-shift- en continuous-omschrijving verschillen (dagenbereik)', presetDescription('three-shift') !== presetDescription('continuous'), true);

// isAutoGeneratedDescription: de twee historische fabrieksdefaults + alle vijf preset-vormen ⇒ true;
// alles anders (leeg, handmatig getypt, of een tekst die toevallig op een preset-omschrijving lijkt
// maar een teken afwijkt) ⇒ false.
eq('68 fabrieksdefault (bouwmodus) ⇒ auto-gegenereerd', isAutoGeneratedDescription('Standaard bouwkalender: ma-vr 07:00-16:00'), true);
eq('69 fabrieksdefault (neutraal) ⇒ auto-gegenereerd', isAutoGeneratedDescription('Standaardkalender: ma-vr 07:00-16:00'), true);
for (const key of ['day', 'two-shift', 'three-shift', 'night', 'continuous'] as const) {
  eq(`70.${key} presetDescription(${key}) zelf ⇒ auto-gegenereerd (preset→preset blijft meelopen)`, isAutoGeneratedDescription(presetDescription(key)), true);
}
eq('71 lege omschrijving ⇒ NIET auto-gegenereerd', isAutoGeneratedDescription(''), false);
eq('72 handmatige omschrijving ⇒ NIET auto-gegenereerd', isAutoGeneratedDescription('Vaste onderaannemerskalender, zie contract §4'), false);
eq('73 bijna-gelijk (1 teken af) ⇒ NIET auto-gegenereerd', isAutoGeneratedDescription('Dagdienst: ma-vr 08:00-17:00'), false);
// Regressie-kern van B3 zelf: een fabrieksdefault-omschrijving die de gebruiker met de hand exact
// terugtypt (toeval, of copy-paste) telt óók als "auto" — de golden rule kan tekstueel niet
// onderscheiden van bedoeling, en dat is een bewuste, gedocumenteerde afweging (zie de JSDoc in
// shiftPresets.ts), geen gat: de kans dat iemand LETTERLIJK dezelfde tekst intypt is verwaarloosbaar
// t.o.v. de winst dat elke automatische preset-keten blijft meelopen.

if (diffs.length === 0) {
  console.log(`OK  lag-format-check: alle checks groen (${checks})`);
  process.exit(0);
} else {
  console.log(`XX  lag-format-check: ${diffs.length} afwijking(en) van ${checks}`);
  for (const d of diffs) console.log(`   - ${d}`);
  process.exit(1);
}
