// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Catalogus = { 
/**
 * Profielnaam; dezelfde zoeksleutel als de staaltoetsing ("HEA200",
 * "HEA 200" en "hea-200" vinden hetzelfde profiel).
 */
naam: string, };
