// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanningLaag } from "./SpanningLaag";

export type Lagenmodel = { 
/**
 * Lagen van boven naar beneden; aaneengesloten, dus `z_bot` van laag i
 * is `z_top` van laag i+1.
 */
lagen: Array<SpanningLaag>, };
