// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén rekenpunt van het spanningsverloop over de hoogte.
 *
 * Op een laaggrens komt dezelfde `z_mm` twee keer voor — één keer met de
 * breedte erboven en één keer met die eronder. Zo staat de sprong in τ in de
 * gegevens en hoeft de tekening hem niet te raden.
 */
export type SpanningVezel = { 
/**
 * Hoogte vanaf de bovenkant van de doorsnede (mm).
 */
z_mm: number, 
/**
 * Meewerkende breedte op deze hoogte (mm).
 */
breedte_mm: number, 
/**
 * Statisch moment van het deel bóven z om de zwaartelijn (mm³).
 */
s_mm3: number, 
/**
 * Normaalspanning σ_x (N/mm², trek positief).
 */
sigma_x_mpa: number, 
/**
 * Schuifspanning τ (N/mm², absolute waarde).
 */
tau_mpa: number, 
/**
 * Vergelijkspanning σ_eq (N/mm², altijd ≥ 0).
 */
sigma_eq_mpa: number, };
