// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén laag van het vezelmodel: constante breedte tussen twee hoogten.
 * `z` loopt vanaf de bovenkant van de doorsnede naar beneden (mm).
 */
export type SpanningLaag = { 
/**
 * Bovenkant van de laag vanaf de bovenkant van de doorsnede (mm).
 */
z_top_mm: number, 
/**
 * Onderkant van de laag (mm).
 */
z_bot_mm: number, 
/**
 * Meewerkende breedte van de laag (mm). Voor een koker de som van beide
 * wanden, voor een buis de som van de twee wanddoorsneden op die hoogte.
 */
breedte_mm: number, };
