// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanningVezel } from "./SpanningVezel";

/**
 * Het spanningsverloop bij één snedekrachtenset (de maatgevende).
 */
export type SpanningVerloop = { combination_id: number, 
/**
 * Plaats langs de staaf (mm vanaf de startknoop).
 */
position_mm: number, n_ed_kn: number, vz_ed_kn: number, my_ed_knm: number, 
/**
 * De aangenomen dwarsspanning (N/mm²), constant over de hoogte.
 */
sigma_z_mpa: number, vezels: Array<SpanningVezel>, 
/**
 * Hoogte waar σ_eq maximaal is (mm vanaf boven).
 */
z_maatgevend_mm: number, };
