// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForcePoint } from "../steel/ForcePoint";
import type { SpanningDoorsnede } from "./SpanningDoorsnede";

/**
 * Invoer voor één staaf die op vergelijkspanning getoetst wordt.
 *
 * Dit is bewust GEEN normtoetsing: er is geen materiaalnorm, geen
 * doorsnedeklassificatie, geen knik-, kip- of doorbuigingsgrens. De
 * toelaatbare spanning komt volledig van de gebruiker; de kern rekent alleen
 * de spanningen uit de snedekrachten en vergelijkt ze daarmee.
 */
export type SpanningBeamCheckInput = { beam_id: number, 
/**
 * De doorsnede: rechthoek, catalogusprofiel of vrij lagenmodel.
 */
section: SpanningDoorsnede, 
/**
 * Naam van het materiaal zoals de gebruiker het genoemd heeft, bijv.
 * "Natuursteen". Alleen voor de kopregel en het rapport.
 */
material_name: string, 
/**
 * Toelaatbare spanning f_toel in N/mm². Positief.
 */
f_toel_mpa: number, 
/**
 * Materiaalfactor γ_M; de rekenwaarde is f_d = f_toel / γ_M.
 * Standaard 1,0 — dan is f_toel zelf de rekenwaarde.
 */
gamma_m: number, 
/**
 * Dwarsspanning σ_z in N/mm² (bijv. een oplegdruk), constant over de
 * doorsnede aangenomen. Het staafmodel berekent σ_z niet zelf: een
 * staafelement kent alleen N, V en M. Standaard 0.
 */
sigma_z_mpa: number, 
/**
 * Staaflengte in m — alleen voor de kopregel van het rapport.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N trek-positief, M_y positief
 * = trek in de onderste vezel (zie `mechanics::InternalForces`).
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Richtaantal rekenpunten over de hoogte; elke laag krijgt er minstens
 * drie. Standaard 21.
 */
fiber_count: number, };
