// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { NamedCheck } from "../steel/NamedCheck";
import type { SpanningDoorsnedeResultaat } from "./SpanningDoorsnedeResultaat";
import type { SpanningVerloop } from "./SpanningVerloop";

/**
 * Volledig toetsresultaat van één staaf op vergelijkspanning.
 */
export type SpanningBeamCheckResult = { beam_id: number, 
/**
 * Doorsnedenaam voor de kopregel, bijv. "HEA 200" of "300 × 500 mm".
 */
section_name: string, 
/**
 * Materiaalnaam zoals de gebruiker hem gaf.
 */
material_name: string, f_toel_mpa: number, gamma_m: number, 
/**
 * Rekenwaarde f_d = f_toel / γ_M (N/mm²).
 */
f_d_mpa: number, checks: Array<NamedCheck>, uc_max: number, status: CheckStatus, governing_check_id: string, section: SpanningDoorsnedeResultaat, 
/**
 * Spanningsverloop bij de maatgevende snede; leeg bij een fout.
 */
verloop: SpanningVerloop | null, 
/**
 * Aannamen, benaderingen en meldingen voor paneel en rapport.
 */
notes: Array<string>, };
