// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanningLaag } from "./SpanningLaag";

/**
 * De uitgewerkte doorsnede: lagenmodel plus de gebruikte grootheden.
 */
export type SpanningDoorsnedeResultaat = { naam: string, hoogte_mm: number, 
/**
 * Grootste laagbreedte (mm) — voor de schaal van de tekening.
 */
breedte_max_mm: number, 
/**
 * Zwaartelijn vanaf de bovenkant (mm).
 */
z_c_mm: number, a_mm2: number, iy_mm4: number, 
/**
 * Elastisch weerstandsmoment naar de bovenste vezel (mm³).
 */
wel_top_mm3: number, 
/**
 * Elastisch weerstandsmoment naar de onderste vezel (mm³).
 */
wel_bot_mm3: number, 
/**
 * Herkomst van A en I_y: "profieldatabase" of "lagenmodel".
 */
bron: string, lagen: Array<SpanningLaag>, };
