// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Catalogus } from "./Catalogus";
import type { Lagenmodel } from "./Lagenmodel";
import type { Rechthoek } from "./Rechthoek";

/**
 * De doorsnede zoals de gebruiker hem opgeeft.
 *
 * Drie vormen, alle drie met een echte geometrie — juist omdat het
 * spanningsverloop over de hoogte getekend moet worden. Een doorsnede die
 * alleen als A/I/W bekend is heeft geen vezelverdeling en zou dus geen
 * verloop kunnen leveren; die vorm zit hier bewust niet in. Wie toch een
 * vrije doorsnede wil, geeft hem als `Lagen`.
 */
export type SpanningDoorsnede = { "vorm": "Rechthoek", "maten": Rechthoek } | { "vorm": "Catalogus", "maten": Catalogus } | { "vorm": "Lagen", "maten": Lagenmodel };
