// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { CltLayupResult } from "./CltLayupResult";
import type { KmodPerLoadDuration } from "./KmodPerLoadDuration";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { NamedCheck } from "../steel/NamedCheck";
import type { ServiceClass } from "./ServiceClass";

/**
 * Volledig toetsresultaat van één CLT-staaf. Structureel een superset van
 * `TimberBeamCheckResult` (zie moduledocumentatie).
 */
export type CltBeamCheckResult = { beam_id: number, 
/**
 * Bijv. "CLT 40/20/40/20/40 (h = 160 mm, b = 1000 mm)".
 */
section_name: string, 
/**
 * Sterkteklasse(n) van de lamellen, bijv. "C24" of "C24/C16".
 */
strength_class: string, service_class: ServiceClass, 
/**
 * Zonder belastingduur per combinatie: de klasse uit de invoer; met die
 * lijst: de klasse van de maatgevende toets.
 */
load_duration: LoadDurationClass, checks: Array<NamedCheck>, uc_max: number, status: CheckStatus, governing_check_id: string, 
/**
 * De opbouw met de uitkomst per laag.
 */
layup: CltLayupResult, 
/**
 * Aannamen en meldingen voor het rapport.
 */
notes: Array<string>, 
/**
 * k_mod per belastingduurklasse met de combinaties erin (§3.1.3(2));
 * leeg zonder belastingduur per combinatie.
 */
k_mod_per_load_duration?: Array<KmodPerLoadDuration>, 
/**
 * De combinatie van het maatgevende krachtpunt van de zwaarste toets.
 */
governing_combination_id?: number, };
