// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayup } from "./CltLayup";
import type { CombinationLoadDuration } from "./CombinationLoadDuration";
import type { ForcePoint } from "../steel/ForcePoint";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { ServiceClass } from "./ServiceClass";

/**
 * Invoer voor één CLT-staaf (plaatstrook).
 *
 * `deny_unknown_fields`, om dezelfde reden als bij
 * [`crate::TimberBeamCheckInput`]: `k_cr` en `load_sharing` hebben een
 * standaardwaarde, en een tikfout in die namen viel stil op die standaard
 * terug (gemeten: `kcr` werd genegeerd).
 */
export type CltBeamCheckInput = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, beam_id: number, 
/**
 * Opbouw: breedte van de strook en de lagen van boven naar beneden.
 */
layup: CltLayup, 
/**
 * Klimaatklasse §2.3.1.3.
 */
service_class: ServiceClass, 
/**
 * Belastingduurklasse (§2.3.1.2) voor de hele omhullende, en de terugval
 * voor een combinatie die niet in `load_duration_per_combination` staat.
 * Zonder die lijst geldt deze ene klasse voor ALLE combinaties, en wordt
 * de combinatie met alleen de blijvende belasting dus niet met k_mod
 * "blijvend" getoetst (§3.1.3(2)).
 */
load_duration: LoadDurationClass, 
/**
 * De belastingduurklasse per UGT-combinatie (§3.1.3(2)); leeg = het
 * gedrag van vóór dit veld. Zie `crate::belastingduur`.
 */
load_duration_per_combination?: Array<CombinationLoadDuration>, 
/**
 * Staaflengte in m (voor de slankheidsindicatie L/h).
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Scheurfactor k_cr (6.13a); NB: 1,0 voor prismatische doorsneden.
 */
k_cr: number, 
/**
 * Lastverdelend systeem aanwezig → k_sys = 1,1 (§6.6).
 */
load_sharing: boolean, 
/**
 * Vervormingsfactor k_def voor de kruip van §7.2 — VERPLICHT om te
 * kunnen toetsen, en met opzet zonder standaardwaarde.
 *
 * Tabel 3.2 kent geen rij voor kruislaaghout (zie de kop van deze
 * module). Een waarde lenen van gezaagd of gelijmd gelamineerd hout zou
 * een normwaarde suggereren die er niet is; een waarde aannemen zou de
 * eindzakking van elke CLT-vloer op een verzonnen getal baseren. `None`
 * betekent daarom: geen doorbuigingstoets, met die reden in het
 * resultaat. De waarde hoort uit de productverklaring of de ETA van de
 * gekozen plaat te komen, per klimaatklasse.
 */
k_def?: number, 
/**
 * Waar de opgegeven `k_def` vandaan komt — ook verplicht zodra `k_def`
 * is ingevuld, en letterlijk in de notitie bij de toets.
 *
 * Waarom niet optioneel: een kruipfactor zonder herkomst is in het
 * rapport niet te onderscheiden van een aangenomen getal, en juist die
 * ononderscheidbaarheid is de reden dat deze toets er tot september 2026
 * niet was. Bijvoorbeeld: "ETA-14/0349, tabel 8, klimaatklasse 1".
 */
k_def_bron?: string, 
/**
 * Zakking onder de karakteristieke BGT-combinatie (mm, negatief = omlaag).
 */
deflection_inst_mm: number, 
/**
 * Zakking onder de quasi-blijvende BGT-combinatie (mm).
 */
deflection_quasi_perm_mm: number, 
/**
 * Zakking onder de BGT-combinatie met alleen de blijvende belasting
 * (mm) — w₁ uit figuur NB.1 bij NEN-EN 1990:2002/NB:2019 A1.4.3(2).
 */
deflection_permanent_mm: number, 
/**
 * Noemer voor w_fin (L/n), NB-standaard 250.
 */
deflection_limit_fin: number, 
/**
 * Noemer voor w_add (L/n), NB-standaard 333.
 */
deflection_limit_add: number, 
/**
 * Vrije toelichtingen bij de doorbuigingstoets; zelfde rol als bij
 * [`crate::TimberBeamCheckInput`]: uit welke combinatie elke zakking komt
 * en welke terugval er eventueel is toegepast.
 */
deflection_notes: Array<string>, 
/**
 * Langeduurzakking w_qp,fin (mm, met teken): de zakking onder de
 * quasi-blijvende BGT-combinatie, berekend met de EINDSTIJFHEID
 * E_mean,fin = E_mean/(1 + k_def) van het hout (EN 1995-1-1 2.3.2.2(1),
 * uitdrukking 2.7) en de langeduurstijfheid van de andere delen.
 *
 * Waarom dit bestaat: in een statisch onbepaalde constructie met delen
 * van verschillend kruipgedrag (hout naast staal, beton of hout met een
 * andere k_def) geldt de vereenvoudiging w_fin = w_inst + k_def·w_qp van
 * 2.2.3(5) niet; 2.2.3(4) schrijft dan w_fin = w_inst + (w_qp,fin − w_qp)
 * voor. De kern kan w_qp,fin niet zelf bepalen — daar is een doorrekening
 * van het hele model voor nodig — dus levert de bouwer hem aan.
 *
 * `None` (weglaten) = de vereenvoudiging van 2.2.3(5), precies zoals
 * vóór dit veld. Een niet-eindig getal wordt geweigerd met reden.
 */
deflection_quasi_perm_fin_mm?: number, };
