// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayer } from "./CltLayer";

/**
 * De opbouw van een CLT-doorsnede: een plaatstrook van breedte `width_mm`
 * met lagen van boven (index 0) naar beneden.
 *
 * `deny_unknown_fields`, zie [`CltLayer`].
 */
export type CltLayup = { 
/**
 * Breedte van de beschouwde plaatstrook in mm (gebruikelijk 1000).
 */
width_mm: number, 
/**
 * Lagen van boven naar beneden.
 */
layers: Array<CltLayer>, };
