// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayerResult } from "./CltLayerResult";

/**
 * De uitgewerkte opbouw: stijfheid, zwaartelijn en de lagen.
 */
export type CltLayupResult = { width_mm: number, height_mm: number, 
/**
 * Zwaartelijn vanaf de bovenkant (mm).
 */
z0_mm: number, 
/**
 * (EI)_ef in kNm².
 */
ei_ef_knm2: number, 
/**
 * (EA)_ef in kN.
 */
ea_ef_kn: number, 
/**
 * Netto traagheidsmoment (EI)_ef/E_ref in mm⁴ — hulpgrootheid.
 */
i_ef_net_mm4: number, 
/**
 * Slankheid L/h — indicatie voor de geldigheid van de starre verbinding.
 */
slenderness: number, layers: Array<CltLayerResult>, 
/**
 * 1-gebaseerde index van de maatgevende laag; `None` zonder toetsen.
 */
governing_layer: number | null, };
