// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CltLayerOrientation } from "./CltLayerOrientation";

/**
 * Uitkomst per laag — de regel in de tabel "toetsing per lamel".
 */
export type CltLayerResult = { 
/**
 * 1 = bovenste laag.
 */
index: number, thickness_mm: number, orientation: CltLayerOrientation, strength_class: string, 
/**
 * Boven- en onderkant vanaf de bovenkant van de plaat (mm).
 */
z_top_mm: number, z_bot_mm: number, 
/**
 * E in de spanrichting (N/mm²); 0 voor dwarslagen.
 */
e_mpa: number, 
/**
 * Buigspanning aan boven- en onderkant van de laag (N/mm², trek +).
 */
sigma_top_mpa: number, sigma_bot_mpa: number, 
/**
 * Grootste schuifspanning in de laag (N/mm²); voor een dwarslaag de
 * rolschuifspanning.
 */
tau_max_mpa: number, 
/**
 * Rekenwaarden van de laag (N/mm²); voor dwarslagen 0 (niet getoetst).
 */
f_md_mpa: number, f_vd_mpa: number, 
/**
 * Unity checks; `None` voor dwarslagen (geen toets).
 */
uc_bending: number | null, uc_shear: number | null, 
/**
 * Deze laag bevat de maatgevende toets van de staaf.
 */
governing: boolean, 
/**
 * Id's van de toetsen van deze laag in `checks`.
 */
check_ids: Array<string>, };
