// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vezelrichting van een laag ten opzichte van de spanrichting van de staaf.
 */
export type CltLayerOrientation = "Longitudinal" | "Transverse";
