// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadDurationClass } from "./LoadDurationClass";

/**
 * De belastingduurklasse van één UGT-combinatie, zoals de invoerbouwer haar
 * uit de belastinggevallen afleidde.
 *
 * `deny_unknown_fields` om dezelfde reden als [`crate::TimberBeamCheckInput`]:
 * een tikfout in `load_duration` zou anders stil op de terugval vallen.
 */
export type CombinationLoadDuration = { 
/**
 * Het id van de UGT-combinatie, gelijk aan `ForcePoint::combination_id`.
 */
combination_id: number, 
/**
 * De kortste belastingsduur in deze combinatie (3.1.3(2)).
 */
load_duration: LoadDurationClass, 
/**
 * Waarop de klasse berust, leesbaar voor het rapport — bijvoorbeeld
 * "kortste: geval 4 Wind (W), kort (NB tabel 2.2: sneeuw en wind)".
 * Weglaten mag; het rapport noemt dan alleen de klasse.
 */
basis?: string, };
