// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadDurationClass } from "./LoadDurationClass";

/**
 * k_mod van één belastingduurklasse, met de combinaties die erbij horen.
 */
export type KmodPerLoadDuration = { load_duration: LoadDurationClass, 
/**
 * k_mod uit tabel 3.1 voor deze klasse en de klimaatklasse van de staaf.
 */
k_mod: number, 
/**
 * De UGT-combinaties in deze klasse, oplopend.
 */
combination_ids: Array<number>, 
/**
 * Per combinatie de basis van de klasse ("combinatie 4: kortste: …").
 */
bases: Array<string>, };
