// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Belastingduurklasse volgens §2.3.1.2.
 */
export type LoadDurationClass = "Permanent" | "LongTerm" | "MediumTerm" | "ShortTerm" | "Instantaneous";
