// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Belastinggeval voor de effectieve kiplengte (tabel 6.1).
 */
export type LtbLoadCase = "ConstantMoment" | "UniformLoad" | "ConcentratedMidspan" | "CantileverUniform" | "CantileverConcentratedEnd";
