// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aangrijpingspunt van de belasting t.o.v. het zwaartepunt (tabel 6.1,
 * voetnoot): drukzijde → l_ef + 2h; trekzijde → l_ef − 0,5h.
 */
export type LtbLoadPosition = "CentreOfGravity" | "CompressionEdge" | "TensionEdge";
