// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Klimaatklasse (service class) volgens §2.3.1.3.
 */
export type ServiceClass = "Sc1" | "Sc2" | "Sc3";
