// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CombinationLoadDuration } from "./CombinationLoadDuration";
import type { CustomSection } from "../steel/CustomSection";
import type { ForcePoint } from "../steel/ForcePoint";
import type { LateralBracing } from "../steel/LateralBracing";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { LtbLoadCase } from "./LtbLoadCase";
import type { LtbLoadPosition } from "./LtbLoadPosition";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { ServiceClass } from "./ServiceClass";

/**
 * Invoer voor één houten staaf (rechthoekige doorsnede b × h).
 *
 * `deny_unknown_fields`: een onbekend veld is een FOUT en geen ruis. Zeventien
 * velden hieronder hebben een standaardwaarde, en zonder deze regel viel een
 * tikfout in zo'n veldnaam stil terug op die standaard. Gemeten: `kcr` in
 * plaats van `k_cr` gaf dwarskracht-UC 1,066 in plaats van 1,591, en
 * `deflection_quasi_perm_m` liet de kruipterm k_def·w_qp van §7.2 wegvallen
 * (w_fin-UC 0,788 in plaats van 1,143) — beide zonder melding. Staal
 * (`BeamCheckInput`) en beton (`ConcreteBeamCheckInput`) weigerden al.
 */
export type TimberBeamCheckInput = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, beam_id: number, 
/**
 * Doorsnedebreedte b in mm. Bij een samengestelde doorsnede
 * (`custom_section`) de omhullende breedte; de toetsing rekent dan met
 * de grootheden uit die doorsnede en niet met b x h.
 */
width_mm: number, 
/**
 * Doorsnedehoogte h in mm (buiging om de sterke as).
 */
height_mm: number, 
/**
 * Een samengestelde doorsnede uit de profieleditor, als lamellen.
 *
 * WAAROM DIT VELD ER IS
 * Zonder dit veld kan alleen een rechthoek b x h worden getoetst, en dat
 * is niet alleen een gemis maar een gevaar. Wie een samengestelde ligger
 * (flenzen 1000 x 40, lijf 71 x 40, h = 120) als "1000x120" invoert,
 * krijgt bij de dwarskrachttoets van art. 6.1.7 een schuifspanning die
 * ruim een orde van grootte te laag is: die toets hoort met de breedte
 * van het LIJF en met de eigen S en I te rekenen, niet met b x h.
 *
 * De grootheden worden uit de lamellen berekend door `section-properties`
 * -- dezelfde motor die de profieleditor gebruikt -- inclusief de
 * maatgevende schuifvezel. Zit er geen lamel in (een catalogusdeel, of
 * alleen kant-en-klare eigenschappen), dan is er geen contour om een
 * breedte op te meten en weigert de toetsing met een melding.
 *
 * Weglaten = rechthoek b x h, precies zoals voorheen. `#[ts(optional)]`
 * zodat het veld ook in TypeScript weglaatbaar is en de bestaande
 * bouwers ongewijzigd blijven compileren -- dezelfde afspraak als bij
 * `BeamCheckInput::custom_section` van de staaltoetsing.
 */
custom_section?: CustomSection, 
/**
 * Sterkteklasse, bijv. "C24" (EN 338) of "GL28h" (EN 14080).
 */
strength_class: string, 
/**
 * Klimaatklasse (service class) §2.3.1.3.
 */
service_class: ServiceClass, 
/**
 * Belastingduurklasse (§2.3.1.2) voor de hele omhullende, en de TERUGVAL
 * voor een combinatie die niet in [`Self::load_duration_per_combination`]
 * staat.
 *
 * LET OP: zonder die lijst geldt deze ene klasse voor ALLE
 * UGT-combinaties. §3.1.3(2) wil de kortste belastingsduur PER
 * combinatie; met één klasse wordt de combinatie met alleen de blijvende
 * belasting dus niet met k_mod "blijvend" getoetst.
 */
load_duration: LoadDurationClass, 
/**
 * De belastingduurklasse per UGT-combinatie (§3.1.3(2)).
 *
 * Gevuld: de kern groepeert de omhullende per klasse, toetst elke klasse
 * met haar eigen k_mod en neemt per toets de hoogste unity check. Leeg
 * (of weggelaten): het gedrag van vóór dit veld, met `load_duration` voor
 * alles. Zie `crate::belastingduur`.
 */
load_duration_per_combination?: Array<CombinationLoadDuration>, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N drukt negatief.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Kniklengte om de sterke y-as (m) — knik IN het vlak van het model.
 *
 * `0` of weglaten = niet opgegeven: de kern houdt de staaflengte aan en
 * zegt dat in de afleiding ("staaflengte (terugval)"). Negatief of niet
 * eindig wordt genegeerd mét een kanttekening.
 */
buckling_length_y_m: number, 
/**
 * Kniklengte om de zwakke z-as (m) — knik UIT het vlak van het model.
 *
 * `0` of weglaten = niet opgegeven. De kern leidt L_cr,z dan af uit
 * [`Self::lateral_bracing`], maar alleen op plaatsen waar een steun aan
 * de boven- ÉN aan de onderrand zit; anders geldt de staaflengte. De
 * gebruikte waarde en haar herkomst staan in de kolomtoets en in de
 * drukterm van de kiptoets.
 */
buckling_length_z_m: number, 
/**
 * Zijdelingse steunen als fracties van de staaflengte, per rand — dezelfde
 * vorm als bij staal (`top_flange_positions` = bovenrand,
 * `bottom_flange_positions` = onderrand).
 *
 * ALLEEN voor de kniklengte om de z-as. De kiptoets van art. 6.3.3 rekent
 * met zijn eigen [`Self::ltb_segment_length_m`] en leidt niets uit deze
 * posities af; dat besluit is bewust en blijft staan (zie de toelichting
 * bij dat veld in de invoerbouwer).
 *
 * Weglaten = geen steunen, dus geen afleiding.
 */
lateral_bracing?: LateralBracing, 
/**
 * Kipsteunafstand (m) voor tabel 6.1; 0 → staaflengte.
 */
ltb_segment_length_m: number, 
/**
 * Belastinggeval voor l_ef (tabel 6.1).
 */
ltb_load_case: LtbLoadCase, 
/**
 * Aangrijpingspunt van de belasting (tabel 6.1, voetnoot).
 */
ltb_load_position: LtbLoadPosition, 
/**
 * Expliciete effectieve kiplengte in m; 0 → berekenen via tabel 6.1.
 */
ltb_effective_length_override_m: number, 
/**
 * Kiptoets §6.3.3 uitvoeren. `false` betekent: de gedrukte rand is over
 * de volle lengte zijdelings gesteund en de opleggingen zijn torsievast,
 * zodat k_crit = 1,0 (art. 6.3.3(5)). De toets wordt dan niet stil
 * weggelaten maar als `NotApplicable` met die reden in het resultaat
 * gezet. De referentie-uitwerking voert 6.3.3 alleen voor de ligger uit,
 * niet voor de kolommen.
 */
perform_ltb_check: boolean, 
/**
 * Scheurfactor k_cr voor dwarskracht (6.13a), bereik (0, 1]. 1,0 is de
 * waarde van NEN-EN 1995-1-1/NB bij 6.1.7 voor een prismatische
 * doorsnede en de standaard; de in 6.1.7(2) aanbevolen waarde is 0,67.
 * Alleen bij een rechthoek gelezen; bij een samengestelde doorsnede
 * bepaalt de kern k_cr zelf (`shear::k_cr_nb`).
 */
k_cr: number, 
/**
 * Lastverdelend systeem aanwezig → k_sys = 1,1 (§6.6).
 */
load_sharing: boolean, 
/**
 * Zakking onder de karakteristieke BGT-combinatie (mm, negatief = omlaag).
 */
deflection_inst_mm: number, 
/**
 * Zakking onder de quasi-blijvende BGT-combinatie (mm).
 */
deflection_quasi_perm_mm: number, 
/**
 * Zakking onder de blijvende BGT-combinatie (mm).
 */
deflection_permanent_mm: number, 
/**
 * Noemer voor w_fin (L/n), NB-standaard 250.
 */
deflection_limit_fin: number, 
/**
 * Noemer voor w_add (L/n), NB-standaard 333.
 */
deflection_limit_add: number, 
/**
 * Vrije toelichtingen bij de doorbuigingstoets, die letterlijk in de
 * `notes` van de w_fin-regel van het rapport belanden.
 *
 * Waarom dit bestaat: `deflection_quasi_perm_mm` is een kaal getal, en de
 * kern kan niet zien uit welke belastingscombinatie het komt. De bouwer
 * die de invoer samenstelt weet dat wél — of hij weet juist dat hij de
 * quasi-blijvende combinatie NIET heeft kunnen vinden en op de volle last
 * is teruggevallen. Zonder dit kanaal zou zo'n terugval onzichtbaar zijn,
 * en een onzichtbare aanname is geen aanname maar een fout in wording.
 */
deflection_notes: Array<string>, 
/**
 * Langeduurzakking w_qp,fin (mm, met teken): de zakking onder de
 * quasi-blijvende BGT-combinatie, berekend met de EINDSTIJFHEID
 * E_mean,fin = E_mean/(1 + k_def) van het hout (EN 1995-1-1 2.3.2.2(1),
 * uitdrukking 2.7) en de langeduurstijfheid van de andere delen.
 *
 * Waarom dit bestaat: in een statisch onbepaalde constructie met delen
 * van verschillend kruipgedrag (hout naast staal, beton of hout met een
 * andere k_def) geldt de vereenvoudiging w_fin = w_inst + k_def·w_qp van
 * 2.2.3(5) niet; 2.2.3(4) schrijft dan w_fin = w_inst + (w_qp,fin − w_qp)
 * voor. De kern kan w_qp,fin niet zelf bepalen — daar is een doorrekening
 * van het hele model voor nodig — dus levert de bouwer hem aan.
 *
 * `None` (weglaten) = de vereenvoudiging van 2.2.3(5), precies zoals
 * vóór dit veld. Een niet-eindig getal wordt geweigerd met reden.
 */
deflection_quasi_perm_fin_mm?: number, 
/**
 * Toelichtingen bij de STAAF ALS GEHEEL, letterlijk bij de kolomtoets
 * (art. 6.3.2), de kiptoets (art. 6.3.3) en de eindzakking gezet; rekenen
 * nergens mee. De bouwer zet hier wat hij van de staaf weet en de kern
 * niet: dat een door tussenknopen geknipte staaf als één doorgaande lijn
 * is getoetst, over welke lengte, en welke tussenknopen niet als steun
 * tellen. `None` of leeg = niets te melden.
 */
staaf_notities?: Array<string>, 
/**
 * Breedte b aan het EIND van de staaf (x = L) van een VERLOPENDE staaf;
 * [`Self::width_mm`] is dan de breedte aan het begin (x = 0).
 *
 * Samen met [`Self::height_end_mm`]: ontbreken ze allebei (of zijn ze
 * gelijk aan begin), dan is de staaf prismatisch en verandert er niets
 * aan de bestaande toetsing, tot op het laatste getal. Staat er één van
 * beide, dan houdt de andere maat zijn beginwaarde.
 *
 * De KERN bepaalt per krachtpunt de plaatselijke rechthoek b(x) × h(x),
 * toetst elke doorsnedetoets van §6.1 daarop — met k_h van §3.2(3)/3.3(3)
 * uit de PLAATSELIJKE hoogte — en rekent de stabiliteitstoetsen van
 * §6.3.2 en §6.3.3 veilig-zijdig met de kleinste doorsnede in het veld.
 * Zie `crate::verlopend`.
 *
 * Een samengestelde doorsnede (`custom_section`) kan niet verlopen: dan
 * wordt geweigerd met reden.
 */
width_end_mm?: number, 
/**
 * Hoogte h aan het EIND van de staaf (x = L); zie [`Self::width_end_mm`].
 *
 * Dit is de maat waar het bij een afgezaagde balklaag om gaat: de
 * rekenhoogte verloopt over de overspanning, en k_h verloopt mee.
 */
height_end_mm?: number, };
