// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { KmodPerLoadDuration } from "./KmodPerLoadDuration";
import type { LoadDurationClass } from "./LoadDurationClass";
import type { NamedCheck } from "../steel/NamedCheck";
import type { ServiceClass } from "./ServiceClass";
import type { VerloopRapport } from "../steel/VerloopRapport";

/**
 * Volledig toetsresultaat van één houten staaf.
 */
export type TimberBeamCheckResult = { beam_id: number, 
/**
 * Doorsnedenaam, bijv. "96 x 450".
 */
section_name: string, 
/**
 * Sterkteklasse, bijv. "C24".
 */
strength_class: string, service_class: ServiceClass, 
/**
 * Zonder belastingduur per combinatie: de klasse uit de invoer. Met die
 * lijst: de klasse van de maatgevende toets die van k_mod afhangt (de
 * doorbuiging hangt er niet van af en telt hier niet mee).
 */
load_duration: LoadDurationClass, checks: Array<NamedCheck>, uc_max: number, status: CheckStatus, governing_check_id: string, 
/**
 * k_mod per belastingduurklasse met de combinaties erin (§3.1.3(2)).
 * Leeg als de invoer geen belastingduur per combinatie meegaf.
 */
k_mod_per_load_duration?: Array<KmodPerLoadDuration>, 
/**
 * De combinatie van het maatgevende krachtpunt van de zwaarste toets die
 * van k_mod afhangt. `None` zonder belastingduur per combinatie, of als
 * geen enkele sterktetoets een unity check groter dan nul had.
 */
governing_combination_id?: number, 
/**
 * Alleen bij een VERLOPENDE staaf (`width_end_mm`/`height_end_mm` in de
 * invoer): de zes toetsdoorsneden, het maatgevende punt en de doorsneden
 * waarmee de stabiliteitstoetsen zijn gerekend. Zelfde vorm als bij staal
 * — het rapport kent voor het verloop maar één weergave. Bij hout blijven
 * `tw_mm`/`tf_mm` en `klasse` leeg. Afwezig bij een prismatische staaf,
 * en dan ook niet geserialiseerd.
 */
verloop?: VerloopRapport, };
