// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineEnd } from "./LineEnd";

/**
 * Eén doorgaande liggerlijn zoals figuur 5.2 hem tekent: de overspanningen op
 * volgorde plus de twee uiteinden. Tussen twee opeenvolgende overspanningen
 * zit per definitie een tussensteunpunt.
 *
 * De lengtemaat is mm; de coördinaat x loopt vanaf het uiteinde `start`.
 */
export type BeamLine = { 
/**
 * Overspanningen in mm, op volgorde van `start` naar `end`.
 */
spans_mm: Array<number>, 
/**
 * Wat er aan het begin van de lijn zit (x = 0).
 */
start: LineEnd, 
/**
 * Wat er aan het eind van de lijn zit (x = Σ spans_mm).
 */
end: LineEnd, };
