// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeffPart } from "./BeffPart";

/**
 * De meewerkende flensbreedte bij één l₀, met de hele afleiding erbij.
 */
export type BeffAtL0 = { 
/**
 * De gebruikte afstand tussen de momentnulpunten, mm.
 */
l0_mm: number, 
/**
 * Σ b_eff,i + b_w, begrensd op b (5.7), mm.
 */
b_eff_mm: number, 
/**
 * De totale beschikbare breedte b = b_w + Σ b_i (figuur 5.3), mm.
 */
b_mm: number, 
/**
 * Per uitkragend flensdeel de afleiding van b_eff,i.
 */
parts: Array<BeffPart>, 
/**
 * Heeft de bovengrens b van (5.7) ingegrepen? Zie [`BeffZone`].
 */
limited_by_b: boolean, };
