// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waarom er geen b_eff is. Elke variant draagt zijn eigen reden; er komt
 * nooit een getal terug dat op een aanname berust.
 */
export type BeffError = "NoSpans" | { "NonPositiveSpan": { index: number, value_mm: number, } } | "BothEndsFree" | "CantileverWithoutAdjacentSpan" | { "CantileverTooLong": { index: number, cantilever_mm: number, adjacent_mm: number, } } | { "SpanRatioOutOfRange": { first_index: number, first_mm: number, second_mm: number, ratio: number, } } | { "NonPositiveWeb": { b_w_mm: number, } } | { "NegativeFlange": { index: number, value_mm: number, } } | { "TooManyFlanges": { count: number, } };
