// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeffZone } from "./BeffZone";

/**
 * De meewerkende flensbreedte over de hele liggerlijn, per gebied.
 */
export type BeffDistribution = { 
/**
 * De gebieden op volgorde; ze sluiten aan en beslaan samen de hele lijn.
 */
zones: Array<BeffZone>, 
/**
 * Σ overspanningen, mm.
 */
total_length_mm: number, 
/**
 * Keuzes en aannamen die de uitkomst raken. Leeg betekent: figuur 5.2 is
 * letterlijk toegepast.
 */
notes: Array<string>, };
