// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeffBound } from "./BeffBound";

/**
 * b_eff,i van één uitkragend flensdeel, met alle drie de kandidaten erbij
 * zodat het rapport kan laten zien welke won.
 */
export type BeffPart = { 
/**
 * Het uitkragende flensdeel b_i, mm.
 */
b_i_mm: number, 
/**
 * 0,2·b_i + 0,1·l₀ (5.7a, eerste lid), mm.
 */
formula_mm: number, 
/**
 * 0,2·l₀ (5.7a, tweede lid), mm.
 */
cap_l0_mm: number, 
/**
 * De uitkomst: min van de drie, mm.
 */
b_eff_i_mm: number, governing: BeffBound, };
