// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeffPart } from "./BeffPart";
import type { L0Zone } from "./L0Zone";

/**
 * Eén gebied mét zijn meewerkende flensbreedte.
 */
export type BeffZone = { zone: L0Zone, 
/**
 * Σ b_eff,i + b_w, begrensd op b (5.7), mm.
 */
b_eff_mm: number, 
/**
 * De totale beschikbare breedte b = b_w + Σ b_i (figuur 5.3), mm.
 */
b_mm: number, 
/**
 * Per uitkragend flensdeel de afleiding van b_eff,i.
 */
parts: Array<BeffPart>, 
/**
 * Heeft de bovengrens b van (5.7) ingegrepen? Met (5.7b) toegepast kan
 * dat niet meer gebeuren — Σb_eff,i ≤ Σb_i — dus dit hoort altijd false
 * te zijn. Het veld staat er omdat (5.7) die grens wél noemt en een stille
 * aanname hier niet past.
 */
limited_by_b: boolean, };
