// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welke van de drie grenzen van (5.7a)/(5.7b) een b_eff,i bepaalde.
 */
export type BeffBound = "Formula" | "CapL0" | "CapBi";
