// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deelstap } from "../steel/Deelstap";

/**
 * Het gebied dat werkelijk is aangehouden, met de afleiding uitgeschreven.
 */
export type BeffApplied = { 
/**
 * Index in [`BeffDistribution::zones`] van het gebied waarin `x_mm` valt.
 */
zone_index: number, 
/**
 * De plaats die is aangehouden, mm vanaf het lijnbegin — onveranderd
 * terug, zodat het rapport hem kan noemen.
 */
x_mm: number, 
/**
 * De meewerkende flensbreedte van dat gebied, mm.
 */
b_eff_mm: number, 
/**
 * De afleiding, stap voor stap. Zie [`crate::beff_deelstappen`].
 */
deelstappen: Array<Deelstap>, };
