// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReinforcementCage } from "./ReinforcementCage";
import type { ReinforcementZones } from "./ReinforcementZones";

/**
 * De zone-indeling van één betonstaaf, zoals de toetsing hem gekregen heeft.
 *
 * Spiegel van de drie velden van `ConcreteBeamCheckInput` die hierover gaan
 * (`cage`, `reinforcement_zones` en `length_m`), plus het staafnummer. Bewust
 * niet het hele invoertype: dat draagt ook de omhullende, de milieuklasse en
 * de kolomgegevens, en die zouden dan meereizen door een rapportinvoer die er
 * niets mee doet.
 *
 * De lengte staat er in MILLIMETER in, want de zonegrenzen staan dat ook; een
 * tabel waarin de ene kolom meters en de andere millimeters is, leest verkeerd.
 */
export type BetonStaafZones = { beam_id: number, 
/**
 * Staaflengte, mm — waar de laatste zone uiterlijk ophoudt.
 */
lengte_mm: number, 
/**
 * De korf van de staaf: wat geldt waar de zonelijsten niets zeggen.
 */
korf: ReinforcementCage, 
/**
 * De zone-indeling zoals de kern hem kreeg. Beide lijsten leeg = geen
 * indeling, en dan blijft dit blok weg.
 */
zones: ReinforcementZones, };
