// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { ReinforcementCage } from "./ReinforcementCage";

/**
 * De doorsnede en de wapeningskorf van één betonstaaf — wat de figuren nodig
 * hebben en wat het toetsresultaat niet draagt. Spiegel van
 * `BetonSegmentStaaf` in `design-mockup/src/lib/betonStijfheid.ts`, beperkt
 * tot wat er getekend wordt.
 */
export type BetonStaafDoorsnede = { beam_id: number, 
/**
 * De doorsnede zoals de kern hem heeft gekregen — bij een T of een L dus
 * mét de meewerkende flensbreedte die er werkelijk in zat.
 */
doorsnede: ConcreteSectionInput, korf: ReinforcementCage, };
