// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BetonStaafDoorsnede } from "./BetonStaafDoorsnede";
import type { OvergeslagenStaaf } from "./OvergeslagenStaaf";
import type { StijfheidCombinatie } from "./StijfheidCombinatie";

/**
 * Het hele spoor van één rekengang — spiegel van `BetonStijfheidState`.
 */
export type BetonStijfheidSpoor = { 
/**
 * De gewenste segmentlengte waarmee gerekend is, mm.
 */
segment_lengte_mm: number, 
/**
 * Per combinatie het spoor; leeg zolang er niet fysisch gerekend is.
 */
combinaties: Array<StijfheidCombinatie>, 
/**
 * Betonstaven die niet meerekenden, met de reden.
 */
overgeslagen: Array<OvergeslagenStaaf>, 
/**
 * De doorsnede en korf per meerekenende staaf — alleen voor de figuren.
 */
staafdoorsneden: Array<BetonStaafDoorsnede>, };
