// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waar in de kolom bevindt de beschouwde doorsnede zich? §9.5.3(4).
 */
export type Beugelzone = "Regulier" | "BijBalkOfPlaat" | "BijOverlappingslas";
