// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De cementklasse van §3.1.2(6), die via α in (B.9) de ouderdom t₀ aanpast.
 */
export type CementClass = "S" | "N" | "R";
