// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waarom C zijn waarde heeft — dit is de plek waar geschoord/ongeschoord
 * rechtstreeks in het getal doorwerkt.
 */
export type Cgrondslag = { "UitEindmomenten": { m01_knm: number, m02_knm: number, r_m: number, } } | "GeschoordUitImperfectiesOfDwarsbelasting" | "OngeschoordInHetAlgemeen" | "Onbekend";
