// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De vorm van de doorsnede — het **etiket**, voor het rapport en de
 * meldingen. De rekengang vertakt hier niet op; die kijkt naar
 * [`ConcreteSection::bands`].
 *
 * Dit etiket is óók het eerste veld van [`ConcreteSectionInput`] en reist
 * daarmee over alle drie de wegen mee; vandaar de ts-export.
 */
export type ConcreteShape = "Rectangle" | "Tee" | "Ell";
