// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { CoverGovernedBy } from "./CoverGovernedBy";
import type { CoverSide } from "./CoverSide";
import type { ExposureClass } from "./ExposureClass";
import type { StructuralClass } from "./StructuralClass";

/**
 * Het antwoord: de hele keten van (4.2) en (4.1), met de vindplaats van elke
 * term, plus het oordeel over de opgegeven dekking.
 */
export type ConcreteCoverResponse = { beam_id: number, 
/**
 * De zijde uit het verzoek, onveranderd terug; `None` als er geen is
 * benoemd.
 */
side: CoverSide | null, exposure_class: ExposureClass, structural_class: StructuralClass, 
/**
 * De kolomaanduiding uit tabel 4.4N, of `None` bij XF/XA.
 */
cover_column: string | null, 
/**
 * c_min,dur uit tabel 4.4N; `None` bij XF/XA — zie de moduletekst.
 */
c_min_dur_mm: number | null, 
/**
 * c_min,b uit tabel 4.2: de maatgevende staafdiameter.
 */
c_min_b_mm: number, 
/**
 * Welke staaf die eis stelde — de beugel of de hoofdwapening.
 */
c_min_b_source: string, delta_c_dur_gamma_mm: number, delta_c_dur_st_mm: number, delta_c_dur_add_mm: number, 
/**
 * De duurzaamheidsterm van (4.2): c_min,dur + Δc_dur,γ − Δc_dur,st −
 * Δc_dur,add. `None` bij XF/XA.
 */
durability_term_mm: number | null, 
/**
 * c_min volgens (4.2).
 */
c_min_mm: number, governed_by: CoverGovernedBy, delta_c_dev_mm: number, 
/**
 * De vereiste nominale dekking volgens (4.1).
 */
c_nom_required_mm: number, 
/**
 * De opgegeven nominale dekking, onveranderd terug.
 */
c_nom_provided_mm: number, 
/**
 * c_nom,vereist / c_nom,aanwezig. Groter dan 1 = te weinig dekking.
 */
unity_check: number, status: CheckStatus, 
/**
 * Wat er bij deze uitkomst hoort te worden verteld — de NB-bepalingen die
 * zijn gebruikt en de eisen die deze toets NIET dekt.
 */
notes: Array<string>, };
