// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteShape } from "./ConcreteShape";

/**
 * De doorsnede zoals de **invoer** hem beschrijft: een vorm met de maten die
 * bij die vorm horen.
 *
 * Dit is het buitenaanzicht van [`ConcreteSection`] — het type dat over het
 * Tauri-command, de toetsbrug en de MCP-server gaat. Waarom een apart type en
 * niet `ConcreteSection` zelf: die draagt de **banden**, en banden zijn een
 * rekenkundige afgeleide. Wie ze als invoer zou aanbieden, kan een reeks
 * stroken opgeven die geen rechthoek, geen T en geen L is; de vormen die deze
 * crate kent zijn er dan drie in naam en oneindig veel in werkelijkheid.
 *
 * # Verplichte en verboden maten
 *
 * `b_w_mm` en `h_f_mm` horen bij een flens: bij `Tee` en `Ell` zijn ze
 * verplicht, bij `Rectangle` moeten ze wegblijven. Een rechthoek mét
 * flensdikte is geen tikfout die stilzwijgend genegeerd mag worden — hij
 * betekent dat de aanroeper iets anders bedoelde dan hij opschreef, en
 * negeren zou een doorsnede opleveren die niemand heeft ingevoerd. Zie
 * [`Self::build`], de enige plaats waar dit type een `ConcreteSection` wordt.
 *
 * ```text
 *        Rectangle              Tee / Ell            Tee met flange_at_bottom
 *     ┌───── b ─────┐      ┌────── b ──────┐            ┌──┐
 *     │             │      └──┐  h_f    ┌──┘            │  │
 *     │             h         │         │  h            │  │  h
 *     │             │         │  b_w    │               │  │
 *     └─────────────┘         └─────────┘            ┌──┴──┴──┐  h_f
 * ```
 *
 * `b_mm` is bij een T en een L de **flensbreedte**, en die wordt verondersteld
 * de meewerkende b_eff van 5.3.2.1(3) te zijn — zie [`crate::beff`], die hem
 * afleidt, en [`ConcreteSection::assumptions`], die de aanname als tekst
 * meelevert.
 */
export type ConcreteSectionInput = { 
/**
 * De vorm. Bepaalt welke maten verplicht zijn en welke verboden.
 * Ontbreekt hij, dan is het een rechthoek.
 */
shape: ConcreteShape, 
/**
 * Grootste breedte in mm: b bij een rechthoek, de flensbreedte b_f bij
 * een T en een L.
 */
b_mm: number, 
/**
 * Totale hoogte h in mm (buiging om de sterke as).
 */
h_mm: number, 
/**
 * Lijfbreedte b_w in mm. Verplicht bij `Tee` en `Ell`; bij `Rectangle`
 * moet dit veld wegblijven.
 */
b_w_mm: number | null, 
/**
 * Flensdikte h_f in mm. Zelfde regel als `b_w_mm`.
 */
h_f_mm: number | null, 
/**
 * Ligt de flens aan de ONDERZIJDE — de omgekeerde T? Standaard `false`:
 * de flens ligt boven, zoals bij een ligger onder een vloer.
 *
 * De banden en [`ConcreteSection::mirrored`] dragen dit geval volledig;
 * deze vlag is de enige plaats waar het gekozen wordt. Bij `Rectangle`
 * heeft hij geen betekenis en moet hij `false` blijven.
 */
flange_at_bottom: boolean, };
