// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedCheck } from "../steel/NamedCheck";

/**
 * Antwoord op [`ConcreteColumnCheckRequest`].
 */
export type ConcreteColumnCheckResponse = { beam_id: number, section_name: string, 
/**
 * De toetsen in hetzelfde contract als de rest van de betontoetsing:
 * §5.8.3.1 (de poort), §5.8.4 (kruip) en de §9.5-eisen.
 */
checks: Array<NamedCheck>, 
/**
 * λ = l₀/i. `None` als §5.8 niet van toepassing was of niet kon.
 */
lambda?: number, 
/**
 * λ_lim = 20·A·B·C/√n.
 */
lambda_lim?: number, 
/**
 * l₀ in mm.
 */
l0_mm?: number, 
/**
 * λ < λ_lim: §5.8.3.1(1) staat toe de tweede-orde-effecten te
 * verwaarlozen. `None` = niet vastgesteld.
 */
tweede_orde_verwaarloosbaar?: boolean, 
/**
 * De effectieve kruipcoëfficiënt φ_ef uit (5.19), als hij te bepalen was.
 */
phi_ef?: number, 
/**
 * φ_ef om de z-as zoals in de algemene methode voor e₂ gebruikt: 0 als
 * §5.8.4(4) dat toestaat, anders (5.19) of — zonder quasi-blijvende
 * combinatie — φ(∞,t₀) als bovengrens. `None` = onbekend omdat φ(∞,t₀)
 * niet is opgegeven; moet e₂ om z worden meegenomen, dan zijn ook
 * `e_2_z_mm`, `m_edz_knm` en `interactie_5_39` `None` en zeggen de
 * toetsen waarom.
 */
phi_ef_z?: number, 
/**
 * λ_z = l₀,z/i_z om de z-as. `None` als de tweede as niet kon.
 */
lambda_z?: number, 
/**
 * λ_lim,z om de z-as.
 */
lambda_lim_z?: number, 
/**
 * l₀,z in mm.
 */
l0_z_mm?: number, 
/**
 * λ_z < λ_lim,z: e₂ om z mocht vervallen.
 */
tweede_orde_verwaarloosbaar_z?: boolean, 
/**
 * De imperfectie e_i = θ_i·l₀,z/2 om z, mm (§5.2).
 */
e_i_z_mm?: number, 
/**
 * Het tweede-orde-deel e₂ om z, mm; 0 als het mocht vervallen, `None` bij
 * instabiliteit om z.
 */
e_2_z_mm?: number, 
/**
 * M_Edz op de maatgevende snede, kNm — inclusief imperfectie, tweede orde
 * en de minimale excentriciteit van 6.1(4). Bij instabiliteit om z (geen
 * evenwicht; `e_2_z_mm` is dan `None`) het laatste moment waarvoor nog
 * een kromming is gezocht, en geen rekenwaarde — de toets zegt dat.
 */
m_edz_knm?: number, 
/**
 * M_Rdz op die snede, kNm.
 */
m_rdz_knm?: number, 
/**
 * De grootste som van (5.39), alleen als §5.8.9(4) haar vereiste.
 */
interactie_5_39?: number, };
