// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverSide } from "./CoverSide";
import type { ExposureClass } from "./ExposureClass";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { StructuralClass } from "./StructuralClass";

/**
 * Eén verzoek om de dekkingstoets, zoals het over het Tauri-command, de
 * toetsbrug en de MCP-server gaat.
 *
 * `deny_unknown_fields`: een tikfout in `stirrup_diameter_mm` zou anders
 * stilzwijgend 0 opleveren, en dan valt de aanhechtingseis terug op de
 * hoofdstaaf terwijl er wél een beugel zit.
 */
export type ConcreteCoverRequest = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, 
/**
 * Vrij te kiezen nummer; komt onveranderd terug. 0 als het niet om een
 * staaf uit een model gaat.
 */
beam_id: number, 
/**
 * Welk betonoppervlak dit verzoek betreft (4.4.1.1(1)P).
 *
 * `None` = niet benoemd; dan is het antwoord een dekkingstoets zonder
 * zijde, precies zoals hij vóór deze uitbreiding was. Het veld verandert
 * aan de berekening niets: het reist mee zodat het antwoord kan zeggen
 * wélke zijde is getoetst, want drie antwoorden naast elkaar zonder
 * opschrift zijn niet uit elkaar te houden.
 */
side?: CoverSide, 
/**
 * De milieuklasse van tabel 4.1 — die van de zijde in [`Self::side`], of
 * van het element als er geen zijde is benoemd.
 */
exposure_class: ExposureClass, 
/**
 * De constructieklasse. Blijft het veld weg, dan
 * [`standaard_constructieklasse`] van de bijlage — de NB-waarde voor 50 jaar.
 */
structural_class: StructuralClass | null, 
/**
 * De opgegeven nominale dekking c_nom, in mm — het getal dat de
 * constructeur invult en dat op de tekening komt (4.4.1.1(2)P).
 */
cover_mm: number, 
/**
 * Beugeldiameter in mm; 0 = geen beugel.
 */
stirrup_diameter_mm: number, 
/**
 * De grootste diameter van de hoofdwapening, in mm.
 *
 * Zowel de beugel als de hoofdstaaf tellen mee voor de aanhechtingseis:
 * de beugel ligt op c_nom van de rand, de hoofdstaaf op c_nom + Ø_beugel.
 * Zie [`concrete_cover_request`] voor de afweging.
 */
max_bar_diameter_mm: number, };
