// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteColumnInput } from "./ConcreteColumnInput";
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { DesignSituation } from "./DesignSituation";
import type { ForcePoint } from "../steel/ForcePoint";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { SteelBranch } from "./SteelBranch";

/**
 * Verzoek voor de LOSSE kolomtoets — dezelfde rekengang als in de volledige
 * staaftoetsing, zonder dat daar een hele toetsronde voor nodig is.
 *
 * Bedoeld voor het invoerscherm (λ en λ_lim terwijl je typt, zoals de
 * dekkingstoets van 4.4.1 dat al doet) en voor een client buiten de app.
 */
export type ConcreteColumnCheckRequest = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, 
/**
 * Staafnummer; komt onveranderd terug.
 */
beam_id: number, 
/**
 * De doorsnede: rechthoek, T of L.
 */
section: ConcreteSectionInput, concrete_class: string, reinforcement_grade: string, 
/**
 * Wapeningskorf. A_s is hier de SOM van de boven- en de onderrij; wat
 * daar in een kolom aan ontbreekt staat bij [`kolomtoetsen`].
 */
cage: ReinforcementCage, 
/**
 * Vrije lengte l tussen de eindaansluitingen, m (§5.8.3.2(3)).
 */
length_m: number, 
/**
 * De §5.8-gegevens.
 */
column: ConcreteColumnInput, 
/**
 * UGT-krachtsverloop langs de staaf; N drukt negatief. Uit deze reeks
 * komen de maatgevende drukkracht, het bijbehorende eerste-orde-moment en
 * de twee eindmomenten.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Krachtsverloop onder de QUASI-BLIJVENDE BGT-combinatie (NEN-EN 1990
 * uitdrukking (6.16)) — M₀Eqp uit (5.19). Leeg = niet meegestuurd.
 */
sls_quasi_permanent_envelope: Array<ForcePoint>, 
/**
 * UGT-krachtsverloop uit een EERSTE-ORDE-berekening, voor M₀Ed, M₀₁ en
 * M₀₂ (§5.8.3.1(1), (5.19)) wanneer `forces_envelope` tweede orde is.
 * `None` = `forces_envelope` is eerste orde. Zie hetzelfde veld in
 * `ConcreteBeamCheckInput`.
 */
first_order_envelope?: Array<ForcePoint>, design_situation: DesignSituation, steel_branch: SteelBranch, };
