// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Beugelzone } from "./Beugelzone";
import type { Kniklengtekeuze } from "./Kniklengtekeuze";
import type { Overlappingssituatie } from "./Overlappingssituatie";
import type { Schoring } from "./Schoring";

/**
 * De §5.8-gegevens van één staaf: het ontwerpbesluit, de kniklengte en de
 * kruip.
 *
 * # Waarom dit een BLOK is en geen losse velden
 *
 * Schoring zonder kniklengte levert geen λ, en een kniklengte zonder schoring
 * geen λ_lim: (5.15) tegenover (5.16) is een factor twee in l₀, en C = 0,7 is
 * voor een ongeschoord element VOORGESCHREVEN terwijl een geschoorde kolom
 * C > 1,7 mag halen. De twee horen bij elkaar, en een blok dat er is of er
 * niet is, maakt het onmogelijk om er één van in te vullen en de andere te
 * vergeten. Ontbreekt het blok, dan wordt §5.8 niet getoetst en staat de reden
 * in het rapport — er is geen aangenomen schoring en geen aangenomen l₀.
 *
 * # Geschoord is een ONTWERPBESLUIT
 *
 * §5.8.1 definieert het letterlijk als een aanname in de berekening en niet
 * als een eigenschap van de constructie. Een raamwerk mét windverband ziet er
 * in een 2D-model niet anders uit dan hetzelfde raamwerk zonder. Daarom is
 * [`Schoring`] hier verplicht zodra het blok bestaat, en wordt het nergens
 * afgeleid.
 *
 * # Twee assen
 *
 * `bracing` en `buckling_length` gelden voor de as waarin dit model rekent:
 * buiging om de y-as, in het vlak van het raamwerk. Een kolom heeft ook een
 * tweede as, en knikt daar even goed om uit — met de imperfectie van §5.2 en
 * het tweede-orde-effect in díe richting, ook als de raamwerkoplosser M_z = 0
 * levert. Daarom dragen `bracing_z` en `buckling_length_z` de schoring en de
 * kniklengte om de z-as: een EIGEN gegeven, want de schoring verschilt vaak
 * per richting (een kolom kan in het vlak geschoord zijn en er loodrecht op
 * niet). Blijven ze leeg, dan wordt de keuze van het rekenvlak overgenomen
 * en zegt de toets dat met zoveel woorden. `m0_edz_knm` is een extern
 * eerste-orde-moment om de z-as, nul als beginwaarde, zodat een ruimtelijk
 * model hem straks kan vullen zonder dat dit type verandert. De velden zijn
 * per as benoemd en niet als vaste lijst van twee: een derde grootheid
 * (wringing, een schuine as) past er later naast.
 */
export type ConcreteColumnInput = { 
/**
 * Geschoord of ongeschoord — het ontwerpbesluit van §5.8.1. Verplicht.
 */
bracing: Schoring, 
/**
 * Hoe l₀ wordt bepaald. Verplicht.
 */
buckling_length: Kniklengtekeuze, 
/**
 * Eindwaarde van de kruipcoëfficiënt φ(∞,t₀) volgens §3.1.4.
 *
 * `None` = niet opgegeven. Deze toets rekent §3.1.4 niet zelf uit: dat
 * vraagt de relatieve luchtvochtigheid, de fictieve dikte h₀, de
 * cementklasse en de ouderdom t₀ bij eerste belasting. De berekening
 * volgens bijlage B staat apart in `nen_en_1992_1_1::kruip`
 * (`concrete_creep_coefficient`); de app vult haar uitkomst hier in. Zonder φ(∞,t₀) blijft φ_ef onbekend en
 * staat §5.8.3.1(1) A = 0,7 toe; dat is GEEN veilige kant maar de waarde
 * bij φ_ef ≈ 2,14, en dat wordt gemeld. Om de z-as, waar deze toets e₂
 * zelf bepaalt, geeft de norm voor φ_ef geen standaardwaarde (§5.8.4(1)P,
 * §5.8.6(4)); telt e₂ daar mee, dan wordt het moment om z zonder φ(∞,t₀)
 * niet goedgekeurd. In de app vult de projectwaarde dit veld aan als de
 * staaf zelf geen waarde heeft (`lib/kruipcoefficient.ts`).
 */
phi_inf_t0?: number, 
/**
 * De zone waarin de kolomdoorsnede ligt, voor s_cl,tmax (§9.5.3(4)).
 *
 * `None` = niet opgegeven; dan komt s_cl,tmax als "niet uitgevoerd"
 * terug. Er wordt niet stilzwijgend [`Beugelzone::Regulier`] aangehouden:
 * dat is de tak ZONDER de reductiefactor 0,6 en dus de ruimste van de
 * twee.
 */
stirrup_zone?: Beugelzone, 
/**
 * Komen er overlappingslassen voor, en ligt deze doorsnede er ter plaatse
 * van? Bepaalt A_s,max (NB bij §9.5.2(3)).
 *
 * `None` = niet opgegeven; dan komt A_s,max als "niet uitgevoerd" terug.
 * [`Overlappingssituatie::GeenLassen`] geeft 0,08·A_c tegenover 0,04·A_c
 * buiten een las — een factor twee, en de ruimste tak. Aannemen mag dus
 * niet.
 */
lap_situation?: Overlappingssituatie, 
/**
 * Geschoord of ongeschoord om de Z-AS — het ontwerpbesluit van §5.8.1
 * voor de richting loodrecht op het rekenvlak.
 *
 * `None` = niet apart opgegeven; dan geldt `bracing` ook om z, en de
 * toets meldt dat. Dat is een terugval en geen afleiding: wie weet dat
 * de schoring per richting verschilt, vult dit veld in.
 */
bracing_z?: Schoring, 
/**
 * Hoe l₀ om de Z-AS wordt bepaald: dezelfde keuze als `buckling_length`
 * (een vakje van figuur 5.7, of l₀ zelf), maar voor de richting loodrecht
 * op het rekenvlak. Het vakje moet bij `bracing_z` passen.
 *
 * `None` = niet apart opgegeven; dan geldt `buckling_length` ook om z, en
 * de toets meldt dat.
 */
buckling_length_z?: Kniklengtekeuze, 
/**
 * Een EXTERN eerste-orde-moment om de z-as, kNm, constant over de staaf,
 * dat bij het M_z uit de omhullende wordt opgeteld.
 *
 * `None` = 0. Het veld bestaat omdat de vlakke raamwerkoplosser geen M_z
 * levert; een ruimtelijk model of een handberekening vult het. Het teken
 * doet er niet toe: de korf is symmetrisch om de hartlijn en de toets
 * rekent met de grootte.
 */
m0_edz_knm?: number, };
