// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteColumnInput } from "./ConcreteColumnInput";
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { DesignSituation } from "./DesignSituation";
import type { ExposureClass } from "./ExposureClass";
import type { ForcePoint } from "../steel/ForcePoint";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { ReinforcementZones } from "./ReinforcementZones";
import type { Staafstand } from "../steel/Staafstand";
import type { SteelBranch } from "./SteelBranch";
import type { StructuralClass } from "./StructuralClass";
import type { StructuralSystem } from "./StructuralSystem";

/**
 * Invoer voor één betonnen staaf: een doorsnede met een wapeningskorf.
 *
 * `deny_unknown_fields`: een tikfout in een veldnaam met `#[serde(default)]`
 * zou anders stilzwijgend de standaardwaarde opleveren.
 *
 * De doorsnede staat als één `section`-object in het verzoek en niet meer als
 * een losse breedte en hoogte. Dat is met opzet **geen** uitbreiding met
 * extra optionele velden naast de oude twee: dan zou een T te maken zijn door
 * alleen `h_f_mm` in te vullen en `shape` te vergeten, en zou de doorsnede
 * stilzwijgend een rechthoek blijven. Zie [`ConcreteSectionInput`].
 */
export type ConcreteBeamCheckInput = { 
/**
 * De nationale bijlage waarmee getoetst wordt.
 *
 * Zij bepaalt de nationaal bepaalde parameters van deze toetsing (zie de
 * crate `nationale-bijlage`). Een bijlage die deze uitgave niet kent, wordt
 * bij het lezen van de invoer GEWEIGERD met reden; er wordt nooit stil op
 * de Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` — en waarom dat hier geen stille keuze is: er is
 * precies één gevulde rij, dus "veld weggelaten" kan niet iets anders
 * betekenen dan die rij. Het houdt oude projectbestanden en oude
 * MCP-cliënten aan de praat. Zodra er een tweede rij gevuld is, MOET deze
 * regel weg; de test `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg`
 * in `nationale-bijlage` valt dan om en zegt dat.
 */
bijlage: NationaleBijlage, beam_id: number, 
/**
 * De doorsnede: rechthoek, T of L, met de maten die bij die vorm horen.
 */
section: ConcreteSectionInput, 
/**
 * Betonsterkteklasse, bijv. "C30/37" (tabel 3.1).
 */
concrete_class: string, 
/**
 * Wapeningsstaal, bijv. "B500B" (bijlage C).
 */
reinforcement_grade: string, 
/**
 * Wapeningskorf: dekking, beugel, boven- en onderwapening.
 *
 * Dit is de korf die geldt waar `reinforcement_zones` niets zegt — dus bij
 * lege zonelijsten over de hele staaf.
 */
cage: ReinforcementCage, 
/**
 * De wapening die LANGS de staaf verandert: welke staaflaag van waar tot
 * waar loopt (§9.2.1.3) en waar de beugels dichter staan (§9.2.2).
 *
 * Dit veld staat NAAST `cage` en niet erin. `ReinforcementCage` is `Copy`
 * en beschrijft één doorsnede; hij wordt op tientallen plaatsen
 * doorgegeven waar alleen die doorsnede nodig is (buiging, M-N-κ,
 * scheurwijdte, de twee tekenkanten). Een lengte-as in dat type zou zich
 * door al die signaturen heen planten en het bovendien zijn `Copy` kosten.
 * Zie [`ReinforcementZones`] voor waarom het twee gescheiden lijsten zijn
 * en niet één.
 *
 * **LEEG (of weggelaten) = het gedrag van vóór dit veld**: dan geldt
 * `cage` onveranderd over de hele staaf. Dat is geen bijkomstigheid maar
 * de voorwaarde waaronder dit veld erbij mocht: geen enkele bestaande
 * toets verandert erdoor.
 */
reinforcement_zones: ReinforcementZones, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Krachtsverloop (envelop) langs de staaf; N drukt negatief.
 */
forces_envelope: Array<ForcePoint>, 
/**
 * Aantal stroken waarin de doorsnede voor de integratie van de
 * betonspanning wordt verdeeld ("in hoeveel delen opknippen").
 */
n_strips: number, 
/**
 * Bovenste tak van het staaldiagram (3.2.7(2)); standaard horizontaal.
 */
steel_branch: SteelBranch, 
/**
 * Ontwerpsituatie voor tabel 2.1N; standaard blijvend en tijdelijk.
 */
design_situation: DesignSituation, 
/**
 * Minimale excentriciteit e₀ = max(h/30; 20 mm) toepassen bij druk (6.1(4)).
 */
apply_min_eccentricity: boolean, 
/**
 * Krachtsverloop onder de **frequente** BGT-combinatie, NEN-EN 1990
 * uitdrukking (6.15).
 *
 * De nationale bijlage bij 7.3.1(5) vervangt tabel 7.1N door een tabel
 * waarvan alle drie de kolommen "Frequente belastingscombinatie" heten,
 * waar de EN-tekst de quasi-blijvende combinatie noemt. §7.3 vraagt de
 * staalspanning σ_s in de **gescheurde** doorsnede onder díe combinatie;
 * die is uit de UGT-envelop niet af te leiden. Is deze lijst leeg, dan
 * komen de scheurtoetsen als "niet uitgevoerd" in het rapport, met de
 * reden — er wordt geen UGT-spanning voor in de plaats gezet.
 */
sls_frequent_envelope: Array<ForcePoint>, 
/**
 * Milieuklasse van dit ELEMENT (tabel 4.1) — de ingang van tabel 7.1N
 * voor w_max. `None` = niet opgegeven; §7.3 kan dan niet.
 *
 * # Dit is de klasse van het element, niet van één oppervlak
 *
 * 4.4.1.1(1)P meet de betondekking tot "het dichtstbijzijnde
 * betonoppervlak", en een balk heeft er vier. Een klasse PER ZIJDE staat
 * daarom bij de korf: [`ReinforcementCage::cover_top`],
 * `cover_bottom` en `cover_sides` dragen elk een eigen milieuklasse en een
 * eigen dekking. Dit veld is wat daar de terugval voor is — zie
 * [`Self::exposure_at`] — en tegelijk de klasse waarmee §7.3 werkt.
 *
 * Waarom §7.3 het ELEMENT neemt en niet de trekzijde: tabel 7.1N (in de
 * versie van de nationale bijlage bij 7.3.1(5)) geeft w_max per
 * milieuklasse, en de scheurwijdte wordt aan de trekzijde beoordeeld. Wie
 * die koppeling per zijde wil leggen, moet 7.3 de zijde van het
 * maatgevende momentteken laten kiezen; dat gebeurt hier nog niet, en de
 * scheurtoets houdt dus deze ene klasse aan.
 */
exposure_class?: ExposureClass, 
/**
 * Constructieklasse S1…S6 van dit ELEMENT (4.4.1.2(5)).
 *
 * `None` = de waarde van de nationale bijlage: "Als constructieklasse voor
 * een ontwerplevensduur van 50 jaar moet S4 zijn aangehouden." Anders dan
 * bij de milieuklasse is er hier dus wél een voorgeschreven waarde, en zij
 * staat met zoveel woorden in de norm.
 *
 * De klasse staat NIET per zijde. De vijf criteria van de door de
 * nationale bijlage vervangen tabel 4.3N — ontwerplevensduur 100 jaar,
 * ontwerplevensduur 75 jaar, sterkteklasse, element met plaatgeometrie en
 * gewaarborgde kwaliteitsbeheersing — zijn alle vijf een eigenschap van
 * het element; zie [`StructuralClass`] voor de uitwerking en de ene
 * nuance daarbij.
 */
structural_class?: StructuralClass, 
/**
 * Grootste nominale korrelafmeting d_g in mm, voor §8.2(2) en §9.2(1)e.
 *
 * `None` = niet opgegeven. De norm kent er **geen** aanbevolen waarde
 * voor — d_g hoort bij de betonspecificatie — dus er wordt er ook geen
 * aangenomen; zie [`nen_en_1992_1_1::detaillering::vrije_staafafstand_8_2`].
 */
aggregate_size_mm?: number, 
/**
 * De regel uit tabel 7.4N voor de slankheidstoets van 7.4.2.
 *
 * `None` = niet opgegeven. Dit is niet uit een raamwerkmodel af te
 * leiden: of een staaf een eindveld, een tussenveld of een uitkraging is
 * hangt van de constructie af en niet van de staaf. Zonder deze keuze
 * blijft 7.4.2 ongetoetst, met de reden in het rapport.
 */
structural_system?: StructuralSystem, 
/**
 * Werkelijke hart-op-hartafstand van de trekstaven in mm, voor (7.11) en
 * tabel 7.3N.
 *
 * `None` = niet opgegeven; de orchestrator leidt hem dan af uit de korf
 * (zuivere meetkunde, één rij, gelijkmatig verdeeld tussen de
 * beugelbenen) en meldt dat in de afleiding.
 */
bar_spacing_mm?: number, 
/**
 * Krachtsverloop onder de **quasi-blijvende** BGT-combinatie, NEN-EN 1990
 * uitdrukking (6.16).
 *
 * Dit is de DERDE omhullende van dit type, en zij heeft een eigen taak.
 * `forces_envelope` draagt de UGT; `sls_frequent_envelope` draagt (6.15)
 * voor §7.3, omdat de nationale bijlage bij 7.3.1(5) de scheurwijdte
 * onder de frequente combinatie beoordeeld wil hebben. Deze lijst draagt
 * (6.16) voor M₀Eqp in (5.19) — de effectieve kruipcoëfficiënt van
 * §5.8.4, die de norm uitdrukkelijk aan de QUASI-BLIJVENDE combinatie
 * koppelt.
 *
 * De drie zijn niet uitwisselbaar en er is met opzet geen terugval van de
 * een op de ander: (6.15) als (6.16) lezen geeft een te grote M₀Eqp en
 * dus een te grote φ_ef, en andersom een te kleine. Is deze lijst leeg,
 * dan blijft φ_ef onbekend, staat §5.8.3.1(1) A = 0,7 toe, en zegt de
 * kruiptoets dat met de reden erbij.
 */
sls_quasi_permanent_envelope: Array<ForcePoint>, 
/**
 * Het UGT-krachtsverloop uit een EERSTE-ORDE-berekening van dezelfde
 * combinaties als `forces_envelope`, alleen voor §5.8.
 *
 * WAAROM EEN EIGEN LIJST. §5.8.3.1(1) definieert r_m = M₀₁/M₀₂ met de
 * eerste-orde-eindmomenten, en (5.19) in §5.8.4(2) noemt M₀Ed "het
 * eerste-orde-buigend moment". Komt `forces_envelope` uit een tweede-orde-
 * of fysisch niet-lineaire berekening, dan zitten de tweede-orde-effecten
 * al in die momenten, en dan verschuiven r_m (dus C en λ_lim) en φ_ef (dus
 * A). Uit deze lijst komen dan M₀Ed, M₀₁ en M₀₂; de normaalkracht, de keuze
 * van de maatgevende snede en alle doorsnedetoetsen blijven uit
 * `forces_envelope`. `sls_quasi_permanent_envelope` hoort in dat geval ook
 * eerste orde te zijn.
 *
 * `None` = `forces_envelope` is zelf eerste orde (of de aanroeper heeft
 * niets anders); dan verandert er niets. Een lijst waarin de maatgevende
 * combinatie ontbreekt, wordt niet stil vervangen: dan is §5.8 niet
 * uitgevoerd, met de reden.
 */
first_order_envelope?: Array<ForcePoint>, 
/**
 * De §5.8-gegevens: geschoord of ongeschoord, de kniklengte, de kruip en
 * de twee keuzen die §9.5 nodig heeft.
 *
 * `None` = niet opgegeven. Staat er normaaldruk op de staaf, dan komt
 * §5.8.3.1 als "niet uitgevoerd" in het rapport met de reden; staat er
 * geen druk op, dan is §5.8 niet van toepassing en zegt de toets dát.
 * Er wordt niets aangenomen — zie [`ConcreteColumnInput`] voor waarom
 * geschoord en l₀ geen standaardwaarde mogen hebben.
 */
column?: ConcreteColumnInput, 
/**
 * Hoe de staaf in het model staat — alleen voor de benaming van de zijden
 * in de afleiding.
 *
 * De krachtenomhullende en de zones horen in de referentierichting van de
 * staaf te staan: liggend van links naar rechts, staand van voet naar
 * kop. "Onderwapening" en "bovenwapening" zijn dan bij een liggende staaf
 * letterlijk; bij een staande staaf ligt de onderwapening RECHTS en de
 * bovenwapening LINKS, en dat zet de kern er bij elke toets die een
 * trekzijde kiest bij. `None` of weglaten = [`Staafstand::Liggend`].
 */
staafstand?: Staafstand, 
/**
 * Kanttekeningen bij de staafstand die de BOUWER van de invoer opstelt. De
 * kern zet ze letterlijk bij elke toets die een trekzijde kiest en bij de
 * dekkingslijn, achter de zijden in wereldtermen, en rekent er nergens mee.
 *
 * WAAROM. Aan welke fysieke zijde de "bovenwapening" ligt, springt bij een
 * naar links hellende staaf op 75° van het bovenvlak naar het ondervlak
 * (zie `design-mockup/src/lib/referentierichting.ts`, DE SPRONG BIJ 75°).
 * Of een staaf dicht bij die sprong ligt, weet alleen wie de meetkunde
 * kent; de kern krijgt alleen de omhullende. Zonder dit kanaal zou de
 * waarschuwing niet in de afleiding en niet in het rapport komen. `None` of
 * een lege lijst = geen kanttekening.
 */
staafstand_notities?: Array<string>, };
