// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén sterkteklasse voor beton — één kolom uit tabel 3.1.
 *
 * Sterkten in N/mm², E_cm in N/mm², rekken dimensieloos.
 */
export type ConcreteClass = { 
/**
 * Aanduiding "C30/37": cilinder-/kubusdruksterkte.
 */
name: string, 
/**
 * Karakteristieke cilinderdruksterkte f_ck na 28 dagen (tabel 3.1).
 */
f_ck: number, 
/**
 * Karakteristieke kubusdruksterkte f_ck,cube (tabel 3.1).
 */
f_ck_cube: number, 
/**
 * Gemiddelde druksterkte f_cm = f_ck + 8 (tabel 3.1).
 */
f_cm: number, 
/**
 * Gemiddelde axiale treksterkte f_ctm (tabel 3.1).
 */
f_ctm: number, 
/**
 * 5 %-fractiel van de treksterkte f_ctk,0,05 = 0,7·f_ctm (tabel 3.1).
 */
f_ctk_005: number, 
/**
 * 95 %-fractiel van de treksterkte f_ctk,0,95 = 1,3·f_ctm (tabel 3.1).
 */
f_ctk_095: number, 
/**
 * Secans-elasticiteitsmodulus E_cm in N/mm² (tabel 3.1 geeft GPa).
 */
e_cm: number, 
/**
 * Rek bij de maximale spanning in de niet-lineaire relatie van 3.1.5 (tabel 3.1).
 */
eps_c1: number, 
/**
 * Grensrek in de niet-lineaire relatie van 3.1.5 (tabel 3.1).
 */
eps_cu1: number, 
/**
 * Rek bij het bereiken van f_cd in het parabool-rechthoekdiagram (3.1.7(1), tabel 3.1).
 */
eps_c2: number, 
/**
 * Grensrek van het parabool-rechthoekdiagram (3.1.7(1), tabel 3.1).
 */
eps_cu2: number, 
/**
 * Exponent n van het parabool-rechthoekdiagram (3.1.7(1), tabel 3.1).
 */
n: number, 
/**
 * Rek bij het bereiken van f_cd in het bilineaire diagram (3.1.7(2), tabel 3.1).
 */
eps_c3: number, 
/**
 * Grensrek van het bilineaire diagram en de rechthoekige spanningsverdeling
 * (3.1.7(2) en (3), tabel 3.1).
 */
eps_cu3: number, };
