// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De zijde van de doorsnede waarop een dekking en een milieuklasse slaan.
 *
 * # WAAROM DRIE ZIJDEN EN NIET TWEE OF VIER
 *
 * Een balk heeft vier betonoppervlakken: boven, onder, links en rechts.
 * 4.4.1.1(1)P kent aan elk daarvan een eigen dekking toe. Toch zijn het er
 * hier drie, en dat is een keuze met een reden per variant.
 *
 * * **Boven en onder apart — noodzakelijk.** Zij bepalen de ligging van de
 *   staafas en daarmee de nuttige hoogte d van §1.6 ("effectieve hoogte van
 *   een dwarsdoorsnede"). Boven- en onderwapening liggen aan verschillende
 *   oppervlakken en kunnen dus in een verschillend milieu liggen; met één
 *   dekking voor beide ligt de bovenwapening op de verkeerde plaats zodra de
 *   bovenzijde een andere klasse heeft. Dat is precies het geval waarvoor dit
 *   type bestaat.
 * * **De twee zijkanten samen — verantwoord.** In elke formule die de
 *   zijdelingse dekking gebruikt komt zij uitsluitend als PAAR voor: de
 *   dwarsafstand van de beugelbenen s_t = b_w − 2·c − Ø_beugel (§9.2.2(8)),
 *   de vrije staafafstand van §8.2(2) en de binnenmaat waarin een rij staven
 *   moet passen. Alleen de SOM van links en rechts telt daar. Links en rechts
 *   uit elkaar trekken zou dus in geen enkele uitkomst zichtbaar worden — het
 *   zou alleen de rij staven uit het midden schuiven, en die meetkunde
 *   (staven scheef in de doorsnede) heeft dit model niet.
 * * **Vier zou een vierde invoerveld kosten** voor een onderscheid dat geen
 *   getal verandert. Verschillen de twee zijkanten werkelijk van milieu, dan
 *   is de zwaarste van de twee de juiste invoer; die keus is veilig en staat
 *   in de invoerhulp.
 *
 * De volgorde is die van de tekening: eerst boven, dan onder, dan de
 * zijkanten.
 */
export type CoverSide = "Top" | "Bottom" | "Sides";
