// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welke van de drie termen van (4.2) de maat gaf.
 */
export type CoverGovernedBy = "Bond" | "Durability" | "Floor";
