// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deelstap } from "../steel/Deelstap";
import type { KruipUitkomst } from "./KruipUitkomst";

/**
 * Het antwoord: alle tussenwaarden, de afleiding en de kanttekeningen.
 */
export type CreepCoefficientResponse = { beam_id: number, concrete_class: string, 
/**
 * A_c en u als h₀ uit de doorsnede volgt; anders `None`.
 */
a_c_mm2: number | null, u_mm: number | null, uitkomst: KruipUitkomst, deelstappen: Array<Deelstap>, notes: Array<string>, };
