// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CementClass } from "./CementClass";
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { NationaleBijlage } from "../norm/NationaleBijlage";

/**
 * Eén verzoek om φ(∞,t₀) volgens bijlage B, zoals het over het Tauri-command,
 * de toetsbrug en de MCP-server gaat.
 *
 * h₀ komt uit PRECIES ÉÉN van `section` (B.6 met de hele omtrek) en `h0_mm`
 * (opgegeven). Allebei of geen van beide wordt geweigerd: twee bronnen voor
 * hetzelfde getal zonder voorrangsregel is een stille keuze.
 */
export type CreepCoefficientRequest = { 
/**
 * De nationale bijlage. Bijlage B kent geen nationaal bepaalde
 * parameters; het veld staat er voor dezelfde invoervorm als de andere
 * betonverzoeken, en een onbekende bijlage wordt bij het lezen geweigerd.
 */
bijlage: NationaleBijlage, 
/**
 * Vrij te kiezen nummer; komt onveranderd terug.
 */
beam_id: number, 
/**
 * Sterkteklasse, bijvoorbeeld "C30/37"; f_cm uit tabel 3.1.
 */
concrete_class: string, 
/**
 * Relatieve vochtigheid van de omgeving, in %.
 */
relative_humidity_pct: number, 
/**
 * Ouderdom van het beton bij belasten, in dagen.
 */
t0_days: number, cement_class: CementClass, 
/**
 * De doorsnede waaruit h₀ = 2·A_c/u volgt, met u de hele omtrek.
 */
section?: ConcreteSectionInput, 
/**
 * De fictieve dikte h₀ zelf, in mm — als maar een deel van de omtrek
 * uitdroogt (een vloer op zand, een wand tegen grond).
 */
h0_mm?: number, 
/**
 * Het beschouwde tijdstip t in dagen; weglaten = alleen φ(∞,t₀).
 */
t_days?: number, };
