// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De doorbuigingsgrenzen van 7.4.1(4) en (5) voor één overspanning.
 *
 * Dit zijn de grenzen waar de slankheidstoets VOOR STAAT: 7.4.2(2) zegt dat
 * bij een geslaagde slankheidstoets ervan mag zijn uitgegaan dat de
 * doorbuigingen deze grenzen niet overschrijden. Ze worden hier dus
 * meegeleverd zonder zelf te worden getoetst — er is in deze weg geen
 * berekende doorbuiging om ze mee te vergelijken.
 */
export type DeflectionLimits = { 
/**
 * De overspanning waarop de grenzen betrekking hebben, mm.
 */
span_mm: number, 
/**
 * 7.4.1(4): overspanning/250, voor het uiterlijk en de algehele
 * bruikbaarheid. De zakking is bepaald ten opzichte van de opleggingen.
 */
appearance_mm: number, 
/**
 * 7.4.1(5): overspanning/500, voor doorbuigingen NA DE BOUW die
 * aansluitende constructiedelen kunnen beschadigen.
 */
damage_mm: number, 
/**
 * 7.4.1(4): een in de bekisting aangebrachte opbuiging behoort in het
 * algemeen niet groter te zijn dan overspanning/250.
 */
precamber_max_mm: number, 
/**
 * De belastingcombinatie waaronder beide grenzen gelden.
 */
combination: string, };
