// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dwarskrachtdekking } from "./Dwarskrachtdekking";
import type { Momentdekking } from "./Momentdekking";
import type { SteunpuntEis } from "./SteunpuntEis";

/**
 * Het antwoord op [`DekkingslijnVerzoek`]: de hele dekkingslijn van één staaf.
 */
export type DekkingslijnAntwoord = { 
/**
 * Staafnummer; komt onveranderd terug uit het verzoek.
 */
beam_id: number, 
/**
 * Doorsnedenaam, bijv. "300 x 500".
 */
section_name: string, concrete_class: string, reinforcement_grade: string, 
/**
 * "onder 3Ø16, boven 2Ø12, beugel Ø8, dekking 30 mm".
 */
reinforcement_summary: string, 
/**
 * Staaflengte, mm.
 */
lengte_mm: number, 
/**
 * f_yd van de wapening, N/mm² — de hoogte van de weerstandslijn is
 * A_s·f_yd.
 */
f_yd_mpa: number, 
/**
 * f_ctk;0,05 van de betonsterkteklasse (tabel 3.1), N/mm² — zonder deze
 * waarde is er geen f_bd en dus geen l_bd.
 */
f_ctk_005_mpa: number, 
/**
 * a_l — de verschuiving van de momentenlijn, mm. Een LENGTE, geen
 * richting: bij een omhullende is de benodigde trekkracht op plaats x het
 * MAXIMUM van de omhullende over het venster [x − a_l; x + a_l].
 */
a_l_mm: number, 
/**
 * De vindplaats van a_l — "art. 9.2.1.3(2) (9.2)" of "art. 6.2.2(5)".
 */
a_l_artikel: string, 
/**
 * De inwendige hefboomsarm waarmee a_l is bepaald, mm. Let op: voor de
 * KRACHT F = M_Ed/z is een kleine z ongunstig en wordt z per snede uit de
 * korf ter plaatse genomen; voor de VERSCHUIVING is een grote z ongunstig
 * en wordt de grootste d van de staaf gebruikt. Die twee veilige kanten
 * vallen niet samen, en daarom is dit een eigen veld.
 */
z_voor_a_l_mm: number, 
/**
 * De onderwapening.
 */
onder: Momentdekking, 
/**
 * De bovenwapening.
 */
boven: Momentdekking, 
/**
 * De dwarskracht.
 */
dwarskracht: Dwarskrachtdekking, 
/**
 * §9.2.1.4 en §9.2.1.5 aan beide staafuiteinden.
 */
steunpunten: Array<SteunpuntEis>, 
/**
 * De grootste unity check van de momentendekking over beide zijden, buiten
 * de eindzones. Leeg als er nergens wapening ligt.
 */
uc_moment_max?: number, 
/**
 * De grootste unity check van de dwarskrachtdekking. Leeg als er nergens
 * een V_Rd kon worden bepaald.
 */
uc_dwarskracht_max?: number, 
/**
 * Kanttekeningen die met de hele lijn mee moeten reizen — waarom a_l zo
 * is gelezen, wat er met N_Ed is gebeurd, waarom 6.2.1(8) niet is
 * toegepast en waarom V_Rd,c en V_Rd,s nergens zijn opgeteld.
 */
notes: Array<string>, };
