// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteBeamCheckInput } from "./ConcreteBeamCheckInput";

/**
 * Eén stateloos verzoek om de dekkingslijn van één betonstaaf.
 *
 * `deny_unknown_fields`: een tikfout in een van de vier optionele velden zou
 * zonder deze strengheid stilzwijgend op "niet opgegeven" terugvallen, en dan
 * verandert de lijn zonder dat iemand het ziet — een vergeten `z_mm` levert
 * bij een staaf zonder normaalkracht 0,9·d in plaats van de opgegeven waarde.
 */
export type DekkingslijnVerzoek = { 
/**
 * De betonstaaf, in HETZELFDE type dat `check_concrete_beams` krijgt.
 *
 * Gebruikt worden: `beam_id`, `section`, `concrete_class`,
 * `reinforcement_grade`, `cage`, `reinforcement_zones`, `length_m`,
 * `forces_envelope`, `design_situation` en `steel_branch`.
 *
 * Niet gebruikt: `n_strips`, `apply_min_eccentricity`,
 * `sls_frequent_envelope`, `exposure_class`, `structural_class`,
 * `aggregate_size_mm`, `structural_system` en `bar_spacing_mm`. Zij horen
 * bij de doorsnedetoetsen (§6.1, §7.3, §7.4, §8.2) en niet bij de
 * dekkingslijn; zie de moduletekst voor waarom dit type tóch als geheel
 * wordt hergebruikt.
 */
beam: ConcreteBeamCheckInput, 
/**
 * De inwendige hefboomsarm z in mm waarmee figuur 9.2 het moment op
 * kracht omrekent.
 *
 * Leeg = niet opgegeven: dan volgt z per snede uit 6.2.3(1). Zonder
 * normaalkracht is dat de benadering z = 0,9·d. Mét normaalkracht staat
 * de norm die benadering niet toe en is z de werkelijke inwendige
 * hefboomsarm uit het spanningsblok van 3.1.7(3) bij de N_Ed van die
 * snede — de arm van de buigweerstand, dezelfde kern als de buigtoets —
 * begrensd op 0,9·d zodat een normaalkracht de lijn nooit gunstiger
 * maakt dan zonder; waar het spanningsblok geen arm levert (geen
 * wapening, bij deze normaalkracht geheel gedrukt, trekcapaciteit
 * overschreden) geldt 0,9·d met de reden erbij. Elk punt meldt zijn
 * grondslag in `z_grondslag`.
 */
z_mm?: number, 
/**
 * c_d volgens figuur 8.3, mm — de maat die α₂ van tabel 8.2 bepaalt.
 *
 * Leeg = 0 mm, de ONBEPAALDE waarde: alle alfa-factoren worden 1,0 en l_bd
 * is maximaal, dus de schuine takken van figuur 9.2 zijn zo lang als de
 * norm ze kan maken. Dat is de veilige kant. Let op het gevolg: een
 * omgebogen staafeinde ([`Staafvorm::AndersDanRecht`](nen_en_1992_1_1::Staafvorm))
 * verkort l_bd dan NIET, want α₁ = 0,7 vergt c_d > 3Φ.
 */
c_d_mm?: number, 
/**
 * A_sl in mm² volgens 6.2.2(1): de trekwapening die ≥ (l_bd + d) voorbij
 * de beschouwde doorsnede doorloopt (figuur 6.3).
 *
 * Leeg = de trekrij van de korf die op die plaats geldt. Met zones is dat
 * al een stuk scherper dan één korf voor de hele staaf, maar het is nog
 * niet de regel van 6.2.2(1); elk punt van de dwarskrachtlijn meldt
 * daarom zowel de GEBRUIKTE A_sl als de deelverzameling die aantoonbaar
 * naar beide kanten ver genoeg doorloopt.
 */
a_sl_mm2?: number, 
/**
 * cot θ van de betondrukdiagonaal, binnen 1,0 ≤ cot θ ≤ 2,5 (NB bij
 * 6.2.3(2)).
 *
 * Leeg = de dwarskrachttoets kiest θ per snede zelf, en voor de
 * verschuiving a_l wordt de bovengrens aangehouden: een grotere cot θ
 * geeft volgens (9.2) een grotere a_l en dus een zwaardere eis.
 */
cot_theta?: number, };
