// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ductiliteitsklasse van betonstaal — bijlage C, tabel C.1.
 */
export type DuctilityClass = "A" | "B" | "C";
