// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snedezijde } from "./Snedezijde";
import type { Spoor } from "./Spoor";
import type { Weerstandsroute } from "./Weerstandsroute";
import type { ZGrondslag } from "./ZGrondslag";

/**
 * Eén plaats op de DWARSKRACHTdekkingslijn.
 *
 * Er is met opzet ÉÉN `aanwezig_kn`, met de route die hem leverde ernaast.
 * V_Rd,c en V_Rd,s staan hier niet als twee optelbare velden: 6.2.1(2) geeft
 * V_Rd = V_Rd,s + V_ccd + V_td zonder betonterm, 6.2.3(3) noemt V_Rd "de
 * kleinste waarde van" (6.8) en (6.9), en 6.2.1(3) is een tweede, losstaande
 * bewijsvoering.
 */
export type Dwarskrachtpunt = { 
/**
 * Plaats langs de staaf, mm vanaf de beginknoop.
 */
x_mm: number, 
/**
 * Aan welke kant van een sprong dit punt ligt.
 */
zijde: Snedezijde, 
/**
 * |V_Ed| van de maatgevende combinatie, kN.
 */
benodigd_kn: number, 
/**
 * De maatgevende weerstand V_Rd, kN. Leeg als zij niet kon worden bepaald;
 * `reden` zegt waarom.
 */
aanwezig_kn?: number, 
/**
 * V_Ed/V_Rd. Leeg als `aanwezig_kn` dat ook is.
 */
uc?: number, 
/**
 * Welke bewijsvoering `aanwezig_kn` leverde.
 */
route?: Weerstandsroute, 
/**
 * Welk spoor van 6.2.1(3)/(5) hier geldt.
 */
spoor: Spoor, 
/**
 * Waarom er geen V_Rd is.
 */
reden?: string, 
/**
 * A_sl zoals de dwarskrachttoets hem gebruikte, mm².
 */
a_sl_gebruikt_mm2: number, 
/**
 * De trekwapening die op deze plaats aantoonbaar naar BEIDE kanten
 * ≥ (l_bd + d) doorloopt, mm² — de deelverzameling die zonder
 * opleggingsgeometrie aan 6.2.2(1) voldoet. Wordt gemeld, niet opgelegd.
 */
a_sl_doorlopend_mm2: number, 
/**
 * De combinatie die deze snede maatgevend maakte.
 */
combinatie_id: number, 
/**
 * De inwendige hefboomsarm van het vakwerkmodel op deze plaats, mm.
 * Leeg als er geen vakwerkmodel is opgebouwd.
 */
z_mm?: number, 
/**
 * Waar die z vandaan komt — 6.2.3(1). Leeg als `z_mm` dat ook is.
 */
z_grondslag?: ZGrondslag, 
/**
 * De werkelijke, onbegrensde hefboomsarm uit het spanningsblok bij N_Ed,
 * mm. Alleen gevuld bij `Evenwicht` en `EvenwichtBegrensd`.
 */
z_werkelijk_mm?: number, };
