// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dwarskrachtpunt } from "./Dwarskrachtpunt";

/**
 * De dwarskrachtdekking van de staaf.
 */
export type Dwarskrachtdekking = { 
/**
 * De lijn, oplopend in x. Op een sprong staan twee punten met dezelfde x.
 */
punten: Array<Dwarskrachtpunt>, 
/**
 * De maatgevende plaats — de index in `punten`.
 *
 * Hier wordt NIETS uitgezonderd: 6.2.1(8) is niet gebouwd (het model kent
 * geen oplegvlak en dus geen dagkant), dus er wordt tot in de oplegging
 * getoetst. Dat is de veilige kant.
 */
maatgevend?: number, 
/**
 * Kanttekeningen.
 */
toelichting: Array<string>, };
