// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeamLine } from "./BeamLine";
import type { FlangeGeometry } from "./FlangeGeometry";

/**
 * Eén verzoek om de meewerkende flensbreedte, zoals het over het
 * Tauri-command, de toetsbrug en de MCP-server gaat.
 *
 * `deny_unknown_fields`: een tikfout in `b_i_mm` zou anders een lege lijst
 * opleveren en dus b_eff = b_w, stilzwijgend en aan de andere kant van de
 * werkelijkheid.
 */
export type EffectiveFlangeWidthRequest = { 
/**
 * Vrij te kiezen nummer; komt onveranderd terug. 0 als het niet om een
 * staaf uit een model gaat.
 */
beam_id: number, 
/**
 * De doorgaande liggerlijn waar de staaf deel van is.
 */
line: BeamLine, 
/**
 * De flensmaten van figuur 5.3.
 */
flange: FlangeGeometry, 
/**
 * De plaats langs de liggerlijn (mm vanaf `line.start`) waarvoor de
 * afleiding wordt uitgeschreven — meestal het midden van de staaf die de
 * b_eff gaat gebruiken.
 *
 * Blijft dit veld weg, dan komt alleen de verdeling terug en is
 * [`EffectiveFlangeWidthResponse::applied`] leeg. Dat is geen gebrek maar
 * de eerlijke uitkomst: zonder plaats is er geen gebied, en zonder gebied
 * is er geen afleiding om op te schrijven.
 *
 * Waarom de plaats in het VERZOEK zit en niet een keten per gebied in het
 * antwoord: één keten per gebied maakt het antwoord voor élke aanroeper
 * groter, en "welk gebied geldt hier" is precies de vraag die 5.3.2.1(4)
 * stelt. Zo staat die vraag in het verzoek en het antwoord erop in het
 * antwoord.
 */
x_mm: number | null, };
