// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Milieuklasse volgens tabel 4.1 ("Verband tussen milieuklassen en
 * milieu-omstandigheden volgens EN 206-1").
 *
 * De volgorde is die van de tabel: eerst X0, dan de carbonatatieklassen, de
 * chlorideklassen, de zeewaterklassen, vorst/dooi en chemische aantasting.
 */
export type ExposureClass = "X0" | "XC1" | "XC2" | "XC3" | "XC4" | "XD1" | "XD2" | "XD3" | "XS1" | "XS2" | "XS3" | "XF1" | "XF2" | "XF3" | "XF4" | "XA1" | "XA2" | "XA3";
