// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExposureClass } from "./ExposureClass";

/**
 * Eén rij uit tabel 4.1, zoals de keuzelijst hem nodig heeft.
 *
 * `description` is de kolom "Beschrijving van het milieu" en `examples` de
 * kolom "Informatieve voorbeelden waar de milieuklassen zich kunnen
 * voordoen"; beide woordelijk uit de tabel. `group` is het tussenkopje
 * waaronder de klasse in de tabel staat.
 */
export type ExposureClassInfo = { class: ExposureClass, 
/**
 * "XC4" — de klasseaanduiding als tekst, voor labels en het rapport.
 */
name: string, 
/**
 * Het tussenkopje uit tabel 4.1, bijv. "2 Corrosie ingeleid door carbonatatie".
 */
group: string, 
/**
 * De kolom "Beschrijving van het milieu".
 */
description: string, 
/**
 * De kolom "Informatieve voorbeelden…"; regels gescheiden door " · ".
 */
examples: string, 
/**
 * De kolomaanduiding in tabel 4.4N, of `None` als de tabel de klasse niet
 * kent (XF en XA).
 */
cover_column: string | null, };
