// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExposureClass } from "./ExposureClass";

/**
 * Wat één betonoppervlak aan EIGEN gegevens draagt: zijn dekking en zijn
 * milieuklasse.
 *
 * # `None` betekent "volg het element", niet "nul" en niet "onbekend"
 *
 * Beide velden leeg — de [`Default`] — is de stand van vóór dit type: de zijde
 * gebruikt dan de dekking en de milieuklasse van het element. Dat is de reden
 * dat dit type überhaupt zo mag bestaan: een projectbestand van vóór deze
 * uitbreiding kent deze velden niet, `#[serde(default)]` maakt ze leeg, en
 * elke uitkomst blijft daarmee bit voor bit dezelfde. Zie
 * [`crate::section::ReinforcementCage::cover_at_mm`].
 *
 * De dekking en de klasse staan met opzet in ÉÉN type en niet in twee losse
 * lijstjes. (4.2) leidt c_min,dur rechtstreeks uit de milieuklasse af; wie ze
 * zou scheiden, kan een projectbestand krijgen met een eigen dekking voor de
 * bovenzijde en een milieuklasse voor het hele element, en niets dat die
 * tegenspraak opmerkt.
 */
export type FaceCover = { 
/**
 * De nominale dekking c_nom van DEZE zijde, in mm. `None` = de dekking van
 * het element.
 */
cover_mm?: number, 
/**
 * De milieuklasse van DEZE zijde (tabel 4.1). `None` = de milieuklasse van
 * het element.
 */
exposure_class?: ExposureClass, };
