// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wijze van bezwijken (einde van het M-κ-diagram).
 */
export type FailureMode = "ConcreteCrushing" | "SteelRupture" | "SteelStrainLimit" | "AxialCapacityExceeded" | "NoEquilibrium";
