// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De flensmaten van figuur 5.3, in mm.
 *
 * `b_i_mm` bevat één waarde per uitkragend flensdeel: twee voor een T-ligger,
 * één voor een L-ligger (randligger), geen voor een rechthoek. Elke b_i is de
 * halve vrije afstand tot het naastliggende lijf, of het werkelijke overstek
 * bij een rand. b = b_w + Σ b_i.
 */
export type FlangeGeometry = { 
/**
 * Lijfbreedte b_w in mm.
 */
b_w_mm: number, 
/**
 * De uitkragende flensdelen b_i in mm (0, 1 of 2 stuks).
 */
b_i_mm: Array<number>, };
