// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De gevallen van **figuur 5.7** — voorbeelden van knikvormen met hun
 * effectieve lengte.
 *
 * De figuur toont ZEVEN vakjes, a) tot en met g). Vijf ervan hebben een vaste
 * l₀; de laatste twee, f) en g), zijn juist de gevallen mét gedeeltelijke
 * inklemming en horen bij de vergelijkingen (5.15) en (5.16). Hun bijschrift
 * geeft daarom een BEREIK en geen waarde. Zie [`Knikgeval::l0_factor`], die
 * voor f) en g) `None` teruggeeft: daar is een rekensom nodig, geen tabel.
 *
 * **Het bijschrift van g) is geen ondergrens.** Er staat "l₀ > 2l", maar dat
 * hoort bij de in dát vakje getekende situatie. (5.16) zelf loopt van l₀ = l
 * (bij k₁ = k₂ = 0) tot oneindig en levert bij k₁ = 0,4 en k₂ = 0,8 een l₀ van
 * 1,91·l — netjes onder 2l. Wie het bijschrift als ondergrens leest, vermoedt
 * daar ten onrechte een rekenfout. Bij f) valt het bereik l/2 < l₀ < l wél
 * samen met het bereik van (5.15), maar dat volgt uit die formule en niet uit
 * de figuur.
 */
export type Knikgeval = "ScharnierendScharnierend" | "Console" | "IngeklemdScharnierend" | "TweezijdigIngeklemdGeschoord" | "TweezijdigIngeklemdOngeschoord" | "GedeeltelijkIngeklemdGeschoord" | "GedeeltelijkIngeklemdOngeschoord";
