// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Knikgeval } from "./Knikgeval";

/**
 * Hoe de kniklengte l₀ van deze staaf wordt bepaald.
 *
 * # Waarom deze twee wegen, en niet de k-factoren van (5.15)/(5.16)
 *
 * §5.8.3.2 kent vier wegen naar l₀: de vaste gevallen van figuur 5.7, de
 * vergelijking (5.15) voor een geschoord raamwerk, (5.16) voor een
 * ongeschoord raamwerk, en (5.17) uit een numeriek bepaalde knikbelasting.
 * De kern ([`Kniklengtebepaling`]) draagt ze alle vier. Dit invoertype biedt
 * er twee aan, en dat is een keuze:
 *
 * * **Figuur 5.7** is wat een constructeur herkent. De vijf vakjes met een
 *   VASTE l₀ — a) l₀ = l, b) 2l, c) 0,7l, d) l/2, e) l — zijn de gevallen die
 *   in een raamwerkmodel ook werkelijk te benoemen zijn: scharnierend,
 *   ingeklemd, console, zijdelings gehouden of niet.
 * * **l₀ zelf opgeven** is de uitweg voor al het andere. Wie (5.15), (5.16) of
 *   (5.17) met de hand heeft doorgerekend, of een aparte knikanalyse heeft
 *   gedaan, vult de uitkomst hier in; de afleiding legt dan vast dát l₀ is
 *   opgegeven en niet waaruit.
 *
 * De vakjes f) en g) van figuur 5.7 — gedeeltelijke inklemming — staan hier
 * NIET, en daarmee ook (5.15) en (5.16) niet. Reden: die vergelijkingen vragen
 * k = (θ/M)·(EI/l) per staafeind, de relatieve flexibiliteit van de
 * verhindering. Dat getal is niet uit dit model af te lezen. §5.8.3.2(5) eist
 * er bovendien uitdrukkelijk bij dat het effect van SCHEURVORMING in de
 * verhinderende elementen wordt meegenomen, en §5.8.3.2(4) dat bij een
 * meewerkende aansluitende kolom de SOM (EI/l)_a + (EI/l)_b wordt genomen.
 * Een k die de app zelf zou verzinnen stuurt l₀ recht evenredig en daarmee λ,
 * en dat gebeurt onzichtbaar. Wie k wél heeft, rekent (5.15)/(5.16) uit en
 * vult l₀ in.
 */
export type Kniklengtekeuze = { "soort": "Figuur57", geval: Knikgeval, } | { "soort": "Opgegeven", l0_m: number, };
