// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Knikgeval } from "./Knikgeval";

/**
 * Hoe l₀ tot stand komt.
 */
export type Kniklengtebepaling = { "Standaardgeval": Knikgeval } | { "Raamwerk": { k1: number, k2: number, } } | { "UitKnikbelasting": { ei_nmm2: number, n_b_n: number, } } | "Opgegeven";
