// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CementClass } from "./CementClass";

/**
 * Alle tussenwaarden van bijlage B, in de volgorde van de norm.
 */
export type KruipUitkomst = { f_cm_mpa: number, relative_humidity_pct: number, h0_mm: number, 
/**
 * De opgegeven ouderdom bij belasten, t₀,T in (B.9).
 */
t0_days: number, cement_class: CementClass, 
/**
 * α van (B.9).
 */
alpha_cement: number, 
/**
 * t₀ volgens (B.9), de ouderdom die in (B.5) wordt ingevuld.
 */
t0_adjusted_days: number, 
/**
 * Is de ondergrens 0,5 dag van (B.9) maatgevend geweest?
 */
t0_ondergrens_maatgevend: boolean, 
/**
 * α₁, α₂, α₃ van (B.8c). Ook bij f_cm ≤ 35 MPa uitgerekend; ze worden
 * dan niet gebruikt.
 */
alpha_1: number, alpha_2: number, alpha_3: number, 
/**
 * `true` = de b-tak van (B.3) en (B.8), f_cm > 35 MPa.
 */
hoge_sterkte_tak: boolean, phi_rh: number, beta_fcm: number, beta_t0: number, 
/**
 * φ₀ van (B.2).
 */
phi_0: number, 
/**
 * β_H van (B.8a)/(B.8b), na de bovengrens.
 */
beta_h: number, 
/**
 * Is de bovengrens 1500 (of 1500·α₃) van (B.8) maatgevend geweest?
 */
beta_h_bovengrens_maatgevend: boolean, 
/**
 * φ(∞,t₀) = φ₀ (β_c → 1).
 */
phi_inf_t0: number, 
/**
 * Het beschouwde tijdstip t, als opgegeven.
 */
t_days: number | null, 
/**
 * β_c(t,t₀) van (B.7), als t is opgegeven.
 */
beta_c: number | null, 
/**
 * φ(t,t₀) van (B.1), als t is opgegeven.
 */
phi_t_t0: number | null, };
