// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hoe φ_ef uit (5.19) is bepaald — de afleiding voor het rapport.
 */
export type Kruip519Afleiding = { phi_inf_t0: number, ugt_combinatie: string, 
/**
 * M₀Ed op de gekozen doorsnede, kNm.
 */
m0_ed_knm: number, 
/**
 * De gekozen doorsnede, mm vanaf de beginknoop.
 */
x_mm: number, 
/**
 * De quasi-blijvende combinatie die φ_ef bepaalde; `None` als er geen was.
 */
quasi_combinatie: string | null, 
/**
 * M₀Eqp van die combinatie op dezelfde doorsnede, kNm.
 */
m0_eqp_knm: number | null, 
/**
 * |M₀Eqp|/|M₀Ed| als (5.19) is ingevuld; `None` bij de bovengrens.
 */
verhouding: number | null, 
/**
 * De φ_ef waarmee het spanning-rekdiagram is opgerekt (5.8.6(4)).
 */
phi_ef: number, 
/**
 * Is de bovengrens φ(∞,t₀) gehouden?
 */
bovengrens_gehouden: boolean, 
/**
 * De uitgeschreven afleiding, woordelijk voor het rapport.
 */
toelichting: string, };
