// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Het antwoord op §5.8.4(4): mag φ_ef = 0 worden aangehouden?
 */
export type KruipVerwaarlozing = { 
/**
 * Alle drie de voorwaarden vervuld?
 */
toegestaan: boolean, 
/**
 * φ(∞,t₀) ≤ 2.
 */
kruipcoefficient_ten_hoogste_2: boolean, 
/**
 * λ ≤ 75.
 */
slankheid_ten_hoogste_75: boolean, 
/**
 * M₀Ed/N_Ed ≥ h, met h de hoogte van de doorsnede in de overeenkomstige
 * richting.
 */
excentriciteit_ten_minste_h: boolean, 
/**
 * De uitgerekende excentriciteit M₀Ed/N_Ed in mm, ter vergelijking met h.
 */
e0_mm: number, 
/**
 * De waarschuwing uit de OPMERKING bij §5.8.4(4), als zij van toepassing
 * is. `None` = de opmerking speelt hier niet of ω is niet opgegeven.
 */
waarschuwing: string | null, };
