// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuasiBlijvendMoment } from "./QuasiBlijvendMoment";

/**
 * De gegevens om φ_ef van één staaf in één UGT-combinatie uit (5.19) te
 * bepalen: φ_ef = φ(∞,t₀)·M₀Eqp/M₀Ed (EN 1992-1-1 5.8.4(2)).
 *
 * DE DOORSNEDE. 5.8.4(3): varieert de verhouding langs het element, dan mag
 * zij "voor de doorsnede met het maximale moment" worden berekend. De
 * aanroeper kiest die doorsnede: de plaats van het grootste |M₀Ed| langs de
 * staaf in de EERSTE-ORDE-oplossing van deze UGT-combinatie, en leest M₀Eqp op
 * dezelfde plaats uit de eerste-orde-oplossing van elke quasi-blijvende
 * combinatie.
 *
 * MEERDERE QUASI-BLIJVENDE COMBINATIES. De kern neemt de grootste φ_ef die
 * daaruit volgt (de laagste stijfheid, de ongunstige kant) en noemt welke.
 *
 * ALLEEN IN DE UGT. 7.4.3(5) vraagt in de BGT de volle φ(∞,t₀); een verzoek
 * met `limit_state = MeanValues` én dit blok wordt geweigerd.
 */
export type Kruip519Invoer = { 
/**
 * De eindwaarde van de kruipcoëfficiënt φ(∞,t₀) van de staaf (3.1.4).
 */
phi_inf_t0: number, 
/**
 * Naam van de UGT-combinatie, voor het rapport.
 */
ugt_combinatie: string, 
/**
 * Het grootste |M₀Ed| langs de staaf, MET teken, in kNm (eerste orde).
 */
m0_ed_knm: number, 
/**
 * Waar dat moment zit, mm vanaf de beginknoop.
 */
x_mm: number, 
/**
 * M₀Eqp op dezelfde doorsnede per quasi-blijvende combinatie. Leeg = er
 * is geen quasi-blijvende combinatie; dan geldt de bovengrens φ(∞,t₀).
 */
quasi_blijvend: Array<QuasiBlijvendMoment>, };
