// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welk geval uit figuur 5.2 een gebied is.
 */
export type L0Case = "EndSpan" | "InteriorSpan" | "SingleSpan" | "InteriorSupport" | "RestrainedEnd" | "Cantilever";
