// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { L0Case } from "./L0Case";

/**
 * Eén gebied uit figuur 5.2, met zijn plaats langs de liggerlijn en zijn l₀.
 */
export type L0Zone = { 
/**
 * Begin van het gebied langs de liggerlijn, mm vanaf `BeamLine::start`.
 */
x_start_mm: number, 
/**
 * Einde van het gebied langs de liggerlijn, mm.
 */
x_end_mm: number, 
/**
 * De afstand tussen de momentnulpunten voor dit gebied, mm.
 */
l0_mm: number, case: L0Case, 
/**
 * Bij een veldgebied: de overspanning waar het gebied bij hoort
 * (0-gebaseerd). Bij een steunpuntgebied leeg — dat ligt op twee
 * overspanningen tegelijk.
 */
span_index: number | null, 
/**
 * De uitdrukking uit figuur 5.2 met de overspanningen ingevuld, bijv.
 * `"l0 = 0,15·(l1 + l2) = 0,15·(6000 + 5000) = 1650 mm"`.
 */
expression: string, };
