// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wat er aan één uiteinde van de liggerlijn zit.
 *
 * De steunpunten TUSSEN twee overspanningen zijn impliciet; alleen de twee
 * buitenste uiteinden hebben een keuze.
 */
export type LineEnd = "Support" | "Restrained" | "Free";
