// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * β van (7.19): de invloed van de belastingsduur op de gemiddelde rek.
 *
 * Serde en ts-rs staan erop omdat het segmentstijfheidsverzoek in
 * `concrete-check` deze keuze als invoerveld draagt en hem in het antwoord
 * terugmeldt. Welke β is gebruikt mag niet impliciet blijven; het scheelt in
 * de BGT rechtstreeks stijfheid (zie `beta_van_7_19_werkt_de_goede_kant_op`).
 */
export type LoadDuration = "ShortTerm" | "Sustained";
