// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebarRow } from "./RebarRow";
import type { RebarSide } from "./RebarSide";
import type { Staafvorm } from "./Staafvorm";
import type { Stortpositie } from "./Stortpositie";

/**
 * Eén stuk langswapening dat over een deel van de staaf ligt — de eenheid
 * waarin §9.2.1.3 ("Inkorting van op trek belaste langswapening") denkt.
 *
 * # De maten x
 *
 * `x_start_mm` en `x_end_mm` zijn gemeten LANGS de staaf vanaf het beginknoop,
 * in millimeters, met x_start < x_end. Ze zijn de plaats waar het STAAL
 * begint en ophoudt, dus de fysieke staafuiteinden — niet de plaats waar de
 * staaf zijn volle kracht kan leveren. Dat verschil is precies §9.2.1.3(3):
 * "Met de weerstand van staven binnen hun verankeringslengte mag rekening zijn
 * gehouden, uitgaande van een lineair krachtverloop, zie figuur 9.2." Binnen
 * l_bd vanaf elk uiteinde telt de staaf dus LINEAIR mee, van nul op het
 * uiteinde tot vol op l_bd ervandaan; zie
 * [`crate::verankering::opneembare_krachtfractie`]. Dit type legt alleen vast
 * wáár de staaf ligt; wie die schuine tak tekent, rekent l_bd uit met
 * [`crate::verankering::verankeringslengte`].
 *
 * # Wat er voor §8.4 in staat, en wat niet
 *
 * [`crate::verankering::VerankeringInvoer`] vraagt vijftien gegevens. De
 * meeste daarvan volgen uit iets wat al bekend is en horen dus geen invoerveld
 * te worden — een tweede plek om hetzelfde te zeggen is een tweede plek om het
 * verkeerd te zeggen:
 *
 * * `diameter_mm` — uit [`Self::row`];
 * * `f_ctk_005_mpa`, `alpha_ct`, `gamma_c`, `f_yd_mpa` — uit de
 *   betonsterkteklasse, de staalsoort en de ontwerpsituatie van de staaf;
 * * `h_mm` en `z_staaf_boven_onderrand_mm` — uit de doorsnede en de korf: de
 *   staafas ligt op c_nom + Ø_beugel + Ø/2 van de rand aan [`Self::side`];
 * * `soort` (trek of druk) — dat hangt van het momentteken op de beschouwde
 *   snede af en is dus geen eigenschap van de zone;
 * * `c_d_mm`, `lambda`, `phi_t_mm`, `p_mpa` — afleidbaar uit de korf, de
 *   beugelzones en de dwarsdruk, en hun onbepaalde waarde (K = 0, geen gelaste
 *   dwarsstaaf, p = 0) ligt aan de VEILIGE kant: elke alfa-factor wordt dan
 *   1,0 en l_bd dus maximaal.
 *
 * Twee gegevens blijven over die niemand kan afleiden en die daarom hier
 * staan: [`Self::casting_position`] en [`Self::bar_shape`]. Beide zijn
 * UITVOERINGSgegevens.
 */
export type LongitudinalZone = { 
/**
 * Boven- of onderwapening.
 */
side: RebarSide, 
/**
 * Het aantal staven en de diameter die op dit stuk liggen.
 *
 * Een LEGE rij (0 staven) is geldig en betekent "hier ligt aan deze zijde
 * geen langswapening". Zo wordt een afgekorte staaf uitgedrukt: de zone
 * waar hij ligt draagt zijn staven, de zone erachter draagt er minder of
 * geen.
 */
row: RebarRow, 
/**
 * Begin van het staal langs de staaf, in mm vanaf het beginknoop.
 */
x_start_mm: number, 
/**
 * Einde van het staal langs de staaf, in mm vanaf het beginknoop.
 */
x_end_mm: number, 
/**
 * Vorm van de staafeinden — tabel 8.2, regel "Vorm van de staaf".
 *
 * Standaard [`Staafvorm::Recht`]. Een ombuiging of haak maakt α₁ = 0,7 bij
 * c_d > 3Φ en verkort l_bd dus met 30 %; dat mag alleen gelden als de
 * staaf werkelijk zo is gebogen, en dat weet alleen de tekenaar.
 */
bar_shape: Staafvorm, 
/**
 * Waar deze staven lagen ten opzichte van de stortrichting — figuur 8.2,
 * bepaalt η₁ in (8.2).
 *
 * Standaard [`Stortpositie::Onderzijde`], de gewone situatie bij werk ter
 * plaatse. Dit is het gegeven dat [`crate::verankering`] uitdrukkelijk PER
 * STAAF opgegeven wil hebben: dezelfde balk kan van bovenaf zijn gestort
 * of op zijn kant zijn geprefabriceerd, en dat scheelt in l_bd een factor
 * 1/0,7 = 1,43. Het model kan het niet afleiden, dus het staat hier.
 */
casting_position: Stortpositie, };
