// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { DesignSituation } from "./DesignSituation";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { SteelBranch } from "./SteelBranch";

/**
 * Verzoek om het M-N-κ-diagram van een korf, los van een staaf.
 */
export type MnKappaRequest = { 
/**
 * De nationale bijlage waarmee gerekend wordt (normnaad).
 *
 * Zij bepaalt γ_C, γ_S, α_cc en ε_ud van het materiaal (via
 * `DesignMaterial::new`). Een bijlage die deze uitgave niet kent, wordt bij
 * het lezen van het verzoek GEWEIGERD met reden; er wordt nooit stil op de
 * Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` om dezelfde reden als bij `ConcreteBeamCheckInput`:
 * er is één gevulde rij, dus weglaten kan niets anders betekenen. De test
 * `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg` in
 * `nationale-bijlage` valt om zodra dat niet meer waar is.
 */
bijlage: NationaleBijlage, 
/**
 * De doorsnede: rechthoek, T of L, met de maten die bij die vorm horen.
 */
section: ConcreteSectionInput, concrete_class: string, reinforcement_grade: string, cage: ReinforcementCage, 
/**
 * Normaalkracht waarbij het M-κ-diagram wordt bepaald (kN, trek positief).
 */
n_ed_kn: number, 
/**
 * Richting van het moment: +1 trek onder (standaard), −1 trek boven.
 */
moment_sign: number, n_strips: number, steel_branch: SteelBranch, design_situation: DesignSituation, 
/**
 * Aantal punten van het N-M-interactiediagram (0 = niet berekenen).
 */
interaction_points: number, };
