// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén punt van het M-κ-diagram.
 */
export type MnKappaPoint = { kappa_per_m: number, m_knm: number, 
/**
 * Drukrek boven en onder (druk positief), dimensieloos.
 */
eps_top: number, eps_bottom: number, 
/**
 * Hoogte van de drukzone vanaf de gedrukte rand, mm (0 als er geen druk is).
 */
x_mm: number, };
