// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welk bewijs de weerstandbiedende trekkracht op een plaats levert —
 * §9.2.1.3(1) of §9.2.1.3(3).
 */
export type MomentBewijs = "GeenWapening" | "VolledigOntwikkeld" | "BinnenVerankeringslengte";
