// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MomentBewijs } from "./MomentBewijs";
import type { Snedezijde } from "./Snedezijde";
import type { ZGrondslag } from "./ZGrondslag";

/**
 * Eén plaats op de MOMENTdekkingslijn, voor één zijde van de doorsnede.
 *
 * Dit is figuur 9.2 als getallen. `omhullende_kn` is regel A, `benodigd_kn`
 * regel B (A ná de verschuiving over a_l) en `aanwezig_kn` regel C.
 */
export type Momentpunt = { 
/**
 * Plaats langs de staaf, mm vanaf de beginknoop.
 */
x_mm: number, 
/**
 * Aan welke kant van een sprong dit punt ligt.
 */
zijde: Snedezijde, 
/**
 * Regel A — de omhullende van M_Ed/z + N_Ed op deze plaats zelf, kN.
 */
omhullende_kn: number, 
/**
 * Regel B — F_s, de optredende trekkracht ná de verschuiving over a_l, kN.
 */
benodigd_kn: number, 
/**
 * Regel C — F_Rs, de weerstandbiedende trekkracht, kN.
 */
aanwezig_kn: number, 
/**
 * Wat de hier liggende staven zouden leveren als zij volledig ontwikkeld
 * waren, kN. Het verschil met `aanwezig_kn` is precies wat het lineaire
 * krachtverloop van 9.2.1.3(3) van hen afhaalt.
 */
aanwezig_volledig_kn: number, 
/**
 * De laagste ontwikkelingsfractie van de bundels die hier liggen, 0…1.
 */
ontwikkeling: number, 
/**
 * F_s/F_Rs. Leeg als er geen wapening ligt — dan is er geen verhouding,
 * alleen een tekort.
 */
uc?: number, 
/**
 * max(0; F_s − F_Rs), kN.
 */
tekort_kn: number, 
/**
 * Welk bewijs hier gold.
 */
bewijs: MomentBewijs, 
/**
 * De inwendige hefboomsarm z waarmee M_Ed hier op kracht is omgerekend, mm.
 */
z_mm: number, 
/**
 * Waar die z vandaan komt — 6.2.3(1).
 */
z_grondslag: ZGrondslag, 
/**
 * De werkelijke, onbegrensde hefboomsarm uit het spanningsblok bij N_Ed,
 * mm. Alleen gevuld bij `Evenwicht` en `EvenwichtBegrensd`.
 */
z_werkelijk_mm?: number, 
/**
 * De normaalkracht van de maatgevende combinatie op deze plaats, kN (trek
 * positief). Een DRUKkracht is NIET in `omhullende_kn` verrekend: het
 * aftrekken van de volle drukkracht van de trekgordel veronderstelt een
 * doorsnede-evenwicht dat deze lijn niet maakt. Niet verrekenen is de
 * veilige kant; de waarde staat er zodat het rapport kan tonen wat er is
 * weggelaten.
 */
n_ed_kn: number, 
/**
 * Het buigend moment van de maatgevende combinatie op deze plaats, kNm.
 */
m_ed_knm: number, 
/**
 * De combinatie die `omhullende_kn` op deze plaats leverde.
 */
combinatie_id: number, 
/**
 * Ligt dit punt binnen l_bd van een STAAFEINDE? Daar geldt niet de vrije
 * dekkingslijn maar §9.2.1.4/§9.2.1.5 — zie `steunpunten`.
 */
in_eindzone: boolean, };
