// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Momentpunt } from "./Momentpunt";
import type { RebarSide } from "./RebarSide";
import type { Staafbundel } from "./Staafbundel";

/**
 * De momentendekking van één zijde van de doorsnede.
 */
export type Momentdekking = { 
/**
 * Boven- of onderwapening.
 */
side: RebarSide, 
/**
 * De lijn, oplopend in x. Op een sprong staan twee punten met dezelfde x.
 */
punten: Array<Momentpunt>, 
/**
 * De maatgevende plaats — de index in `punten` met de hoogste unity check
 * BUITEN de eindzones.
 *
 * De eindzones blijven erbuiten omdat de norm ze elders regelt: binnen
 * l_bd van een staafeinde geldt §9.2.1.4/§9.2.1.5 en niet de vrije
 * dekkingslijn. Zonder die uitzondering zou het maatgevende punt altijd
 * x = 0 zijn, waar de weerstandslijn per definitie bij nul begint.
 */
maatgevend?: number, 
/**
 * De bundels waaruit de weerstandslijn is opgebouwd.
 */
bundels: Array<Staafbundel>, 
/**
 * Kanttekeningen bij deze zijde.
 */
toelichting: Array<string>, };
