// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén toets die niet uitgevoerd kon worden.
 *
 * De REDEN staat niet hier maar in de `notes` van die toets in `checks` — daar
 * zet de kern hem neer, in de bewoording van de kern. Hem hier overschrijven
 * zou een tweede versie van dezelfde tekst opleveren, en hem eruit raden
 * (de eerste note? de laatste?) zou stil de verkeerde regel kunnen kiezen: de
 * ene toets zet zijn reden als enige note neer, de dwarskrachttoets zet er
 * eerst de vormaannamen en er achteraf de getoetste snede omheen. Deze lijst
 * is dus een VERWIJZING: zoek `check_id` op in `checks` en toon zijn notes.
 */
export type NietUitgevoerdeToets = { 
/**
 * De `id` van de toets, bijvoorbeeld "6.2_shear".
 */
check_id: string, 
/**
 * De titel van de toets, zoals het rapport hem toont ("Dwarskracht").
 */
titel: string, 
/**
 * Is dit een detailleringseis (§8.2, §9.2, §9.5)? Die bepalen de
 * staafstatus niet: ze begrenzen de UITVOERING, niet de draagkracht, en
 * een eis die niet van toepassing is zegt niets over de draagkracht van
 * de staaf.
 */
detaillering: boolean, };
