// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Op welke sterkte- en stijfheidswaarden de (3.14)-kromme is gebaseerd.
 *
 * * [`NonlinearBasis::DesignValues`] — 5.8.6(3): "Met spanning-rekdiagrammen
 *   gebaseerd op rekenwaarden, is uit de berekening direct een rekenwaarde
 *   van de bezwijkbelasting verkregen. In vergelijking (3.14) en in de
 *   k‑waarde is f_cm dan vervangen door de rekenwaarde van de druksterkte
 *   f_cd, en E_cm door E_cd = E_cm/γ_cE (5.20)." Voor de uiterste
 *   grenstoestand.
 * * [`NonlinearBasis::MeanValues`] — 3.1.5 zoals hij er staat, met f_cm en
 *   E_cm uit tabel 3.1. Voor de bruikbaarheidsgrenstoestand, waar 7.4.3 de
 *   vervormingsberekening op gemiddelde eigenschappen baseert ("In het
 *   algemeen zal de beste schatting van het gedrag zijn verkregen indien
 *   f_ctm is gebruikt", 7.4.3(4)).
 */
export type NonlinearBasis = "DesignValues" | "MeanValues";
