// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Een betonstaaf die NIET meerekende, met de reden. Spiegel van `CheckSkip`.
 *
 * Zonder deze lijst zou het hoofdstuk stilzwijgend over een betonstaaf heen
 * stappen, en dat is erger dan een lange lijst: de lezer ziet dan niet dat
 * die staaf de ongescheurde stijfheid heeft gehouden.
 */
export type OvergeslagenStaaf = { beam_id: number, 
/**
 * Woordelijk de reden die de frontend heeft vastgesteld.
 */
reden: string, };
