// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * M₀Eqp van één quasi-blijvende combinatie (6.16b), eerste orde, op de
 * doorsnede van [`Kruip519Invoer::x_mm`].
 */
export type QuasiBlijvendMoment = { 
/**
 * Naam van de quasi-blijvende combinatie, voor het rapport.
 */
combinatie: string, 
/**
 * Eerste-orde-moment in kNm, zelfde tekenconventie als M₀Ed.
 */
m0_eqp_knm: number, };
