// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén rij hoofdwapening: aantal staven en diameter.
 *
 * `Default` is de LEGE rij (0 staven, Ø 0) — geen bruikbare wapening, maar
 * wel wat [`ReinforcementCage::default`] nodig heeft om te bestaan.
 */
export type RebarRow = { count: number, diameter_mm: number, };
