// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De zijde waaraan een langswapeningszone ligt.
 *
 * Dezelfde tweedeling als [`ReinforcementCage::top`] en
 * [`ReinforcementCage::bottom`]: `Bottom` is de zijde z = 0, `Top` de zijde
 * z = h. De zijde is nodig omdat boven- en onderwapening onafhankelijk van
 * elkaar inkorten — bij een doorgaande ligger loopt de bovenwapening juist
 * dóór waar de onderwapening ophoudt.
 */
export type RebarSide = "Bottom" | "Top";
