// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LongitudinalZone } from "./LongitudinalZone";
import type { StirrupZone } from "./StirrupZone";

/**
 * De wapening die LANGS de staaf verandert, in twee gescheiden lijsten.
 *
 * **Beide lijsten leeg is het gedrag van vóór dit type**: dan geldt de korf
 * van de staaf onveranderd over de hele lengte en levert
 * [`Self::cage_at_mm`] op elke plaats diezelfde korf terug. Elke bestaande
 * aanroeper blijft daardoor werken zonder wijziging, en `Default` is die lege
 * stand.
 *
 * De twee lijsten staan los van elkaar: een gevulde beugellijst zegt niets
 * over de langswapening en andersom. Zie de toelichting boven dit blok voor
 * waarom het er twee zijn en geen één.
 */
export type ReinforcementZones = { 
/**
 * De langswapening per stuk — §9.2.1.3. Leeg = de rijen `top` en `bottom`
 * van de korf gelden over de hele staaf.
 */
longitudinal: Array<LongitudinalZone>, 
/**
 * De beugels per stuk — §9.2.2. Leeg = de beugelvelden van de korf gelden
 * over de hele staaf.
 */
stirrups: Array<StirrupZone>, };
