// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuctilityClass } from "./DuctilityClass";

/**
 * Eén wapeningsstaalsoort: vloeigrens plus de ductiliteitseigenschappen
 * van tabel C.1.
 */
export type ReinforcementGrade = { 
/**
 * Aanduiding, bijv. "B500B".
 */
name: string, 
/**
 * Karakteristieke vloeigrens f_yk in N/mm² (3.2.2(3): 400 t/m 600).
 */
f_yk: number, ductility_class: DuctilityClass, 
/**
 * Minimumwaarde van k = (f_t/f_y)_k (tabel C.1): A ≥ 1,05; B ≥ 1,08;
 * C ≥ 1,15 (en < 1,35). Gebruikt voor de hellende bovenste tak van
 * 3.2.7(2)a; de minimumwaarde is de veilige keuze.
 */
k: number, 
/**
 * Karakteristieke rek bij maximale kracht ε_uk (tabel C.1):
 * A ≥ 2,5 %; B ≥ 5,0 %; C ≥ 7,5 %. Dimensieloos.
 */
eps_uk: number, };
