// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaceCover } from "./FaceCover";
import type { RebarRow } from "./RebarRow";

/**
 * Wapeningskorf: dekking, beugel, boven- en onderwapening.
 *
 * # `Default` is een LEGE korf, geen standaardkorf
 *
 * `ReinforcementCage::default()` levert dekking 0, geen beugel en geen
 * hoofdwapening. Dat is met opzet géén bruikbare korf: [`Self::validate`]
 * weigert hem met "de korf bevat geen hoofdwapening". `Default` bestaat
 * alleen zodat code die de beugelvelden niet invult
 * `..ReinforcementCage::default()` kan schrijven; er is nergens in de norm
 * een standaardkorf, en die zou hier ook niet mogen ontstaan.
 */
export type ReinforcementCage = { 
/**
 * Nominale betondekking c_nom op de beugel, in mm (§4.4.1) — de dekking
 * van het ELEMENT.
 *
 * Dit is de dekking die geldt aan elke zijde die niets eigens zegt. Wie
 * niets anders invult, heeft dus precies wat hij vroeger had: één dekking
 * rondom. Zie [`Self::cover_at_mm`] en [`crate::dekking::CoverSide`] voor
 * wanneer een zijde ervan afwijkt.
 */
cover_mm: number, 
/**
 * De eigen dekking en milieuklasse van de BOVENZIJDE (z = h). `None` =
 * niet opgegeven; die van het element gelden dan.
 *
 * 4.4.1.1(1)P meet de dekking tot "het dichtstbijzijnde betonoppervlak";
 * bij een vloer met de bovenzijde binnen (XC1) en de onderzijde buiten
 * (XC4) zijn dat twee verschillende eisen en dus twee verschillende
 * nuttige hoogtes. Leeg = het gedrag van vóór dit veld — dezelfde
 * afspraak als bij de vier beugelvelden hieronder, en dezelfde vorm
 * (`Option` met `#[serde(default)]`), zodat een projectbestand dat het
 * veld niet kent er niet over struikelt.
 */
cover_top?: FaceCover, 
/**
 * Idem voor de ONDERZIJDE (z = 0).
 */
cover_bottom?: FaceCover, 
/**
 * Idem voor de twee verticale ZIJKANTEN samen.
 *
 * Zij bepalen niet de nuttige hoogte maar de dwarsafstand van de
 * beugelbenen (§9.2.2(8)), de vrije staafafstand (§8.2(2)) en de
 * binnenmaat waarin een rij staven moet passen. Waarom links en rechts
 * niet apart staan, staat bij [`crate::dekking::CoverSide`].
 */
cover_sides?: FaceCover, 
/**
 * Beugeldiameter in mm (0 = geen beugel; de hoofdwapening ligt dan direct
 * achter de dekking).
 */
stirrup_diameter_mm: number, 
/**
 * Bovenwapening (aan de zijde z = h).
 */
top: RebarRow, 
/**
 * Onderwapening (aan de zijde z = 0).
 */
bottom: RebarRow, 
/**
 * Wapening langs de twee verticale ZIJKANTEN — de staven die van een
 * balkkorf een KOLOMkorf maken. `None` = ze zijn er niet, en dat is
 * letterlijk het gedrag van vóór dit veld.
 *
 * # `count` is het aantal staven op ÉÉN zijkant
 *
 * De korf wordt links-rechts symmetrisch verondersteld, dus in de
 * doorsnede liggen er tweemaal zoveel. "4Ø20 boven, 4Ø20 onder, 2Ø16 per
 * zijde" is dus een kolom met 12 staven — precies zoals een constructeur
 * een kolom uitschrijft. [`Self::a_s_sides_mm2`] rekent daarom met het
 * DUBBELE van het rijoppervlak.
 *
 * # De hoekstaven zitten hier NIET in
 *
 * Die horen bij [`Self::top`] en [`Self::bottom`]; deze rij telt alleen
 * de staven ertussen. Zonder die afspraak zou een hoekstaaf twee keer in
 * A_s meetellen en zou §9.5.2(4) niet meer te toetsen zijn — de vraag
 * "staat er in iedere hoek een staaf" is dan de vraag of de boven- en de
 * onderrij elk minstens twee staven hebben.
 *
 * # Waarom dit een `Option` met `serde(default)` is
 *
 * Dezelfde afspraak als bij de beugelvelden en de dekking per zijde: de
 * struct draagt `deny_unknown_fields`, en een projectbestand van vóór dit
 * veld moet zonder wijziging inleesbaar blijven. `None` en
 * `Some(lege rij)` betekenen hetzelfde en worden door
 * [`Self::side_row`] meteen gelijkgeschakeld.
 */
sides?: RebarRow, 
/**
 * Hart-op-hartafstand s van de beugels, gemeten LANGS de lengteas, in mm
 * (§9.2.2(5), symbool s in (9.4); begrensd door s_l,max in §9.2.2(6)).
 *
 * `None` = niet opgegeven. Dat is iets anders dan 0 (dat zou een
 * oneindige hoeveelheid wapening betekenen) en iets anders dan een
 * aangenomen waarde: de norm geeft geen aanbevolen s, alleen een
 * bovengrens. Zonder s zijn A_sw/s in (6.8) en ρ_w in (9.4) onbepaald.
 */
stirrup_spacing_mm?: number, 
/**
 * Aantal beugelbenen n dat één verticale doorsnede kruist.
 *
 * §9.2.2(5) omschrijft A_sw als "de oppervlakte van de doorsnede van de
 * dwarskrachtwapening binnen de lengte s"; bij een gesloten tweebenige
 * beugel is dat 2·(π/4)·Ø², bij een vierbenige het dubbele. Dit getal is
 * uit dekking of diameter niet af te leiden en is de grootste enkele
 * foutbron in een dwarskrachttoets: hij schaalt V_Rd,s recht evenredig.
 *
 * `None` = niet opgegeven.
 */
stirrup_legs?: number, 
/**
 * Hart-op-hartafstand s_t van de beugelbenen in DWARSRICHTING, in mm
 * (§9.2.2(8); de nationale bijlage begrenst hem op 500 mm).
 *
 * `None` = niet opgegeven. Bij een gesloten tweebenige beugel is s_t
 * zuivere meetkunde en hoeft hij niet te worden gevraagd; zie
 * [`Self::leg_spacing_mm`]. Bij meer benen hangt hij af van de verdeling
 * over de breedte en is hij niet af te leiden.
 */
stirrup_leg_spacing_mm?: number, 
/**
 * Karakteristieke vloeigrens f_ywk van de DWARSKRACHTWAPENING, in N/mm².
 *
 * `None` = dezelfde staalsoort als de langswapening. De beugelkwaliteit
 * mág afwijken en is niet uit de langswapening af te leiden, dus het veld
 * bestaat; maar `None` is hier geen ontbrekend gegeven, want de
 * staalsoort van de staaf is wél bekend. Wie het invult, moet het in de
 * afleiding terugzien.
 */
stirrup_fywk_mpa?: number, };
