// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Draagt dit element bij aan de horizontale stabiliteit? (§5.8.1)
 *
 * **Geen `Default`.** Dat is opzet. Een standaardwaarde zou een
 * ontwerpbesluit stilzwijgend voor de constructeur nemen, en het besluit is
 * niet neutraal: [`Schoring::Ongeschoord`] dwingt C = 0,7 af en verlaagt
 * λ_lim, [`Schoring::Geschoord`] geeft de gunstigere kniklengteformule. Wie
 * niets invult, hoort een lege invoer te zien en geen aangenomen antwoord.
 */
export type Schoring = "Geschoord" | "Ongeschoord";
