// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De drie takken van s_cl,tmax, zodat de afleiding kan tonen wélke wint.
 */
export type ScltmaxTak = "TwintigMaalDiameter" | "KleinsteKolomafmeting" | "Plafond400";
