// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Toestand van één segment. De volgorde is oplopend in ernst; het antwoord
 * van de hele ronde neemt de zwaarste over.
 */
export type SegmentStatus = "Layout" | "Uncracked" | "Cracked" | "BeyondEpsCu1" | "Failed";
