// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConcreteSectionInput } from "./ConcreteSectionInput";
import type { DesignSituation } from "./DesignSituation";
import type { Kruip519Invoer } from "./Kruip519Invoer";
import type { LoadDuration } from "./LoadDuration";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { NonlinearBasis } from "./NonlinearBasis";
import type { ReinforcementCage } from "./ReinforcementCage";
import type { SegmentForces } from "./SegmentForces";
import type { SteelBranch } from "./SteelBranch";

/**
 * Eén stateloos verzoek om de segmentstijfheden van één betonstaaf.
 *
 * `deny_unknown_fields`: er staan hier tien velden met een standaardwaarde,
 * en een tikfout in één daarvan zou zonder deze strengheid stilzwijgend op de
 * standaard terugvallen — met een andere stijfheid als gevolg.
 */
export type SegmentStiffnessRequest = { 
/**
 * De nationale bijlage waarmee gerekend wordt (normnaad).
 *
 * Zij bepaalt γ_C, γ_S, α_cc en ε_ud van het materiaal (via
 * `DesignMaterial::new`). Een bijlage die deze uitgave niet kent, wordt bij
 * het lezen van het verzoek GEWEIGERD met reden; er wordt nooit stil op de
 * Nederlandse waarden teruggevallen.
 *
 * `#[serde(default)]` om dezelfde reden als bij `ConcreteBeamCheckInput`:
 * er is één gevulde rij, dus weglaten kan niets anders betekenen. De test
 * `zodra_er_een_tweede_bijlage_is_moet_de_serde_default_weg` in
 * `nationale-bijlage` valt om zodra dat niet meer waar is.
 */
bijlage: NationaleBijlage, 
/**
 * Staafnummer; komt onveranderd terug in het antwoord.
 */
beam_id: number, 
/**
 * De doorsnede: rechthoek, T of L, met de maten die bij die vorm horen.
 * De ongescheurde stijfheid E_c·I_c waarmee de eerste ronde begint volgt
 * uit de WERKELIJKE meetkunde van deze vorm.
 */
section: ConcreteSectionInput, 
/**
 * Betonsterkteklasse, bijv. "C30/37" (tabel 3.1).
 */
concrete_class: string, 
/**
 * Wapeningsstaal, bijv. "B500B" (bijlage C).
 */
reinforcement_grade: string, 
/**
 * Wapeningskorf: dekking, beugel, boven- en onderwapening.
 */
cage: ReinforcementCage, 
/**
 * Staaflengte in m.
 */
length_m: number, 
/**
 * Gewenste segmentlengte in mm; 400 als beginwaarde (besluit B3). De
 * werkelijke lengte volgt uit [`segment_layout`] en staat in het antwoord.
 */
target_segment_length_mm: number, 
/**
 * Vangnet: meer segmenten dan dit is een verzoekfout, geen berekening.
 */
max_segments: number, 
/**
 * Grenstoestand: `DesignValues` = UGT (5.8.6(3), f_cd en E_cd = E_cm/1,2,
 * geen betontrek), `MeanValues` = BGT (3.1.5/7.4.3, f_cm en E_cm, met de
 * tension stiffening van (7.18)). Nooit impliciet — de gebruikte variant
 * staat per segment in het antwoord.
 */
limit_state: NonlinearBasis, 
/**
 * Effectieve kruipcoëfficiënt volgens 5.8.4, verwerkt volgens 5.8.6(4).
 * Besluit B1 zet hem op 0; het antwoord meldt dat met zoveel woorden.
 *
 * Moet 0 blijven wanneer [`Self::kruip_5_19`] is meegestuurd: dan bepaalt
 * de kern φ_ef zelf, en twee bronnen voor één getal worden geweigerd.
 */
phi_ef: number, 
/**
 * φ_ef uit (5.19) met de werkelijke verhouding M₀Eqp/M₀Ed in plaats van
 * een vaste waarde — alleen in de UGT (`DesignValues`). Weggelaten = de
 * vaste `phi_ef` hierboven, zoals vóór issue #24.
 */
kruip_5_19?: Kruip519Invoer, 
/**
 * De krachten per segment uit de vorige raamwerkronde, in de volgorde van
 * de segmentindeling. **Leeg = ronde 0**: dan komt alleen de indeling
 * terug. Is de lijst niet leeg, dan moet hij precies zoveel elementen
 * tellen als er segmenten zijn; een afwijkende lengte is een fout en geen
 * stilzwijgende bijsnijding.
 */
segment_forces: Array<SegmentForces>, 
/**
 * De stijfheden van de vorige ronde, in dezelfde volgorde. Leeg = eerste
 * ronde met krachten; er is dan niets om tegen te convergeren.
 */
previous_ei_knm2: Array<number>, 
/**
 * Onderrelaxatie ω: `EI = EI_vorig + ω·(EI_berekend − EI_vorig)`.
 * 1,0 = geen relaxatie (beginwaarde). Alleen van kracht als er een vorige
 * ronde is. De onbewerkte waarde blijft in `ei_raw_knm2` staan.
 */
relaxation: number, 
/**
 * Convergentietolerantie op `max |ΔEI| / max(|EI|, |EI_vorig|)`.
 */
convergence_tolerance: number, 
/**
 * Ondergrens voor EI als fractie van E_c·I_c, om het globale stelsel
 * oplosbaar te houden. 0 = niet klemmen. Grijpt de klem in, dan is de
 * ronde per definitie niet geconvergeerd.
 */
min_ei_ratio: number, 
/**
 * Aantal stroken voor de integratie van de betonspanning.
 */
n_strips: number, 
/**
 * Bovenste tak van het staaldiagram (3.2.7(2)); standaard horizontaal.
 */
steel_branch: SteelBranch, 
/**
 * Ontwerpsituatie voor tabel 2.1N; standaard blijvend en tijdelijk.
 */
design_situation: DesignSituation, 
/**
 * β van (7.19); alleen in de BGT van invloed.
 */
load_duration: LoadDuration, };
