// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De snedekrachten van één segment, zoals de vorige raamwerkronde ze gaf.
 *
 * Tekenconventie gelijk aan `mechanics` en aan de rest van dit project:
 * **N positief = trek**, M positief = trek in de onderste vezel.
 */
export type SegmentForces = { 
/**
 * Normaalkracht in kN; trek positief, druk dus negatief.
 */
n_ed_kn: number, 
/**
 * Buigend moment in kNm om de sterke as; positief = trek onderin.
 */
m_ed_knm: number, };
