// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonlinearBasis } from "./NonlinearBasis";
import type { SegmentStatus } from "./SegmentStatus";
import type { SolveMethod } from "./SolveMethod";

/**
 * Eén segment: dit is letterlijk de rapporttabel.
 *
 * Alle rekengrootheden zijn `Option`. Dat is met opzet: in ronde 0 is er
 * niets gerekend, en een segment dat niet convergeert hoort géén getal te
 * leveren. Een nul of een NaN op die plek zou als antwoord kunnen worden
 * gelezen.
 */
export type SegmentStiffness = { 
/**
 * Volgnummer, 0-gebaseerd; dezelfde volgorde als `segment_forces`.
 */
index: number, 
/**
 * Beginafstand langs de staaf vanaf het staafbegin, mm.
 */
x_start_mm: number, 
/**
 * Eindafstand langs de staaf, mm.
 */
x_end_mm: number, 
/**
 * Midden van het segment, mm — de doorsnede waarin evenwicht en
 * compatibiliteit worden afgedwongen (5.8.6(6)).
 */
x_mid_mm: number, length_mm: number, 
/**
 * Normaalkracht in dit segment (kN, trek positief).
 */
n_ed_kn: number | null, 
/**
 * Buigend moment in dit segment (kNm).
 */
m_ed_knm: number | null, 
/**
 * Het moment bij κ = 0 om de geometrische middenvezel h/2. Bij een
 * asymmetrische korf onder druk is dit niet nul, en zonder deze correctie
 * is EI = M/κ fout.
 */
m0_knm: number | null, 
/**
 * Scheurmoment uit f_ctm, met de normaalkracht erin (kNm).
 */
m_cr_knm: number | null, 
/**
 * De gevonden kromming, 1/m.
 */
kappa_per_m: number | null, 
/**
 * EI = (M − M₀)/κ zoals de kern hem berekende, kNm² — vóór relaxatie en
 * vóór klemmen.
 */
ei_raw_knm2: number | null, 
/**
 * De EI die de aanroeper moet gebruiken, kNm² — ná relaxatie en klemmen.
 */
ei_knm2: number | null, 
/**
 * De EI van de vorige ronde, kNm².
 */
ei_previous_knm2: number | null, 
/**
 * |EI_raw − EI_vorig| / max(|EI_raw|, |EI_vorig|).
 */
relative_change: number | null, 
/**
 * Is |M_Ed| groter dan |M_cr|?
 */
cracked: boolean | null, 
/**
 * ζ van (7.19); alleen in de BGT gevuld (7.4.3(3)).
 */
zeta: number | null, 
/**
 * De gebruikte variant. Nooit impliciet, ook niet per segment.
 */
basis: NonlinearBasis, 
/**
 * Heeft de relaxatie de teruggegeven waarde verschoven?
 */
relaxed: boolean, 
/**
 * Heeft de ondergrens ingegrepen? Zo ja, dan is `ei_knm2` een verzinsel
 * dat het stelsel oplosbaar houdt en is de ronde niet geconvergeerd.
 */
clamped: boolean, 
/**
 * Ligt de grootste drukrek boven ε_cu1?
 */
beyond_eps_cu1: boolean, 
/**
 * Aantal iteraties van de krommingsoplosser.
 */
iterations: number, 
/**
 * Hoe de kromming is gevonden.
 */
method: SolveMethod | null, status: SegmentStatus, 
/**
 * Reden bij `Failed`, of een toelichting bij een ingreep.
 */
message: string | null, };
