// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kruip519Afleiding } from "./Kruip519Afleiding";
import type { LoadDuration } from "./LoadDuration";
import type { NonlinearBasis } from "./NonlinearBasis";
import type { SegmentRunStatus } from "./SegmentRunStatus";
import type { SegmentStiffness } from "./SegmentStiffness";

/**
 * Antwoord op [`SegmentStiffnessRequest`].
 */
export type SegmentStiffnessResponse = { beam_id: number, 
/**
 * Doorsnedenaam, bijv. "300 x 500".
 */
section_name: string, concrete_class: string, reinforcement_grade: string, 
/**
 * "onder 3Ø16, boven 2Ø12, beugel Ø8, dekking 30 mm".
 */
reinforcement_summary: string, length_m: number, 
/**
 * De gevraagde segmentlengte, mm.
 */
target_segment_length_mm: number, 
/**
 * De werkelijke segmentlengte, mm — L/n, voor elk segment gelijk.
 */
segment_length_mm: number, segment_count: number, 
/**
 * De regel die de indeling bepaalde, uitgeschreven voor het rapport.
 */
segmentation_rule: string, 
/**
 * De gebruikte grenstoestand en zijn omschrijving.
 */
limit_state: NonlinearBasis, limit_state_label: string, 
/**
 * β van (7.19).
 */
load_duration: LoadDuration, beta: number, 
/**
 * De effectieve kruipcoëfficiënt die in het diagram zit (5.8.6(4)).
 */
phi_ef: number, 
/**
 * Staat φ_ef op nul?
 */
creep_neglected: boolean, 
/**
 * De afleiding van φ_ef uit (5.19) als het verzoek `kruip_5_19` droeg;
 * `None` = er is met de vaste `phi_ef` van het verzoek gerekend.
 * `serde(default)`: een opgeslagen spoor van vóór dit veld blijft leesbaar.
 */
kruip_5_19: Kruip519Afleiding | null, 
/**
 * De verplichte vermelding uit besluit B1 — altijd gevuld, ook als er
 * mét kruip is gerekend.
 */
creep_note: string, 
/**
 * f_cd (UGT) of f_cm (BGT), N/mm².
 */
f_c_mpa: number, 
/**
 * E_cd = E_cm/1,2 (UGT) of E_cm (BGT), N/mm².
 */
e_c_mpa: number, 
/**
 * f_ctm volgens tabel 3.1, N/mm².
 */
f_ctm_mpa: number, 
/**
 * E_c·I_c van de bruto betondoorsnede, kNm². **Vergelijkingswaarde, geen
 * rekenwaarde**: in de UGT bestaat er geen ongescheurde tak, want
 * 5.8.6(5) laat de betontrek weg.
 */
ei_uncracked_knm2: number, 
/**
 * De toegepaste ondergrens in kNm² (`min_ei_ratio` × E_c·I_c).
 */
min_ei_knm2: number, relaxation: number, convergence_tolerance: number, 
/**
 * Zijn er krachten meegestuurd? Zo niet, dan is dit ronde 0.
 */
has_forces: boolean, segments: Array<SegmentStiffness>, 
/**
 * Zijn de stijfheden uitgeconvergeerd? Klemmen zet dit onvoorwaardelijk
 * op false.
 */
converged: boolean, 
/**
 * De grootste relatieve verandering over alle segmenten; leeg als er geen
 * vorige ronde was.
 */
max_relative_change: number | null, 
/**
 * Het segment waar die grootste verandering zit.
 */
governing_segment: number | null, clamped_count: number, failed_count: number, status: SegmentRunStatus, 
/**
 * Toelichtingen die in het rapport horen: de indelingsregel, een ingreep
 * van de klem, de reden van niet-convergeren.
 */
notes: Array<string>, };
