// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Toestand van de hele ronde.
 */
export type SegmentRunStatus = "Layout" | "Converged" | "NotConverged" | "Failed";
