// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén correctiefactor op de basiswaarde van (7.16), met de reden waarom hij
 * wél of NIET is toegepast.
 *
 * Een correctie die niet geldt, verdwijnt hier NIET uit het antwoord. Anders
 * zou de lezer niet kunnen zien of de norm haar heeft overwogen of dat de
 * implementatie haar is vergeten — en juist bij deze drie correcties gaat het
 * mis. Een niet toegepaste correctie staat er dus in met `factor = 1,0`,
 * `applied = false` en een reden.
 */
export type SlendernessCorrection = { 
/**
 * Stabiele sleutel: `"sigma_s"`, `"flens"`, `"lange_overspanning"`.
 */
id: string, 
/**
 * Nederlandse naam voor het rapport.
 */
label: string, 
/**
 * Vindplaats.
 */
article: string, 
/**
 * De factor waarmee de basiswaarde is vermenigvuldigd. 1,0 als de
 * correctie niet van toepassing is.
 */
factor: number, applied: boolean, 
/**
 * De formule van deze correctie MET DE GETALLEN INGEVULD, in LaTeX.
 * Zonder deze regel staat in het rapport wel de factor maar niet waar
 * hij vandaan komt, en juist bij deze drie correcties is dat de vraag.
 */
filled_latex: string, 
/**
 * Waarom wél of niet, in gewone taal.
 */
reason: string, };
