// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { DeflectionLimits } from "./DeflectionLimits";
import type { SlendernessCorrection } from "./SlendernessCorrection";
import type { SlendernessEquation } from "./SlendernessEquation";
import type { StructuralSystem } from "./StructuralSystem";

/**
 * Het antwoord: de hele keten van (7.16) en de correcties, met per stap de
 * vindplaats, plus het oordeel en de grenswaarden waar het voor staat.
 */
export type SlendernessResponse = { beam_id: number, system: StructuralSystem, 
/**
 * De woordelijke tabelregel van tabel 7.4N.
 */
system_label: string, 
/**
 * K uit tabel 7.4N.
 */
k: number, f_ck_mpa: number, 
/**
 * ρ₀ = 10⁻³·√f_ck.
 */
rho_0: number, rho: number, rho_prime: number, 
/**
 * Welke tak van (7.16) gold.
 */
equation: SlendernessEquation, 
/**
 * De basiswaarde uit (7.16), inclusief K en vóór de correcties.
 */
base_l_over_d: number, 
/**
 * De drie correcties, ook die welke NIET zijn toegepast.
 */
corrections: Array<SlendernessCorrection>, 
/**
 * De grenswaarde van de slankheid: `base_l_over_d` maal alle factoren.
 */
limit_l_over_d: number, 
/**
 * De werkelijke slankheid l/d.
 */
actual_l_over_d: number, span_mm: number, d_mm: number, 
/**
 * (l/d)_werkelijk / (l/d)_grens. Groter dan 1 = te slank.
 */
unity_check: number, status: CheckStatus, 
/**
 * De grenswaarden van 7.4.1(4) en (5) waarvoor deze toets in de plaats
 * komt.
 */
deflection_limits: DeflectionLimits, 
/**
 * Wat er bij deze uitkomst hoort te worden verteld: de aannamen, de
 * voorwaarden die NIET zijn gecontroleerd, en wat er gebeurt als de
 * toets niet slaagt.
 */
notes: Array<string>, };
