// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructuralSystem } from "./StructuralSystem";

/**
 * Eén verzoek om de slankheidstoets van 7.4.2.
 *
 * `deny_unknown_fields`: een tikfout in `rho_prime` zou anders stilzwijgend
 * 0 opleveren, en dan valt (7.16.b) terug op een doorsnede zonder
 * drukwapening — een lagere en dus verkeerde grenswaarde, zonder enig
 * signaal.
 *
 * DE OPTIONELE VELDEN BETEKENEN "NIET OPGEGEVEN", niet "nul". Elk van hen
 * leidt tot een eigen aantekening in het antwoord, zodat een ontbrekend
 * gegeven zichtbaar is in plaats van weggemoffeld.
 */
export type SlendernessRequest = { 
/**
 * Vrij te kiezen nummer; komt onveranderd terug. 0 als het niet om een
 * staaf uit een model gaat.
 */
beam_id: number, 
/**
 * De regel uit tabel 7.4N. Zie [`StructuralSystem`]: dit is invoer.
 */
system: StructuralSystem, 
/**
 * f_ck in MPa — de norm schrijft dat achter (7.16) letterlijk voor.
 */
f_ck_mpa: number, 
/**
 * De te toetsen overspanning l, in mm. Bij in twee richtingen dragende
 * platen de KORTSTE, bij vlakke plaatvloeren de LANGSTE (OPMERKING 2 bij
 * tabel 7.4N).
 */
span_mm: number, 
/**
 * De nuttige hoogte d, in mm.
 */
d_mm: number, 
/**
 * ρ: de VEREISTE wapeningsverhouding van de trekwapening in het midden
 * van de overspanning (bij uitkragingen ter plaatse van de oplegging)
 * waarmee het moment ten gevolge van de REKENWAARDE van de belastingen
 * kan zijn opgenomen. Dimensieloos (0,005 = 0,5 %).
 *
 * De norm laat in het midden ten opzichte van welke oppervlakte deze
 * verhouding is genomen; deze module kiest die oppervlakte daarom NIET
 * maar neemt ρ als gegeven aan. Wie hem uit A_s,req berekent, hoort erbij
 * te vermelden welke breedte hij heeft gebruikt.
 */
rho: number, 
/**
 * ρ': de VEREISTE wapeningsverhouding van de drukwapening op dezelfde
 * plaats. Dimensieloos. Ontbreekt het veld, dan 0 — geen drukwapening.
 * Wordt alleen door (7.16.b) gebruikt.
 */
rho_prime: number, 
/**
 * σ_s in MPa, indien expliciet bepaald: de trekspanning in het staal in
 * het midden van de overspanning onder de rekenwaarde van de belasting
 * in de BGT. Is dit veld gevuld, dan gaat 310/σ_s vóór op (7.17).
 */
sigma_s_mpa: number | null, 
/**
 * f_yk in MPa, voor de conservatieve aanname (7.17).
 */
f_yk_mpa: number | null, 
/**
 * A_s,req in mm²: de staaldoorsnede die in de beschouwde doorsnede voor
 * de UITERSTE grenstoestand is vereist. Voor (7.17).
 */
a_s_req_mm2: number | null, 
/**
 * A_s,prov in mm²: de staaldoorsnede die in de beschouwde doorsnede
 * aanwezig is. Voor (7.17).
 */
a_s_prov_mm2: number | null, 
/**
 * De flensbreedte, mm. Bij een rechthoek gelijk aan `b_web_mm`. Uit
 * [`crate::ConcreteSection::b_mm`].
 */
b_flange_mm: number, 
/**
 * De ribbreedte (lijfbreedte), mm. Uit
 * [`crate::ConcreteSection::b_w_mm`].
 */
b_web_mm: number, 
/**
 * l_eff volgens 5.3.2.2(1), in mm. `None` = niet opgegeven; dan wordt
 * `span_mm` gebruikt en zegt het antwoord dat erbij. LET OP: de norm
 * vult l_eff in de correcties in METERS in; de omrekening gebeurt in
 * deze module.
 */
l_eff_mm: number | null, 
/**
 * Draagt dit element scheidingswanden die bij overmatige doorbuiging
 * kunnen zijn beschadigd? Voorwaarde voor de correcties 7/l_eff en
 * 8,5/l_eff.
 *
 * `None` = niet vastgesteld. Ligt de overspanning boven de drempel, dan
 * wordt de correctie in dat geval AAN DE VEILIGE KANT tóch toegepast en
 * staat dat met zoveel woorden in de reden — een niet toegepaste
 * correctie levert immers een hógere en dus gunstiger grenswaarde op.
 */
carries_brittle_partitions: boolean | null, 
/**
 * N_Ed in kN in de beschouwde doorsnede, TREK POSITIEF (de
 * tekenconventie van deze crate aan de buitengrens). `None` = niet
 * opgegeven; dan kan de voorwaarde "zonder normaaldruk" van tabel 7.4N
 * niet worden gecontroleerd en zegt het antwoord dat.
 */
n_ed_kn: number | null, };
