// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welke tak van (7.16) is gebruikt.
 */
export type SlendernessEquation = "Eq716a" | "Eq716b";
