// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aan welke kant van een sprong een punt ligt.
 *
 * Op een zonegrens verandert de korf en SPRINGT de weerstand. Interpoleren
 * over een sprong heeft geen betekenis; er staan daarom twee punten op
 * dezelfde `x_mm`, met deze aanduiding erbij. Wie de lijn tekent, moet die
 * twee punten met een verticaal stuk verbinden en niet met een schuine lijn.
 */
export type Snedezijde = "Enkel" | "Links" | "Rechts";
