// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hoe de kromming is gevonden.
 *
 * Serde en ts-rs staan erop om dezelfde reden als bij [`LoadDuration`]: het
 * segmentantwoord meldt per segment of de snelle weg is genomen of dat er is
 * teruggevallen op de insluiting. Dat is de vroegste zichtbare aanwijzing dat
 * een segment tegen de top van zijn M-κ-diagram aanloopt.
 */
export type SolveMethod = "Newton" | "Bisection";
