// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welk spoor van 6.2.1(3)/(5) geldt — de ONTWERPvraag, los van de
 * weerstandsroute.
 *
 * Een doorsnede met V_Ed ≤ V_Rd,c die tóch beugels draagt, staat in
 * [`Spoor::GeenBerekendeWapening`] en kan niettemin
 * [`Weerstandsroute::Dwarskrachtwapening`] zijn.
 */
export type Spoor = "GeenBerekendeWapening" | "Vakwerkmodel";
