// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De vorm van het staafeinde volgens de regel "Vorm van de staaf" in tabel 8.2.
 */
export type Staafvorm = "Recht" | "AndersDanRecht";
