// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebarSide } from "./RebarSide";
import type { Verankeringsafleiding } from "./Verankeringsafleiding";

/**
 * Eén staafbundel: een groep staven met dezelfde diameter die over hetzelfde
 * stuk staaf doorloopt.
 *
 * Dit is de eenheid waarin figuur 9.2 denkt, en zij is NIET hetzelfde als een
 * wapeningszone. Een zone zegt hoevéél staven er op een stuk liggen; een
 * bundel zegt wélke staven het zijn. Loopt de onderwapening van 3Ø16 naar
 * 5Ø16 en weer terug naar 3Ø16, dan zijn dat drie zones maar twee bundels: 3Ø16
 * over de hele lengte en 2Ø16 in het veld. Alleen die tweede bundel heeft
 * staafeinden in het veld, en alleen dáár loopt de weerstandslijn schuin.
 */
export type Staafbundel = { 
/**
 * Boven- of onderwapening.
 */
side: RebarSide, 
/**
 * Aantal staven in deze bundel.
 */
aantal: number, 
/**
 * Staafdiameter Φ, mm.
 */
diameter_mm: number, 
/**
 * A_s van de bundel, mm².
 */
a_s_mm2: number, 
/**
 * Begin van het staal, mm vanaf de beginknoop.
 */
x_start_mm: number, 
/**
 * Einde van het staal, mm vanaf de beginknoop.
 */
x_end_mm: number, 
/**
 * De rekenwaarde van de verankeringslengte, mm.
 */
l_bd_mm: number, 
/**
 * De volle trekkracht A_s·f_yd van de bundel, kN — de hoogte van de
 * trapeziumlijn waar de bundel volledig is ontwikkeld.
 */
f_rs_vol_kn: number, 
/**
 * De hele afleiding van l_bd volgens §8.4.
 */
verankering: Verankeringsafleiding, 
/**
 * "onderwapening 2Ø16 van 1000 tot 4000 mm, l_bd = 705 mm".
 */
label: string, 
/**
 * Kanttekeningen bij deze bundel.
 */
toelichting: Array<string>, };
