// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Keuze van de bovenste tak van het staaldiagram, 3.2.7(2), figuur 3.8.
 */
export type SteelBranch = "Horizontal" | "Inclined";
