// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Staafeinde } from "./Staafeinde";

/**
 * De eis van §9.2.1.4 en §9.2.1.5 aan één staafuiteinde.
 *
 * §9.2.1.5(1) verklaart de oppervlakte-eis van §9.2.1.4(1) uitdrukkelijk ook
 * van toepassing op TUSSENsteunpunten, dus deze eis geldt aan elk uiteinde
 * zonder dat er hoeft te worden geweten wat voor steunpunt daar zit. Wat wél
 * van het soort steunpunt afhangt is de vereiste verankeringsLENGTE, en die
 * wordt gemeten vanaf de raaklijn tussen balk en oplegging (§9.2.1.4(3)) — een
 * maat die dit model niet heeft. Beide kandidaten worden daarom GEMELD en er
 * wordt geen oordeel over de lengte geveld.
 */
export type SteunpuntEis = { 
/**
 * Welk uiteinde.
 */
uiteinde: Staafeinde, 
/**
 * De plaats, mm.
 */
x_mm: number, 
/**
 * A_s,veld: de grootste onderwapening die ergens in de overspanning ligt, mm².
 */
a_s_veld_mm2: number, 
/**
 * β₂·A_s,veld met β₂ = 0,25 — §9.2.1.4(1) met de nationale bijlage.
 */
a_s_vereist_mm2: number, 
/**
 * De onderwapening die hier werkelijk ligt, mm².
 */
a_s_aanwezig_mm2: number, 
/**
 * Voldoet de oppervlakte-eis?
 */
voldoet_oppervlakte: boolean, 
/**
 * F_Ed volgens (9.3) — de hier te verankeren trekkracht, kN.
 */
f_ed_kn: number, 
/**
 * |V_Ed| waarmee (9.3) is ingevuld, kN.
 */
v_ed_kn: number, 
/**
 * N_Ed waarmee (9.3) is ingevuld, kN (trek positief).
 */
n_ed_kn: number, 
/**
 * a_l zoals gebruikt, mm.
 */
a_l_mm: number, 
/**
 * z zoals gebruikt, mm.
 */
z_mm: number, 
/**
 * l_bd van de staven die hier eindigen, mm — de lengte die §9.2.1.4(3)
 * eist, te meten vanaf de raaklijn tussen balk en oplegging. Leeg als er
 * hier geen onderwapening ligt.
 */
l_bd_mm?: number, 
/**
 * 10Φ — de ondergrens van §9.2.1.5(2) voor RECHTE staven bij een
 * tussensteunpunt, mm. Leeg als er hier geen onderwapening ligt.
 */
min_lengte_recht_mm?: number, 
/**
 * Kanttekeningen.
 */
toelichting: Array<string>, };
