// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén ronde van de lus — spiegel van `StijfheidRonde` in de store.
 */
export type StijfheidRonde = { 
/**
 * 1-gebaseerd; ronde 0 is de indeling en telt niet als oplossing mee.
 */
ronde: number, 
/**
 * De grootste relatieve verandering van EI over alle staven en segmenten.
 * Leeg in de eerste ronde: er is dan niets om tegen te vergelijken.
 */
max_relatieve_verandering: number | null, 
/**
 * Zeiden ALLE staven van de kern dat deze ronde geconvergeerd is?
 */
geconvergeerd: boolean, };
