// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonlinearBasis } from "./NonlinearBasis";
import type { SegmentStiffnessResponse } from "./SegmentStiffnessResponse";
import type { StijfheidRonde } from "./StijfheidRonde";

/**
 * Wat één belastingcombinatie fysisch niet-lineair opleverde — spiegel van
 * `StijfheidCombinatie` in de store.
 */
export type StijfheidCombinatie = { combinatie_id: number, combinatie_naam: string, 
/**
 * De variant waarmee de kern gerekend heeft: UGT-combinaties met
 * rekenwaarden, BGT-combinaties met gemiddelde waarden. Staat óók per
 * segment in het antwoord — de norm laat dat nooit impliciet.
 */
grenstoestand: NonlinearBasis, 
/**
 * Aantal opgeloste raamwerkstelsels (ronde 0, de indeling, telt niet mee).
 */
ronden: number, 
/**
 * Het convergentieverloop, op volgorde.
 */
verloop: Array<StijfheidRonde>, 
/**
 * De kernantwoorden van de LAATSTE ronde, per staaf — de rapporttabel.
 */
staven: Array<SegmentStiffnessResponse>, };
