// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eén stuk beugelwapening dat over een deel van de staaf ligt — §9.2.2.
 *
 * De vijf gegevens zijn precies wat A_sw/s en ρ_w nodig hebben: §9.2.2(5)
 * omschrijft A_sw als "de oppervlakte van de doorsnede van de
 * dwarskrachtwapening binnen de lengte s", dus n benen × (π/4)·Ø², en (9.4)
 * deelt dat door s·b_w·sin α.
 *
 * # Alle drie de maten zijn hier VERPLICHT en positief
 *
 * In [`ReinforcementCage`] mogen `stirrup_spacing_mm` en `stirrup_legs`
 * ontbreken: leeg betekent daar "niet opgegeven" en de dwarskrachttoets meldt
 * dan dat hij niet kan. In een zone kan dat niet dezelfde betekenis hebben —
 * wie een stuk staaf apart benoemt, zegt daarmee wat er ligt. Een zone met een
 * halve opgave zou de toets op dat stuk stilzwijgend uitzetten terwijl hij op
 * het stuk ernaast wél loopt, en dat is een gat dat in een rapport niet
 * opvalt.
 *
 * Een stuk staaf ZONDER beugels is hierin dus niet uit te drukken, en dat is
 * met opzet: §6.2.1(4) eist ook waar geen berekende dwarskrachtwapening nodig
 * is tóch de minimumwapening van §9.2.2, behalve bij platen met dwarsverdeling
 * en bij elementen van ondergeschikt belang. Voor die uitzonderingen blijft de
 * beugellijst LEEG en gelden de beugelvelden van [`ReinforcementCage`] — die
 * mogen wél leeg zijn.
 */
export type StirrupZone = { 
/**
 * Begin van de zone langs de staaf, in mm vanaf het beginknoop.
 */
x_start_mm: number, 
/**
 * Einde van de zone langs de staaf, in mm vanaf het beginknoop.
 */
x_end_mm: number, 
/**
 * Hart-op-hartafstand s van de beugels LANGS de lengteas, mm — symbool s
 * in (9.4), begrensd door s_l,max in §9.2.2(6).
 */
spacing_mm: number, 
/**
 * Aantal beugelbenen n dat één verticale doorsnede kruist — §9.2.2(5).
 */
legs: number, 
/**
 * Beugeldiameter Ø, mm. De nationale bijlage bij §9.2.2(9) eist ten minste
 * 5 mm; die toets hoort bij de detaillering en niet bij deze validatie.
 */
diameter_mm: number, };
