// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waar de staaf lag ten opzichte van de stortrichting — PER STAAF op te geven.
 *
 * Figuur 8.2 leidt de aanhechtingsomstandigheden af uit drie dingen: de
 * stortrichting (de pijl 'A' in de figuur), de hoogte h van het element en de
 * plaats van de staaf daarin. De eerste daarvan is een uitvoeringsgegeven dat
 * het rekenmodel niet kan weten, en juist die bepaalt of de bovenwapening van
 * een balk van 700 mm 'goed' of 'slecht' verankerd is — een verschil van een
 * factor 1/0,7 = 1,43 in l_bd.
 *
 * [`Stortpositie::Onderzijde`] is de standaard: dat is de gewone situatie bij
 * werk ter plaatse, waarbij van bovenaf wordt gestort en de onderwapening dus
 * in de 'goede' zone ligt.
 */
export type Stortpositie = "Onderzijde" | "Bovenzijde" | "Glijbekisting" | "GoedAangetoond";
