// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructuralSystem } from "./StructuralSystem";

/**
 * Eén regel uit tabel 7.4N, zoals een keuzelijst hem nodig heeft.
 */
export type StructuralSystemInfo = { system: StructuralSystem, 
/**
 * De kolom "Constructief systeem", woordelijk uit de tabel.
 */
label: string, 
/**
 * De kolom K.
 */
k: number, 
/**
 * De kolom "Beton onder hoge spanning (ρ = 1,5 %)". ORIËNTATIE, GEEN
 * INVOER: dit is de uitkomst van (7.16) voor C30/37 bij ρ = 1,5 %.
 */
basic_high_stress: number, 
/**
 * De kolom "Beton onder lage spanning (ρ = 0,5 %)". Idem oriëntatie.
 */
basic_low_stress: number, };
