// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Het constructieve systeem uit tabel 7.4N, dat K bepaalt.
 *
 * De vijf regels van de tabel, in de volgorde van de tabel. De namen zijn
 * Engels omdat de rest van de kern dat is; de woordelijke Nederlandse
 * tabelregel staat in [`StructuralSystemInfo::label`].
 *
 * Deze keuze is INVOER. Uit een raamwerkmodel is zij niet betrouwbaar af te
 * leiden — of een veld een eind- of een tussenoverspanning is, hangt van de
 * continuïteit van de ligger af, en of een plaat in één of in twee
 * richtingen draagt is een ontwerpgegeven. Tussen K = 1,0 en K = 1,5 zit
 * 50 % verschil, dus een gok is hier duurder dan een vraag.
 */
export type StructuralSystem = "SimplySupported" | "EndSpan" | "InteriorSpan" | "FlatSlab" | "Cantilever";
