// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De afleiding van l_bd van één bundel volgens §8.4 — (8.2), (8.3), (8.4) en
 * (8.6)/(8.7).
 *
 * Geen kaal getal: wie l_bd in een rapport zet, moet kunnen laten zien welke
 * aanhechtingsomstandigheden zijn aangehouden, welke alfa-factoren golden en
 * welke ondergrens maatgevend was. De schuine tak van figuur 9.2 loopt over
 * deze lengte, dus zij bepaalt rechtstreeks waar de weerstandslijn schuin
 * gaat lopen.
 */
export type Verankeringsafleiding = { 
/**
 * η₁ volgens 8.4.2(2) — 1,0 bij 'goede' omstandigheden, 0,7 bij "alle
 * andere gevallen".
 */
eta_1: number, 
/**
 * De omschrijving zoals de norm haar noemt.
 */
aanhechting: string, 
/**
 * Waarom die omstandigheden gelden (figuur 8.2).
 */
aanhechting_reden: string, 
/**
 * η₂ volgens 8.4.2(2) — de staafdiameterfactor.
 */
eta_2: number, 
/**
 * f_ctd volgens (3.16), N/mm².
 */
f_ctd_mpa: number, 
/**
 * f_bd volgens (8.2), N/mm².
 */
f_bd_mpa: number, 
/**
 * σ_sd zoals in (8.3) ingevuld, N/mm².
 */
sigma_sd_mpa: number, 
/**
 * l_b,rqd volgens (8.3), mm.
 */
l_b_rqd_mm: number, 
/**
 * α₁ — vorm van de staaf (tabel 8.2).
 */
alpha_1: number, 
/**
 * α₂ — betondekking.
 */
alpha_2: number, 
/**
 * α₃ — opsluiting door niet-gelaste dwarswapening.
 */
alpha_3: number, 
/**
 * α₄ — opsluiting door gelaste dwarswapening.
 */
alpha_4: number, 
/**
 * α₅ — opsluiting door dwarsdruk.
 */
alpha_5: number, 
/**
 * α₁·α₂·α₃·α₄·α₅ met (8.5) toegepast — de factor uit (8.4).
 */
alpha_product: number, 
/**
 * Heeft (8.5) het product α₂·α₃·α₅ opgetrokken tot 0,7?
 */
begrensd_door_8_5: boolean, 
/**
 * (8.4) vóór de ondergrens, mm.
 */
l_bd_berekend_mm: number, 
/**
 * l_b,min volgens (8.6)/(8.7), mm.
 */
l_b_min_mm: number, 
/**
 * Is l_b,min maatgevend voor l_bd?
 */
ondergrens_maatgevend: boolean, 
/**
 * De rekenwaarde van de verankeringslengte, mm — het antwoord.
 */
l_bd_mm: number, 
/**
 * Eén regel per alfa-factor: welke tabelregel gold en waarom.
 */
herkomst: Array<string>, 
/**
 * Kanttekeningen bij deze staaf: aannamen, afwijkingen, grenzen.
 */
toelichting: Array<string>, };
