// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Welke van de twee door de norm toegelaten bewijsvoeringen de
 * dwarskrachtweerstand op een plaats levert.
 */
export type Weerstandsroute = "BetonZonderWapening" | "Dwarskrachtwapening";
