// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waar de inwendige hefboomsarm z van een punt vandaan komt — 6.2.3(1), zie
 * `nen_en_1992_1_1::hefboomsarm`.
 */
export type ZGrondslag = "Opgegeven" | "Benadering" | "Evenwicht" | "EvenwichtBegrensd" | "Terugval";
