// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De nationale bijlage waarmee gerekend wordt.
 *
 * De waarde is de landcode volgens ISO 3166-1 alpha-2, zoals de Eurocodes hem
 * zelf gebruiken in aanduidingen als "NEN-EN 1993-1-1+A1:2014+NB:2016 nl".
 *
 * # Waarom hier maar één variant staat
 *
 * Een variant toevoegen betekent een rij vullen in [`Ndp1990`], [`Ndp1992`],
 * [`Ndp1993`], [`Ndp1993Las`], [`Ndp1995`] én [`Aanduidingen`]. Zolang de
 * normtekst van die bijlage niet te lezen is, zou dat verzinnen zijn. De naad
 * is er wél: alles wat de keuze door de keten draagt (projectbestand,
 * app-instelling, toetsinvoer, MCP-schema, toetsbrug) is op meer dan één
 * waarde gebouwd.
 */
export type NationaleBijlage = "NL";
