// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Iets dat bij deze plaat NIET getoetst is, met de reden.
 */
export type PlaatNietGetoetst = { 
/**
 * Stabiele sleutel, bijvoorbeeld "en1993_1_5_plooi".
 */
id: string, 
/**
 * De titel zoals paneel en rapport hem tonen.
 */
titel: string, 
/**
 * Waarom niet — met de normverwijzing.
 */
reden: string, 
/**
 * Bepaalt dit gat de STATUS van de plaat? `true` betekent: de spanning
 * waar het om gaat is in deze plaat werkelijk aanwezig en niet getoetst,
 * dus de plaat kan niet "voldoet" heten (status `NotApplicable` zolang
 * geen uitgevoerde toets `NotOk` geeft). `false` betekent: het staat
 * erbij als grens van de toets, zoals plooi bij staal.
 */
bepaalt_status: boolean, };
