// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Beton: de benodigde trekkracht in de wapening van één element, per
 * wapeningsrichting, volgens NEN-EN 1992-1-1 bijlage F — het maximum over de
 * combinaties. In kN per m wand (= f'_td · t): deel door f_yd voor A_s in
 * mm²/m (over beide zijden samen).
 */
export type PlaatWapeningElement = { element_id: number, 
/**
 * Wapening in de horizontale modelrichting (x).
 */
n_td_x_kn_per_m: number, combination_x: number, 
/**
 * Wapening in de verticale modelrichting (z).
 */
n_td_z_kn_per_m: number, combination_z: number, };
