// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De materiaalsoort van een plaat — dezelfde vijf soorten als in
 * `design-mockup/src/lib/plaatMateriaal.ts`.
 *
 * De soort reist expliciet mee en wordt niet uit de naam geraden: "C30" is in
 * EN 338 een HOUTsterkteklasse en "C30/37" een betonklasse, en de app heeft
 * die keuze bij het bepalen van de stijfheid al gemaakt. Deze kern controleert
 * wel dat de naam bij de opgegeven soort in zijn eigen tabel staat; past dat
 * niet, dan volgt een weigering in plaats van een toets met een andere tabel.
 */
export type PlaatMateriaalSoort = "Staal" | "Hout" | "Kruislaaghout" | "Beton" | "Vrij";
