// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spanningen van één plaatelement in de globale assen, in N/mm².
 *
 * `sigma_y_mpa` is de normaalspanning in de VERTICALE richting van het
 * modelvlak (model-z) — de naam volgt het plaatresultaat van de solver
 * (`sigmaY`). In de notatie van NEN-EN 1993-1-1 (6.1) is dat σ_z,Ed.
 * Trek positief.
 */
export type PlaatElementSpanning = { 
/**
 * Element-id in het rekenmesh; komt onveranderd terug in het resultaat.
 */
element_id: number, sigma_x_mpa: number, sigma_y_mpa: number, tau_xy_mpa: number, };
