// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaatWapeningElement } from "./PlaatWapeningElement";

/**
 * Beton: de benodigde wapening over de hele plaat.
 */
export type PlaatWapening = { 
/**
 * Het element met de grootste benodigde trekkracht in x.
 */
max_x: PlaatWapeningElement, 
/**
 * Het element met de grootste benodigde trekkracht in z.
 */
max_z: PlaatWapeningElement, 
/**
 * Per element, in de volgorde van het rekenmesh.
 */
elementen: Array<PlaatWapeningElement>, };
