// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExposureClass } from "../concrete/ExposureClass";
import type { PlaatWapeningRichting } from "./PlaatWapeningRichting";

/**
 * De aanwezige wapening van een betonwand.
 */
export type PlaatWapeningInvoer = { 
/**
 * Betonstaalsoort, bijvoorbeeld "B500B" — bepaalt f_yk en f_yd.
 */
staalsoort: string, 
/**
 * Wapening in de horizontale modelrichting (x).
 */
horizontaal: PlaatWapeningRichting, 
/**
 * Wapening in de verticale modelrichting (z).
 */
verticaal: PlaatWapeningRichting, 
/**
 * Milieuklasse (tabel 4.1): de enige ingang van tabel 7.1N (NB) voor
 * w_max. Weglaten = scheurwijdte niet getoetst, met reden; er wordt geen
 * klasse aangenomen.
 */
milieuklasse?: ExposureClass, 
/**
 * Treksterkte op het verwachte scheurtijdstip (7.3.2), N/mm².
 * Geen automatische aanname van ouderdom of f_ctm.
 */
f_ct_eff_mpa?: number, 
/**
 * Belastingsduur voor (7.9): true = langdurend, false = kortdurend.
 */
langdurend?: boolean, 
/**
 * Aanhechting voor (7.11): true = hoog, false = glad.
 */
hoge_aanhechting?: boolean, };
