// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaatWapeningLaag } from "./PlaatWapeningLaag";

/**
 * De wapening in één richting: zijde 1 (voorzijde) en zijde 2 (achterzijde).
 */
export type PlaatWapeningRichting = { zijde_1?: PlaatWapeningLaag, zijde_2?: PlaatWapeningLaag, };
