// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Het maatgevende element van één combinatie.
 */
export type PlaatCombinatieUitkomst = { combination_id: number, uc: number, element_id: number, check_id: string, };
