// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De hoogste unity check van één element over alle combinaties — de
 * OMHULLENDE per element. Hieruit kleurt het canvas elk element.
 */
export type PlaatElementUitkomst = { element_id: number, uc: number, 
/**
 * De combinatie waarin deze hoogste UC optreedt.
 */
combination_id: number, 
/**
 * De toets die deze UC geeft (bij staal altijd het vloeicriterium).
 */
check_id: string, };
