// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CombinationLoadDuration } from "../timber/CombinationLoadDuration";
import type { NationaleBijlage } from "../norm/NationaleBijlage";
import type { PlaatCombinatie } from "./PlaatCombinatie";
import type { PlaatMateriaalSoort } from "./PlaatMateriaalSoort";
import type { PlaatPlooiInput } from "./PlaatPlooiInput";
import type { PlaatWapeningInvoer } from "./PlaatWapeningInvoer";
import type { ServiceClass } from "../timber/ServiceClass";

/**
 * Invoer voor de toets van één plaat.
 *
 * `deny_unknown_fields`, net als de staafinvoertypen: een tikfout in een
 * veldnaam hoort geweigerd te worden en niet stil op een standaardwaarde te
 * vallen.
 */
export type PlateCheckInput = { 
/**
 * De nationale bijlage (normnaad); bepaalt γ_M0.
 */
bijlage: NationaleBijlage, 
/**
 * Plaatnummer uit het model; komt onveranderd terug.
 */
plate_id: number, soort: PlaatMateriaalSoort, 
/**
 * De materiaalnaam zoals de app hem herkende: "S355", "C24", "GL28h", …
 */
materiaal: string, 
/**
 * Plaatdikte in mm. Bij staal bepaalt zij de dikteklasse van tabel 3.1.
 */
thickness_mm: number, 
/**
 * Zonder dit veld blijft de bestaande vloeicontrole ongewijzigd.
 */
plooi?: PlaatPlooiInput, 
/**
 * Hout: hoofdrichting (vezel) in GRADEN tegen de klok in vanaf de globale
 * x-as — dezelfde hoek als `Plate.hoofdrichting` en als de solver gebruikt.
 * Weglaten = 0°. Bij staal zonder betekenis.
 */
hoofdrichting_graden?: number, 
/**
 * Hout: de klimaatklasse (2.3.1.3). VERPLICHT voor hout: ontbreekt zij,
 * dan weigert de kern — er wordt geen klasse aangenomen.
 */
service_class?: ServiceClass, 
/**
 * Hout: de belastingduurklasse per UGT-combinatie (3.1.3(2)), zoals de
 * invoerbouwer haar uit de belastinggevallen afleidde. Elke combinatie in
 * `combinations` moet erin staan; anders weigert de kern.
 */
load_duration_per_combination?: Array<CombinationLoadDuration>, 
/**
 * Kanttekeningen van de invoerbouwer; rekenen nergens mee en komen
 * letterlijk in de notities van het resultaat.
 */
notities?: Array<string>, 
/**
 * De elementspanningen per UGT-combinatie.
 */
combinations: Array<PlaatCombinatie>, 
/**
 * Beton: volledige elementset uit de mesh, onafhankelijk van de spanningsresultaten.
 * Weglaten betekent onbewezen dekking en levert geen betontoets op.
 */
expected_element_ids?: Array<number>, 
/**
 * Beton: ontbrekende of tegenstrijdige meshmetadata vastgesteld door de invoerbouwer.
 * Een opgegeven fout blokkeert de toets, ook bij een verder passende elementset.
 */
mesh_fout?: string, 
/**
 * Beton: de AANWEZIGE wapening van de wand (issue #25). Weglaten = niet
 * ingevoerd; dan toetst de kern alleen de benodigde wapening en het beton,
 * precies zoals zonder dit veld, met de melding dat de aanwezige wapening
 * niet is ingevoerd. Bij een ander materiaal dan beton geweigerd.
 */
wapening_aanwezig?: PlaatWapeningInvoer, 
/**
 * Beton: de elementspanningen per FREQUENTE BGT-combinatie (6.15b) — de
 * combinatie waaronder de nationale bijlage bij 7.3.1(5) (tabel 7.1N) de
 * scheurwijdte laat toetsen. Alleen gelezen samen met
 * `wapening_aanwezig`; leeg = scheurwijdte niet getoetst, met reden.
 */
frequente_combinaties?: Array<PlaatCombinatie>, };
