// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckStatus } from "../steel/CheckStatus";
import type { NamedCheck } from "../steel/NamedCheck";
import type { PlaatCombinatieUitkomst } from "./PlaatCombinatieUitkomst";
import type { PlaatElementUitkomst } from "./PlaatElementUitkomst";
import type { PlaatMateriaalSoort } from "./PlaatMateriaalSoort";
import type { PlaatNietGetoetst } from "./PlaatNietGetoetst";
import type { PlaatWapening } from "./PlaatWapening";

/**
 * Resultaat van de toets van één plaat.
 *
 * Geen `PartialEq`: `NamedCheck` heeft die niet. Vergelijk twee antwoorden
 * op hun JSON, zoals de drie-wegen-tests dat doen.
 */
export type PlateCheckResult = { plate_id: number, soort: PlaatMateriaalSoort, materiaal: string, thickness_mm: number, 
/**
 * De norm waarop getoetst is, zoals het rapport hem noemt; leeg bij een
 * weigering.
 */
norm: string, 
/**
 * Per toets de afleiding op het maatgevende element en de maatgevende
 * combinatie van díe toets.
 */
checks: Array<NamedCheck>, 
/**
 * De hoogste unity check over alle elementen, combinaties en toetsen. 0
 * bij een weigering — lees dan `geweigerd`, niet dit getal.
 */
uc_max: number, status: CheckStatus, governing_check_id: string, governing_element_id?: number, governing_combination_id?: number, 
/**
 * Per combinatie het maatgevende element.
 */
combinaties: Array<PlaatCombinatieUitkomst>, 
/**
 * Per element de hoogste UC over de combinaties (omhullende), in de
 * volgorde van het rekenmesh.
 */
elementen: Array<PlaatElementUitkomst>, 
/**
 * Wat niet getoetst is, met reden.
 */
niet_getoetst: Array<PlaatNietGetoetst>, 
/**
 * Aanwezig = er is NIETS getoetst, met de reden. `status` is dan
 * `NotApplicable` en `uc_max` 0.
 */
geweigerd?: string, 
/**
 * Alleen bij beton: de benodigde wapening volgens bijlage F.
 */
wapening?: PlaatWapening, 
/**
 * Kanttekeningen bij de plaat als geheel.
 */
notes: Array<string>, };
