// De assistent-vaardigheid "Plattegrond": een bouwkundige plattegrond tekenen
// waarin de onderdelen elkaar kennen.
//
// Dit bestand bevat alleen GEGEVENS — de chip voor het assistentvenster en de
// instructie voor het model dat de MCP-opdrachten uitvoert. De rekenkunde zit
// in sparing.js, ruimte.js en maatvoering.js; de opdracht zelf in
// mcp-plattegrond.js achter `app_floorplan`. Vliesgevels en kozijnen als
// gevelelement lopen via `app_facade_element` (js/gevelelement/).
//
// Waarom een eigen instructie: de bestaande "Teken"-vaardigheid is één zin en
// levert losse vormen op. Een plattegrond vraagt om volgorde (stramien →
// dragende wanden → scheidingswanden → kozijnen → ruimten → maatvoering), om
// een schaal vóór de eerste lijn, en om controleren wat er staat.

export const PLATTEGROND_SKILL = {
  id: 'floorplan',
  icon: '🏠',
  label: 'Floor plan',
  hint: "Draw a floor plan with walls, frames, rooms, dimensions and fixtures (bathroom and kitchen)",
  invoke: "Draw an architectural floor plan. Set the scale, draw walls with doors and windows, identify rooms and add dimensions. Use English labels. Drawing request:",
  needsInput: true,
};

// Wandjoin en de Nederlandse spouwmuur (#476): hoe de app aansluitende wanden
// afsluit, en hoe je een gevel uit losse lagen tekent zonder dat de lagen in
// een hoek door elkaar heen steken. Eigen blok, ingevoegd na de wandmaten.
export const SPOUWMUUR_INSTRUCTIE =
  "   Wandjoin: wanden die elkaar raken sluit de app zelf af. Samenvallende eindpunten gaan in verstek (elk material). Einden die een wall van HETZELFDE material net passeren of net niet halen, worden tot een dichte angle getrimd; met een ander material gebeurt dat niet, zodat een laag nooit door een andere laag steekt. Een wall die op een continuous wall stopt (eindpunt op de hartlijn, op het vlak, er net voor of erin) wordt een T: bij hetzelfde material vloeien de wanden in elkaar over, bij een ander material stopt hij stomp tegen het vlak met een naad. Zet de join aan een uiteinde alleen uit als dat einde precies moet blijven zoals getekend, met een eigen kap en zonder verstek, T of afkappen: joinStart:false en/of joinEnd:false (begin/eind van de loop), of achteraf app_update_annotation {id, props:{noJoinStart:true}} of {noJoinEnd:true} (true = join uit, false = weer aan).\n" +
  "   Spouwmuur (gevel): een Nederlandse spouwmuur is van outside naar binnen metselwerk 100 (nen47-metselwerk-baksteen), luchtspouw 40, isolatie 100 (isolatie, bijvoorbeeld insulation:\"pir\") en kalkzandsteen 120 (nen47-metselwerk-kunststeen, het binnenblad), samen 360 mm.\n" +
  "   - Teken hem als losse wanden: per gevel een app_floorplan-aanroep per laag. De luchtspouw is GEEN wall; daar blijft 40 mm open tussen metselwerk en isolatie. De laaghartlijnen liggen evenwijdig aan het buitenvlak, op 50 (metselwerk), 190 (isolatie) en 300 mm (kalkzandsteen) naar binnen.\n" +
  "   - Hoeken per laag: laat in een angle de hartlijnen van DEZELFDE laag van beide gevels in één punt samenvallen (metselwerk op metselwerk, isolatie op isolatie, kalkzandsteen op kalkzandsteen). Dan verstekt elke laag met zichzelf en steekt no laag door een andere laag of door de spouw. Moet een laag stomp tegen een doorgaande laag stoppen, laat hem dan op dat vlak eindigen: bij een ander material wordt dat vanzelf een stompe aansluiting met naad, bij hetzelfde material vloeien ze in elkaar over (wil je daar toch een losse kap, zet dan de join uit).\n" +
  '   - Sparingen: geef een deur of raam aan ALLE lagen van die gevel mee met dezelfde widthMm, zodat alle lagen op dezelfde plek onderbroken worden. alongMm telt vanaf het eigen beginpunt van elke laag; begint een laag op een ander punt (bij een verstekhoek ligt het begin per laag anders), reken dat verschil om, zodat het hart van de sparing in elke laag op dezelfde plek ligt.\n' +
  "   - Binnenwanden sluiten aan op het binnenblad: laat ze eindigen op het binnenvlak (of de hartlijn) van de kalkzandsteen, niet op de hartlijn van de hele gevel. De app maakt er een T van: kalkzandsteen op kalkzandsteen vloeit in elkaar over, een binnenwand van een ander material stopt stomp tegen het binnenvlak. Zet daar de join NIET uit, anders krijgt het einde weer een losse kap.\n" +
  "   - {action:\"inspect\"} geeft per wall joinStart en joinEnd terug.\n";

// Inrichten (#478): sanitair en keuken als parametrische symbolen op
// werkelijke maat, geplaatst met app_create_annotation. Apart gehouden zodat
// de symbool-ids en parameters op één plek staan (skill.test.mjs toetst ze
// tegen de templates).
export const INRICHTING_PROMPT =
  '\nINRICHTEN - sanitair en keuken (na de wanden): app_create_annotation {type:"parametricSymbol", props:{symbolId, x, y, rotation, anchor, params:{...}}}. Elk onderdeel staat op WERKELIJKE MAAT (mm, via de schaal op dat punt).\n' +
  "   Richting: ongedraaid ligt de ACHTERKANT (wandzijde) top; rotation 90 = wall right, 180 = wall bottom, 270 = wall links. anchor:\"back\" maakt x/y het center van de achterkant: geef dan een punt OP HET WANDVLAK (hartlijn plus halve wanddikte naar de ruimte toe) en de app legt het toestel ertegen, ook gedraaid. anchor:\"back-left\"/\"back-right\" is de linker-/rechterhoek van de achterkant (een aanrecht dat in een angle begint); zonder anchor is x/y het center.\n" +
  "   Sanitair: \"wandcloset\" {breedte 360, diepte 530}, \"staand-closet\" {breedte 380, diepte 680}, \"fontein\" {breedte 380, diepte 250, kraan:\"center\"|\"zijkant\", spiegelen}, \"hoekfontein\" {breedte 330, diepte 330, spiegelen} (de angle ligt linksboven, gespiegeld rechtsboven: zet hem met anchor:\"back-left\" in de binnenhoek). Toiletruimte, vuistregel: netto minstens 900 x 1200 mm, hart closet minstens 400 mm uit een zijwand, 600 mm vrij voor de pot; de fontein naast of tegenover het closet, outside de draaicirkel van de deur.\n" +
  "   Keuken: \"aanrecht\" (recht; length, diepte 600), \"aanrecht-hoek\" (L-vorm; length = been 1 langs de achterwand, lengte2 = been 2 langs de rechterwand, buitenhoek rechtsboven, gespiegeld linksboven; diepte 600) en \"kookeiland\" (length 2400, diepte 1000, overstek = zitgedeelte). Allemaal met spiegelen en onderdelen. Een blok met zijn onderdelen is EEN symbool: het verplaatst en draait als geheel.\n" +
  "   onderdelen: [{soort, vanaf, breedte, been}]. soort: spoelbak, spoelbak-dubbel, kookplaat-4, kookplaat-5, inductie, vaatwasser, koelkast, hoge-kast. vanaf = mm van het begin van het been tot de linkerkant van het onderdeel (kijkend naar de wall); breedte standaard 600 (spoelbak-dubbel en kookplaat-5 900, inductie 800); been 1|2 alleen bij aanrecht-hoek, been 2 gemeten vanaf de buitenhoek en pas vrij na het hoekvak (vanaf >= diepte). Wat outside het blad valt, schuift de app erin; lees het resultaat terug met app_get_annotation.\n" +
  "   Wijzigen: app_update_annotation {id, props:{params:{...}}} VOEGT params SAMEN (alleen de length meegeven laat de onderdelen staan) en zet de werkelijke maat opnieuw; een aanrecht groeit vanaf zijn begin (aanrecht-hoek vanaf de buitenhoek), een toestel vanaf de wall.\n" +
  "   Keuken, vuistregels: vaatwasser direct naast de spoelbak; minstens 600 mm werkblad tussen spoelbak en kookplaat; kookplaat minstens 300 mm uit een wall of hoge kast; loopruimte voor een aanrecht en tussen aanrecht en eiland minstens 1000 mm.";

export const PLATTEGROND_PROMPT =
  "\n\nPLATTEGROND TEKENEN (vaardigheid \"Plan\", opdracht app_floorplan):\n" +
  "Teken een plattegrond NOOIT als losse vormen op elkaar. Gebruik app_floorplan, dat de drie relaties van een bouwtekening legt: een sparing hoort bij een wall, een ruimte bij de wanden eromheen, een maat bij wat hij meet.\n" +
  'Coordinatenruimte: alle x/y zijn paginapunten op 100% zoom; app_get_viewport_state geeft pageW/pageH. Alle maten (wanddikte, dagmaat, borstwering, offset) zijn WERKELIJKE MILLIMETERS.\n' +
  'Werkvolgorde:\n' +
  "1. Schaal eerst. Zonder schaal weigert app_floorplan. Zet hem met app_set_measure_scale: pixelsPerUnit = 2.8346 / noemer, unit \"mm\" (1:50 -> 0.0567, 1:100 -> 0.0283). Reken daarna zelf om: 1 mm werkelijk = pixelsPerUnit paginapunt, dus een gevel van 10 m op 1:50 is 567 punten long. Kies een beginpunt zo dat de hele plattegrond op de pagina past.\n" +
  "2. Wanden met hun kozijnen, per gevel of wandloop een aanroep: app_floorplan {action:\"wall\", start:{x,y}, end:{x,y}, thicknessMm, material, openings:[...]}. start/end zijn de HARTLIJN van de wall; laat de hartlijnen van aansluitende wanden in de hoekpunten samenvallen, dan verstekt de app de angle zelf. Elke opening is {kind:\"door\"|\"window\", widthMm (dagmaat), alongMm (hart, gemeten vanaf start langs de wall), sillMm (borstwering), heightMm, swing:\"left\"|\"right\" (scharnierkant) en openTo:{x,y} (een punt in de ruimte waarin de deur draait)}. De wall wordt op elke sparing opgeknipt, dus het kozijn onderbreekt de wall echt. Bewaar de teruggegeven wallIds op volgorde.\n" +
  '   Materialen: nen47-metselwerk-baksteen (buitenblad), nen47-metselwerk-kunststeen (kalkzandsteen, binnenwand), nen47-beton-gewapend, nen47-beton-prefab, isolatie (met insulation: steenwol/glaswol/pir/eps/kooltherm/pur), none.\n' +
  '   Gangbare maten: buitenwand 300-350 mm, dragende binnenwand 200-250, scheidingswand 70-100. Deur 900 x 2315, binnendeur 830, raam 1200-2400 breed met borstwering 850.\n' +
  SPOUWMUUR_INSTRUCTIE +
  '2b. Vliesgevels en puien: gebruik app_facade_element, niet een rij losse ramen. Een gevelelement is EEN object langs een lijn: kader aan beide uiteinden, stijlen op de veldgrenzen, per veld een paneel. preset "curtainWall" (vliesgevel, aluminium stijlen alu-50x150/alu-50x200/alu-65x250, panelen glass, solid, door, open) of "windowFrame" (kozijn, kozijnhout hout-67x114/hout-67x139/hout-90x114, panelen glass, turnSash, door, solid).\n' +
  "   In een wall: app_facade_element {action:\"create\", preset, wallId (een wallId uit stap 2), fromMm (begin, vanaf het beginpunt van de wall) of alongMm (center), lengthMm, fields (aantal gelijke velden) of fieldWidthsMm (hart-op-hart), panels:[\"glass\",\"door\",...]}. De wall wordt dan over de length van het element onderbroken, net als bij een kozijn uit stap 2, en een vliesgevel telt daarna als omsluiting van de ruimte. Los: {action:\"create\", start:{x,y}, end:{x,y}, ...}.\n" +
  "   Een deur is {type:\"door\", hinge:\"start\"|\"end\", swing:\"inside\"|\"outside\"}; binnen is standaard right van de tekenrichting (insideSide).\n" +
  "   Bewerken met het teruggegeven id: {action:\"addMullion\", id, atMm} (veld splitsen), {action:\"removeMullion\", id, mullion} (velden samenvoegen), {action:\"moveMullion\", id, mullion, toMm}, {action:\"setMullionType\", id, mullion, mullionType}, {action:\"setPanel\", id, field, panel}, {action:\"divide\", id, fields}. Stud 0 en de laatste stijl zijn het kader; veld i ligt tussen stijl i en i+1. Terugvragen: {action:\"get\", id} of {action:\"get\"} voor alle elementen op de pagina.\n" +
  "3. Ruimten: app_floorplan {action:\"rooms\", place:true, seeds:[{x,y,name:\"Woonkamer\", number:\"0.01\"}, ...]} (number mag weg). De ruimte volgt uit de wanden: netto oppervlakte binnen de wandvlakken. Per ruimte komt er een ingetogen ruimtevlak (dunne grijze edge, no arcering of vulling, ACHTER de wanden en kozijnen) en EEN ruimtetag met naam, netto oppervlakte en nummer, in het hart van de ruimte. Zet ruimtenamen dus nooit als los tekstvak. Name en nummer horen bij de RUIMTE zelf; de tag laat ze zien en is movable. Wijzigen: {action:\"rooms\", names:[{id (uit het antwoord) of x,y (een punt in de ruimte), name, number}]}. Uitlezen: {action:\"rooms\"} of inspect geeft per geplaatste ruimte id, name, number en tagIds. Is een tag weg, dan zet place:true met een punt in die ruimte alleen een nieuwe tag neer (no tweede ruimtevlak). Een ruimte is met een klik niet te selecteren (wanden en kozijnen winnen); in de app via haar tag. Zonder seeds krijg je alleen een overzicht van wat er gevonden is. openEnds in het antwoord zijn wandeinden waar de contour niet sluit - meld die, ga niet raden. Verschoof er later een wall, draai dan {action:\"rooms\", refresh:true}: elk ruimtevlak rekent zichzelf opnieuw uit en elke ruimtetag krijgt de nieuwe oppervlakte en schuift mee met zijn ruimte.\n" +
  "4. Maatvoering: app_floorplan {action:\"dimensions\", wallIds:[...uit stap 2, op volgorde], side:\"left\"|\"right\"}. Dat levert een maatketting (penant, dagmaat, penant, ...) plus een totaalmaat. Een bouwkundige meet vanaf het WANDVLAK, en zo werkt de ketting ook: de punten liggen op het vlak aan de maatzijde (bij een spouwmuur uit losse lagen op het buitenvlak van de buitenste laag - geef gerust de wallIds van een binnenlaag, de app zoekt de buitenste zelf) en de uiterste punten liggen op de buitenhoek van het gebouw, ook als het wandstuk bij een stompe angle eerder stopt. side is de kant van de ketting, gezien langs de looprichting van de wall: bij een met de klok mee getekende omtrek is \"left\" outside. Laat offsetMm en totalOffsetMm weg: de standaard (500 en 850 mm vanaf het wandvlak op 1:50) groeit mee met de schaal, zodat teksten niet tegen de maatlijnen of de totaalmaat aan komen. Maten zijn zwart en dun en tonen alleen het getal in mm; showUnit:true zet de eenheid erachter. De maatlijn loopt 2 mm (op papier) door voorbij de buitenste hulplijnen en de hulplijnen beginnen 1,5 mm van het wandvlak - dat hoeft niet opgegeven. After een wijziging: {action:\"dimensions\", refresh:true} - ook dan blijven de punten op het wandvlak en de buitenhoek.\n" +
  "   Ketting uitbreiden in plaats van een nieuwe maatlijn tekenen: {action:\"dimensions\", chainOf:\"<id van een maat uit de ketting>\", addPoints:[{x,y}, ...]} zet er hulplijnen bij (tussen twee hulplijnen splitst het segment, erbuiten wordt de ketting langer, de totaalmaat gaat mee); removePoints:[{x,y}] haalt een hulplijn weg. Een punt op een wandvlak wordt aan die wall verankerd. chainId in het antwoord van \"dimensions\" hoort bij de hele ketting.\n" +
  "5. Controleren: app_floorplan {action:\"inspect\"} geeft terug wat er staat - wanden met length en dikte, sparingen met dagmaat en borstwering, de gevonden ruimten met oppervlakte, en openEnds. Gebruik dat om te verifieren, niet alleen een schermafdruk. Bekijk daarna eventueel met app_fit_page + app_screenshot_view of het beeld klopt.\n" +
  'Elke aanroep is één undo-stap. Gaat er iets mis, dan is app_undo genoeg. Teksten op de tekening (ruimtenamen, titel) gaan in de taal van de gebruiker.' +
  kozijnInstructie() +
  INRICHTING_PROMPT;

/**
 * Eigen blok: kozijnen op ware grootte en een spouwmuur met de sparing per
 * laag (layers). Als functie onderaan, zodat het blok los staat van de rest
 * van de instructie.
 */
function kozijnInstructie() {
  return '\n\nKOZIJNEN EN SPOUWMUREN:\n' +
    '- Ramen krijgen op de plattegrond GEEN draaicirkel: een kwartcirkel leest als een deur. Alleen als er echt om gevraagd wordt: showSwing:true bij een draairaam (windowType:"turn").\n' +
    "- Een kozijn wordt op ware grootte getekend: kozijnhout 67 x 114 mm met een sponning, double glas (24 mm) of een deurblad van 40 mm met draaicirkel. widthMm is de KOZIJNMAAT (buitenwerks); in een enkele wall is dat ook de dagmaat. Standaard binnendeur: kozijnmaat 930 (blad 830). Op 1:50 komen sponning en double glas in beeld, op 1:100 wordt het vereenvoudigd.\n" +
    "- Een spouwmuur teken je met EEN aanroep met layers (van outside naar binnen), niet als losse wanden per laag: app_floorplan {action:\"wall\", start, end, insideSide:\"right\", layers:[{thicknessMm:100, material:\"nen47-metselwerk-baksteen\"}, {thicknessMm:40, material:\"none\"}, {thicknessMm:100, material:\"isolatie\", insulation:\"pir\"}, {thicknessMm:120, material:\"nen47-metselwerk-kunststeen\"}], openings:[...]}. Met layers zijn start/end het BUITENVLAK van de gevel (buitenwerks), niet de hartlijn; insideSide is de kant van de binnenruimte gezien van start naar end (een met de klok mee getekende omtrek heeft binnen right: \"right\"). material \"none\" is de luchtspouw: ruimte, no wall. thicknessMm en material van de wall zelf tellen dan niet.\n" +
    "- Het kozijn staat dan in de spouw, direct achter het buitenblad. Het buitenblad heeft 20 mm aanslag over het kozijn (sparing in het metselwerk = kozijnmaat - 40), de isolatie sluit tegen het kozijn, het binnenblad heeft een dagkant met 10 mm speling (sparing = kozijnmaat + 20). Per opening aan te passen: framePositionMm (buitenvlak wall tot buitenkant kozijn), overlapMm (aanslag), clearanceMm (speling), stileWidthMm en frameDepthMm (kozijnhout), leafThicknessMm (deurblad). Het antwoord meldt per opening frame en layerOpeningsMm.\n" +
    "- Laat de buitenvlakken van aansluitende gevels in de hoekpunten samenvallen (zelfde layers, zelfde insideSide): dan verstekt de app elke laag in de angle; corners in het antwoord telt de verstekte lagen.\n" +
    "- Deuren in een spouwmuur draaien standaard naar binnen; openTo of openSide wijst een andere kant aan. swing is de draairichting: de kant van de scharnieren gezien vanaf de kant waar de deur van weg draait. Een raam heeft windowType fixed (fixed), turn (draairaam, met gestreepte draaicirkel naar binnen), pivot of tilt.\n" +
    '- Maatvoering langs een spouwgevel: geef de wallIds van het buitenblad mee (layers[0].wallIds uit het antwoord), dan meet de ketting de sparingen in het metselwerk.';
}
