import { createSignal, onCleanup, For, Show } from 'solid-js';
import { render } from 'solid-js/web';
import { BRAND } from '../js/core/brand.js';
import { readLocalProfile, saveLocalProfile } from '../../../branding/local-profile.js';
import './preview.css';

function Arrow(props) { return <svg width={props.size || 18} height={props.size || 18} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>; }
function Mark() { return <a class="brand-lockup" href="#landing" aria-label="Spanvision Infra home"><img src="icon.svg" alt="GW"/><span>{BRAND.organization}<small>{BRAND.product}</small></span></a>; }
function Floorplan() { return <svg class="plan-art" viewBox="0 0 620 350" aria-label="Architectural drawing with its original blue and red annotations"><rect width="620" height="350" fill="#fff"/><g fill="none" stroke="#242424" stroke-width="3"><path d="M80 50h460v230H80zM80 150h160V50M240 210V150h180V50M420 210h120M240 210h300M330 210v70M170 150v130"/><path stroke-width="1" d="M240 150a45 45 0 0 1 45 45h-45M420 210a45 45 0 0 1 45 45h-45M80 150a40 40 0 0 1 40 40H80"/><rect x="100" y="65" width="95" height="60" rx="2"/><rect x="455" y="70" width="65" height="100" rx="3"/><path d="M270 70h125v100H270zM290 70v100M375 70v100"/></g><g fill="#999" font-family="Arial" font-size="9" text-anchor="middle"><text x="155" y="138">MEETING ROOM</text><text x="331" y="185">OPEN WORKSPACE</text><text x="485" y="190">PROJECT OFFICE</text><text x="118" y="235">LOBBY</text><text x="200" y="250">STORE</text><text x="285" y="250">SERVICE</text></g><g stroke="#3681bc" fill="none" stroke-width="1"><path d="M80 305h460M80 293v24M540 293v24M80 303l8 4M540 303l-8 4"/></g><text x="310" y="302" fill="#3681bc" font-size="10" text-anchor="middle">12,400 mm</text><g stroke="#c44e4e" fill="none" stroke-width="1.6"><ellipse cx="490" cy="125" rx="47" ry="70" stroke-dasharray="5 3"/><path d="M535 75l32-35"/></g><text x="560" y="33" fill="#c44e4e" font-size="9" text-anchor="middle">Review glazing</text><text x="80" y="335" fill="#999" font-family="Arial" font-size="9">GW / PROJECT 024</text><text x="540" y="335" text-anchor="end" fill="#999" font-family="Arial" font-size="9">GROUND FLOOR · 1:100</text></svg>; }
function WorkspaceCard() { return <div class="workspace-card"><div class="mock-title"><img src="icon.svg" alt=""/><span>Spanvision Infra · PDF</span><span class="mock-title-org">Spanvision Infra</span><i>—　□　×</i></div><div class="mock-tabs"><b>Home</b><span>Comment</span><span>Drawing</span><span>Organize</span><span>View</span></div><div class="mock-tools"><span>↖ <small>Select</small></span><span>▱ <small>Highlight</small></span><span>↗ <small>Measure</small></span><span>▤ <small>Text</small></span><span>⤢ <small>Fit page</small></span><span>↶ <small>Undo</small></span></div><div class="mock-document">Project 024 — Ground floor.pdf <span>×　＋</span></div><div class="mock-content"><aside><small>PAGES</small><div class="mini-page">01</div><span>1 / 3</span></aside><div class="mock-paper"><Floorplan/></div></div><div class="mock-status"><span>Ready</span><span>Scale 1:100</span><span>75%　−　＋</span></div></div>; }

function Preview() {
  const route = () => ['account', 'login', 'signup'].includes(location.hash.slice(1)) ? 'account' : 'landing';
  const [screen, setScreen] = createSignal(route());
  const [profile, setProfile] = createSignal(readLocalProfile());
  const [message, setMessage] = createSignal('');
  const [error, setError] = createSignal('');
  const change = () => {setScreen(route()); setMessage(''); setError('');};
  window.addEventListener('hashchange', change);
  onCleanup(() => window.removeEventListener('hashchange', change));
  return <>
    <header class="preview-header"><Mark/><nav aria-label="Main navigation"><a href="#landing">Overview</a><a href="#account">Local profile</a></nav><a class="button button-light header-action" href="./">Open workspace <Arrow/></a></header>
    <main><Show when={screen()==='landing'}><section class="hero"><div class="eyebrow">SPANVISION INFRA / PDF WORKSPACE</div><h1>Clarity,<br/>on every page<span>.</span></h1><div class="hero-bottom"><p>Your documents, drawings and ideas.<br/>One focused workspace to move them forward.</p><div class="hero-actions"><a class="button button-light" href="./">Open workspace <Arrow/></a><a class="button button-outline" href="https://spanvision-infra.vercel.app/">Open scan &amp; OCR in the main workspace</a><small>No account needed. Your files stay yours.</small></div></div><WorkspaceCard/></section></Show>
    <Show when={screen()==='account'}><section class="account-page"><span class="eyebrow">YOUR LOCAL PROFILE</span><h1>Your workspace.</h1><p>Your display name stays in this browser. No sign-in is required.</p><form onSubmit={event=>{event.preventDefault();setMessage('');setError('');try{setProfile(saveLocalProfile(new FormData(event.currentTarget).get('name')));setMessage('Profile saved in this browser.');}catch(reason){setError(reason.message);}}}><label>Display name<input name="name" value={profile().name} maxLength={80} autocomplete="name" placeholder="Your name"/></label><Show when={error()}><p role="alert">{error()}</p></Show><Show when={message()}><p role="status">{message()}</p></Show><button class="button button-light" type="submit">Save profile <Arrow/></button></form></section></Show></main>
    <footer class="preview-footer"><Mark/><span>© 2026 Spanvision Infra</span><div><a href="#account">Local profile</a><a href="notices.md">Open-source notices</a></div></footer>
  </>;
}
render(()=><Preview/>,document.getElementById('preview-root'));
